package main

import (
	"strings"

	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/proto"
	quadsmith_sql "quadsmith/api/gen/quadsmith"
)

func main() {
	protogen.Options{}.Run(func(gen *protogen.Plugin) error {
		for _, f := range gen.Files {
			if !f.Generate {
				continue
			}
			generateFile(gen, f)
		}
		return nil
	})
}

func generateFile(gen *protogen.Plugin, file *protogen.File) {
	hasTables := false
	for _, msg := range file.Messages {
		if proto.HasExtension(msg.Desc.Options(), quadsmith_sql.E_TableName) {
			hasTables = true
			break
		}
	}
	if !hasTables {
		return
	}

	filename := file.GeneratedFilenamePrefix + "_server.pb.go"
	g := gen.NewGeneratedFile(filename, file.GoImportPath)

	g.P("// Code generated by protoc-gen-server. DO NOT EDIT.")
	g.P("package ", file.GoPackageName)
	g.P()
	g.P(`import (`)
	g.P(`	"context"`)
	g.P(`	"connectrpc.com/connect"`)
	g.P(`	"github.com/jackc/pgx/v5/pgxpool"`)
	g.P(`	"quadsmith/api/internal/cel2sql"`)
	g.P(`)`)
	g.P()

	for _, msg := range file.Messages {
		if !proto.HasExtension(msg.Desc.Options(), quadsmith_sql.E_TableName) {
			continue
		}

		msgName := msg.GoIdent.GoName



		// Find the service name
		serviceName := msgName + "Service"

		// We assume pluralization rules based on the name
		pluralName := msgName + "s"
		if strings.HasSuffix(msgName, "y") {
			pluralName = strings.TrimSuffix(msgName, "y") + "ies"
		}

		g.P("type ", serviceName, "Handler struct {")
		g.P("	db *pgxpool.Pool")
		g.P("}")
		g.P()
		g.P("func New", serviceName, "Handler(db *pgxpool.Pool) *", serviceName, "Handler {")
		g.P("	return &", serviceName, "Handler{db: db}")
		g.P("}")
		g.P()

		
		// Get
		g.P("func (s *", serviceName, "Handler) Get", msgName, "(ctx context.Context, req *connect.Request[Get", msgName, "Request]) (*connect.Response[", msgName, "], error) {")
		g.P("	m, err := Get", msgName, "(ctx, s.db, req.Msg.GetId(), req.Msg.GetColumns())")
		g.P("	if err != nil {")
		g.P("		return nil, connect.NewError(connect.CodeInternal, err)")
		g.P("	}")
		g.P("	return connect.NewResponse(m), nil")
		g.P("}")
		g.P()

		// List
		g.P("func (s *", serviceName, "Handler) List", pluralName, "(ctx context.Context, req *connect.Request[List", pluralName, "Request]) (*connect.Response[List", pluralName, "Response], error) {")
		g.P("	where, args, err := cel2sql.Compile(req.Msg.GetFilter())")
		g.P("	if err != nil {")
		g.P("		return nil, connect.NewError(connect.CodeInvalidArgument, err)")
		g.P("	}")
		g.P("	items, err := List", pluralName, "(ctx, s.db, req.Msg.GetColumns(), req.Msg.GetSort(), where, args...)")
		g.P("	if err != nil {")
		g.P("		return nil, connect.NewError(connect.CodeInternal, err)")
		g.P("	}")
		g.P("	res := &List", pluralName, "Response{", pluralName, ": items}")
		g.P("	return connect.NewResponse(res), nil")
		g.P("}")

	}
}
