package main

import (
	"fmt"
	"strings"

	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/reflect/protoreflect"

	// Import the generated sql extension options
	quadsmith_sql "quadsmith/api/gen/quadsmith"
)

func main() {
	protogen.Options{}.Run(func(gen *protogen.Plugin) error {
		g := gen.NewGeneratedFile("schema.sql", "")
		g.P("-- Code generated by protoc-gen-sql. DO NOT EDIT.")
		g.P()

		for _, f := range gen.Files {
			if !f.Generate {
				continue
			}

			for _, msg := range f.Messages {
				generateTable(g, msg)
			}
		}
		return nil
	})
}

func generateTable(g *protogen.GeneratedFile, msg *protogen.Message) {
	opts := msg.Desc.Options()
	if !proto.HasExtension(opts, quadsmith_sql.E_TableName) {
		return
	}

	ext := proto.GetExtension(opts, quadsmith_sql.E_TableName)
	tableName, ok := ext.(string)
	if !ok || tableName == "" {
		return
	}

	g.P("CREATE TABLE IF NOT EXISTS ", tableName, " (")

	var defs []string

	for _, field := range msg.Fields {
		fOpts := field.Desc.Options()

		colName := string(field.Desc.Name())
		colType := sqlDataType(field.Desc)

		if proto.HasExtension(fOpts, quadsmith_sql.E_IsUnique) {
			if isUnq, ok := proto.GetExtension(fOpts, quadsmith_sql.E_IsUnique).(bool); ok && isUnq {
				colType += " UNIQUE"
			}
		}

		defs = append(defs, fmt.Sprintf("%s %s", colName, colType))

		// Check primary key
		if proto.HasExtension(fOpts, quadsmith_sql.E_IsPrimaryKey) {
			if isPk, ok := proto.GetExtension(fOpts, quadsmith_sql.E_IsPrimaryKey).(bool); ok && isPk {
				defs = append(defs, fmt.Sprintf("PRIMARY KEY (%s)", colName))
			}
		}

		// Check foreign key
		if proto.HasExtension(fOpts, quadsmith_sql.E_References) {
			if ref, ok := proto.GetExtension(fOpts, quadsmith_sql.E_References).(string); ok && ref != "" {
				defs = append(defs, fmt.Sprintf("FOREIGN KEY (%s) REFERENCES %s", colName, ref))
			}
		}
	}

	g.P("    ", strings.Join(defs, ",\n    "))
	g.P(");")
	g.P()

	// Generate indexes
	for _, field := range msg.Fields {
		fOpts := field.Desc.Options()
		if proto.HasExtension(fOpts, quadsmith_sql.E_CreateIndex) {
			if isIdx, ok := proto.GetExtension(fOpts, quadsmith_sql.E_CreateIndex).(bool); ok && isIdx {
				colName := string(field.Desc.Name())
				g.P("CREATE INDEX IF NOT EXISTS idx_", tableName, "_", colName, " ON ", tableName, " (", colName, ");")
			}
		}
	}
	g.P()
}

func sqlDataType(desc protoreflect.FieldDescriptor) string {
	name := string(desc.Name())
	kind := desc.Kind()

	if strings.HasSuffix(name, "uuids") && desc.IsList() && kind == protoreflect.StringKind {
		return "UUID[]"
	}
	if strings.HasSuffix(name, "uuid") && kind == protoreflect.StringKind {
		return "UUID"
	}
	switch kind {
	case protoreflect.StringKind:
		return "TEXT"
	case protoreflect.Int32Kind, protoreflect.Int64Kind, protoreflect.Uint32Kind, protoreflect.Uint64Kind:
		return "INTEGER"
	case protoreflect.FloatKind, protoreflect.DoubleKind:
		return "DECIMAL"
	case protoreflect.BoolKind:
		return "BOOLEAN"
	default:
		return "TEXT"
	}
}
