cameras: {
  uuid: "a4c24db1-9024-4e23-9953-3dc8b9613673"
  id: "walksnail-avatar-hd-pro-camera"
  manufacturer: "Walksnail"
  name: "Walksnail Avatar HD Pro Camera"
  weight_g: 9.5
  protocol: "Digital"
  width_mm: 19
}
cameras: {
  uuid: "730c445e-fbf3-4738-910e-3a5aadfa9434"
  id: "walksnail-moonlight-camera"
  manufacturer: "Walksnail"
  name: "Walksnail Moonlight Camera"
  weight_g: 8.9
  protocol: "Digital"
  width_mm: 19
}
cameras: {
  uuid: "37198b31-b5bd-4c9b-918a-ef9ae5e0f5f8"
  id: "dji-o4-lite-camera"
  manufacturer: "DJI"
  name: "DJI O4 Lite Camera"
  weight_g: 3
  protocol: "Digital"
  width_mm: 14
}
cameras: {
  uuid: "cc25d9bf-5c8c-47d0-820f-59effadeb75a"
  id: "dji-o4-wide-camera"
  manufacturer: "DJI"
  name: "DJI O4 Wide Camera"
  weight_g: 41.5
  protocol: "Digital"
  width_mm: 20
}
cameras: {
  uuid: "b09458dc-419a-4be7-9585-f1e40f8bfb7a"
  id: "dji-o4-pro-camera"
  manufacturer: "DJI"
  name: "DJI O4 Pro Camera"
  weight_g: 2.1
  protocol: "Digital"
  width_mm: 25
}
cameras: {
  uuid: "c966b786-ef4b-4c7b-81c2-c911a8790df8"
  id: "caddx-ratel-2"
  manufacturer: "Caddx"
  name: "Caddx Ratel 2"
  weight_g: 5.9
  protocol: "CVBS"
  width_mm: 19
}
cameras: {
  uuid: "c2172e23-8726-415e-9a77-cd2e19041365"
  id: "c04-fpv-camera"
  manufacturer: "BETAFPV"
  name: "C04 FPV Camera"
  weight_g: 1.45
}
cameras: {
  uuid: "aed30e9b-8a77-42dc-ba98-99b55fe484f2"
  id: "air-camera"
  manufacturer: "BETAFPV"
  name: "Air Camera"
  weight_g: 1.48
}
cameras: {
  uuid: "03fb5a8c-95d3-4fdd-9964-0d8a6c11d58c"
  id: "nd-filter-for-dji-o4-pro-camera"
  manufacturer: "BETAFPV"
  name: "ND Filter for DJI O4 Pro Camera"
  weight_g: 1
}
cameras: {
  uuid: "33905170-8ac8-4f90-bbad-b9778fc8d938"
  id: "canopy-for-micro-camera"
  manufacturer: "BETAFPV"
  name: "Canopy for Micro Camera"
  weight_g: 1
}
cameras: {
  uuid: "6871ff57-c355-4f1e-b06c-53b3292e8d5d"
  id: "canopy-for-nano-hd-camera"
  manufacturer: "BETAFPV"
  name: "Canopy for Nano HD Camera"
  weight_g: 1
}
cameras: {
  uuid: "5dc05a7e-b864-422a-9006-eee7f3574d9a"
  id: "caddx-baby-ratel-14mm-nano-1200tvl"
  manufacturer: "BETAFPV"
  name: "Caddx Baby Ratel 14mm Nano 1200TVL"
  description: "Caddx Baby Ratel 14mm Nano 1200TVL 1.8mm FPV Camera"

  weight_g: 3}
cameras: {
  uuid: "379652f5-5b9c-46fb-a88e-fb5f1b54d225"
  id: "caddx-ratel-19mm-micro-starlight-1200tvl"
  manufacturer: "BETAFPV"
  name: "Caddx Ratel 19mm Micro Starlight 1200TVL"
  weight_g: 5.9
  description: "Caddx Ratel 19mm Micro Starlight 1200TVL HDR Low-Light FPV Camera"
}
cameras: {
  uuid: "a66aeb92-28cd-4dd9-a4e1-41d11c7336fd"
  id: "caddx-baby-turtle-camera"
  manufacturer: "BETAFPV"
  name: "Caddx Baby Turtle Camera"

  weight_g: 3}
cameras: {
  uuid: "ff12204d-afe9-42ff-af3b-406da5a843d3"
  id: "smo-4k-camera-adapter-cable"
  manufacturer: "BETAFPV"
  name: "SMO 4K Camera Adapter Cable"
  weight_g: 0.7
}
cameras: {
  uuid: "32181b6a-9cf3-4e82-9f26-2c0db9a24a71"
  id: "case-v2-for-naked-camera"
  manufacturer: "BETAFPV"
  name: "Case V2 for Naked Camera"
  weight_g: 0.82
}
cameras: {
  uuid: "6309c971-466b-4510-8958-9ffff453f89f"
  id: "customized-runcam-split-3-nano-camera"
  manufacturer: "BETAFPV"
  name: "Customized Runcam Split 3 Nano Camera"
  weight_g: 4.5
}
cameras: {
  uuid: "652352a1-f2e3-469b-ae56-fc765d5d8af7"
  id: "customized-caddx-kangaroo-camera"
  manufacturer: "BETAFPV"
  name: "Customized Caddx Kangaroo Camera"
  weight_g: 5.9
}
cameras: {
  uuid: "3928718d-a42a-4a4d-a833-312bcc8b2cc0"
  id: "canopy-for-mini-camera"
  manufacturer: "BETAFPV"
  name: "Canopy for Mini Camera"
  weight_g: 1
}
cameras: {
  uuid: "08f9d1a8-0d93-4c45-b401-473ba59cc77b"
  id: "betapfv-customized-eosv2-fpv-camera-ntsc"
  manufacturer: "BETAFPV"
  name: "BETAPFV Customized EOSV2 FPV Camera NTSC"
  weight_g: 1.48
}
cameras: {
  uuid: "4af6f0c8-516a-416f-a304-429073764ab5"
  id: "caddxfpv-ratel-ultra-analog-camera"
  manufacturer: "CADDXFPV"
  name: "CADDXFPV Ratel Ultra Analog Camera"

  weight_g: 5.9}
cameras: {
  uuid: "249b83ba-8791-47c1-9bbe-7c753d0b47f3"
  id: "caddxfpv-ratel-pro-analog-camera"
  manufacturer: "CADDXFPV"
  name: "CADDXFPV Ratel Pro Analog Camera"
  weight_g: 9.5
}
cameras: {
  uuid: "e30a1ae0-8489-494e-a606-7352d7b09ed0"
  id: "caddxfpv-walnut-action-camera-magnetic-charging"
  manufacturer: "CADDXFPV"
  name: "CADDXFPV Walnut Action Camera Magnetic Charging"
  description: "CADDXFPV Walnut Action Camera Magnetic Charging Part"

  weight_g: 5.9}
cameras: {
  uuid: "e2cfeb86-f048-4a2c-aac9-2dd2971f4832"
  id: "caddxfpv-ant-lite-analog-camera"
  manufacturer: "CADDXFPV"
  name: "CADDXFPV Ant Lite Analog Camera"
  description: "CADDXFPV Ant Lite Analog Camera  (FPV Cycle Edition)"

  weight_g: 1.7}
cameras: {
  uuid: "c8189d00-6037-4298-b5b8-b0c05e75a9a1"
  id: "caddxfpv-camera-lens-family"
  manufacturer: "CADDXFPV"
  name: "CaddxFPV Camera Lens Family"

  weight_g: 5.9}
cameras: {
  uuid: "08d40cf6-f781-4753-b305-e7cd9d98c382"
  id: "darwinfpv-caddx-ant-micro-fpv-camera"
  manufacturer: "DarwinFPV"
  name: "DarwinFPV Caddx Ant  Micro FPV Camera"
  weight_g: 1.7
}
cameras: {
  uuid: "98ea4e86-e810-43c6-8e78-f1dddf36f626"
  id: "runcam-thumb"
  manufacturer: "DarwinFPV"
  name: "RunCam Thumb"
  weight_g: 27
}
cameras: {
  uuid: "d3df2154-1c3e-4bc6-aff7-9258bff0bb33"
  id: "darwinfpv-cement-ultra-durable-fpv-drone"
  manufacturer: "DarwinFPV"
  name: "DarwinFPV Cement Ultra Durable FPV Drone"
  description: "DarwinFPV Cement Ultra Durable FPV Drone Camera"

  weight_g: 3}
cameras: {
  uuid: "960ea027-3926-4d5c-8910-0c0df8c09e90"
  id: "nano-1-mini-action-fpv-camera"
  manufacturer: "DarwinFPV"
  name: "NANO 1 Mini Action FPV Camera"

  weight_g: 1.8}
cameras: {
  uuid: "a9136de0-a6cf-4560-8ce1-2553509c636b"
  id: "darwin-129-professional-customized-camera"
  manufacturer: "DarwinFPV"
  name: "Darwin 129 Professional Customized Camera"
  weight_g: 3.5
}
cameras: {
  uuid: "0ce4d839-208d-4dbb-8c02-1702fad02412"
  id: "newbeedrone-racespec-camera-mount"
  manufacturer: "NewBeeDrone"
  name: "NewBeeDrone RaceSpec Camera Mount"

  weight_g: 1.3}
cameras: {
  uuid: "f704e308-6016-47be-b3a2-40315defb4d6"
  id: "newbeedrone-whoop-training-camera-x3"
  manufacturer: "NewBeeDrone"
  name: "NewBeeDrone Whoop Training Camera x3"

  weight_g: 5.4}
cameras: {
  uuid: "5d65add1-6cf2-4ece-b92f-48ed7f63a515"
  id: "newbeedrone-beeeye-v2-fpv-camera-10-10"
  manufacturer: "NewBeeDrone"
  name: "NewBeeDrone BeeEye V2 FPV Camera 10×10"
  description: "NewBeeDrone BeeEye V2 FPV Camera 10×10 – Ultra-Light 800 TVL"

  weight_g: 19.5}
cameras: {
  uuid: "ca07f0c5-8c5b-4b59-9ad1-90dd31e4ab25"
  id: "newbeedrone-dji-o4-pro-camera-naked"
  manufacturer: "NewBeeDrone"
  name: "NewBeeDrone DJI O4 Pro Camera Naked"
  description: "NewBeeDrone DJI O4 Pro Camera Naked Kit – Lightweight FPV Mod for Drones"

  weight_g: 2.1}
cameras: {
  uuid: "fc343577-630e-481f-be66-39adbafd4453"
  id: "newbeedrone-caddx-nano-ant-camera"
  manufacturer: "Caddx+NewBeeDrone"
  name: "NewBeeDrone × CADDX Nano ANT Camera"
  weight_g: 1.7
  description: "NewBeeDrone × CADDX Nano ANT Camera for BLV5 - Plug-and-Play Replacement"
}
cameras: {
  uuid: "1ab3e82f-8995-47c0-9b7d-fc0d8fceee38"
  id: "newbeedrone-racespec-whoop-racing-camera-mount"
  manufacturer: "NewBeeDrone"
  name: "NewBeeDrone RaceSpec Whoop Racing Camera Mount"
  weight_g: 5.4
  description: "NewBeeDrone RaceSpec Whoop Racing Camera Mount 0.71g (30° or 40°)"
}
cameras: {
  uuid: "6af27f66-7583-47d6-8e2d-9d0a8bc03944"
  id: "newbeedrone-goober-canopy-camera-mount-v2"
  manufacturer: "NewBeeDrone"
  name: "NewBeeDrone Goober Canopy Camera Mount V2"
  weight_g: 1
}
cameras: {
  uuid: "8cdf6eca-77b9-47ab-94f6-063b0a670650"
  id: "newbeedrone-beebrain-camera-connector-type-jst0-8mm"
  manufacturer: "NewBeeDrone"
  name: "NewBeeDrone BeeBrain Camera Connector Type: JST0.8mm"
  description: "NewBeeDrone BeeBrain Camera Connector Type: JST0.8mm 3Pin pack of 2"

  weight_g: 1.3}
cameras: {
  uuid: "6808473e-f92f-4651-90f5-c71d482726fc"
  id: "newbeedrone-beeeye-fpv-camera"
  manufacturer: "NewBeeDrone"
  name: "NewBeeDrone BeeEye FPV Camera"

  weight_g: 19.5}
cameras: {
  uuid: "9dd13ab2-1f68-4917-bda9-d7f460346d7e"
  id: "newbeedrone-beebrain-v2-camera-color-mount"
  manufacturer: "NewBeeDrone"
  name: "NewBeeDrone BeeBrain V2 Camera Color Mount"

  weight_g: 1.3}
cameras: {
  uuid: "15655b79-be1b-46d9-acce-5cfd8d3e2f53"
  id: "aura-analog-fpv-camera"
  manufacturer: "Fat Shark"
  name: "Aura Analog FPV Camera"

  weight_g: 41.6}
cameras: {
  uuid: "d050c125-a311-4d8d-a08e-5739432c2124"
  id: "dual-fpv-camera-switcher"
  manufacturer: "ViFly"
  name: "Dual FPV Camera Switcher"
  weight_g: 0.5
}
cameras: {
  uuid: "c4ae7e47-9f5f-4e68-8cad-5a87980d2369"
  id: "naked-gopro-13-pro-action-camera-v2-1"
  manufacturer: "Flywoo"
  name: "Naked Gopro 13 Pro Action Camera V2.1"
  weight_g: 47.5
}
cameras: {
  uuid: "685aa192-a58a-4675-850c-fab8652a358f"
  id: "punch-shorty-dji-o4-pro-camera-mount"
  manufacturer: "Noozle3D"
  name: "Punch & Shorty DJI O4 Pro Camera Mount"

  weight_g: 1}
cameras: {
  uuid: "11bfbdc7-0409-4595-952d-d3e4a7a4457f"
  id: "cinemini-dji-o4-pro-camera-mount"
  manufacturer: "Noozle3D"
  name: "CineMini DJI O4 Pro Camera Mount"
  description: "CineMini DJI O4 Pro Camera Mount for Naked GoPro Mount"

  weight_g: 1}
cameras: {
  uuid: "5069afda-f6e9-42c0-b3b9-f2080c56012b"
  id: "cl2-dji-o4-pro-camera-mount"
  manufacturer: "Noozle3D"
  name: "CL2 DJI O4 Pro Camera Mount"

  weight_g: 1}
cameras: {
  uuid: "de46be52-cfbf-425e-aedd-a1457d502e9a"
  id: "dji-o4-air-unit-pro-camera-module"
  manufacturer: "DJI"
  name: "DJI O4 Air Unit Pro Camera Module"

  weight_g: 2.1}
cameras: {
  uuid: "90bc0ebe-cb41-4536-9674-0c6aad999c3e"
  id: "thumb-2-action-camera-with-nd-filters"
  manufacturer: "Runcam"
  name: "Thumb 2 Action Camera with ND Filters"
  weight_g: 49
}
cameras: {
  uuid: "3114717a-67c5-4e2b-8fc3-3d58080ea1e1"
  id: "vannystyle-pro-camera-plate-set"
  manufacturer: "Alex Vannover"
  name: "Vannystyle Pro Camera Plate Set"

  weight_g: 125}
cameras: {
  uuid: "a930d1e1-7b1e-4511-adef-c011aaba9dab"
  id: "baby-ratel-2-camera-black"
  manufacturer: "Caddx"
  name: "Baby Ratel 2 Camera - Black"
  weight_g: 9.5
}
cameras: {
  uuid: "fdd65c94-61af-4111-86cb-dd41616220d5"
  id: "toothless-2-micro-camera-black"
  manufacturer: "Foxeer"
  name: "Toothless 2 Micro Camera - Black"
  weight_g: 9.8
}
cameras: {
  uuid: "e645c235-4a6d-4bb4-9bed-5a85dfbf64ba"
  id: "action-camera-nd-filter-set"
  manufacturer: "Flywoo"
  name: "Action Camera ND Filter Set"
  weight_g: 0.6
  description: "Action Camera ND Filter Set For Naked Gopro 12 Pro"
}
cameras: {
  uuid: "de3aa174-ccd0-4867-95aa-e359c2bd33ac"
  id: "naked-gopro-12-pro-action-camera-v2-1"
  manufacturer: "Flywoo"
  name: "Naked Gopro 12 Pro Action Camera V2.1"
  weight_g: 47.5
}
cameras: {
  uuid: "2d12e296-c54a-400c-a0ec-26e214f63d83"
  id: "micro-cat-3-camera-black"
  manufacturer: "Foxeer"
  name: "Micro Cat 3 Camera - Black"
  weight_g: 9.8
}
cameras: {
  uuid: "e8c881fa-68da-4f8a-bb46-d7a0ac0431e3"
  id: "tanq-2-camera-cage-set"
  manufacturer: "Rotor Riot"
  name: "TANQ 2 Camera Cage Set"

  weight_g: 16}
cameras: {
  uuid: "b96a80f6-a535-44f0-bdfa-f27818194dad"
  id: "moxy-camera-plate-choose-version"
  manufacturer: "Rotor Riot"
  name: "Moxy Camera Plate - Choose Version"

  weight_g: 36.4}
cameras: {
  uuid: "5caf807e-d322-492f-8a25-31ddae1159b4"
  id: "rc18g-1-8mm-lens"
  manufacturer: "Runcam"
  name: "RC18G 1.8mm Lens"
  weight_g: 2
  description: "RC18G 1.8mm Lens for DJI and Phoenix Cameras"
}
cameras: {
  uuid: "62b0d311-2943-4e29-9d18-5c7e933598ad"
  id: "skylite-camera-plate-choose-version"
  manufacturer: "Rotor Riot"
  name: "Skylite Camera Plate - Choose Version"

  weight_g: 8.5}
cameras: {
  uuid: "2701e9b6-c2a4-49d5-9403-cc5a58a3454e"
  id: "5-injected-udp-propeller-guard-4-pack"
  manufacturer: "Stan FPV"
  name: "5 Injected UDP Propeller Guard 4-Pack"

  weight_g: 2.32}
cameras: {
  uuid: "e242a371-c30c-4416-a2ce-5a3ad0ee9097"
  id: "hq-4025-2-blade-propellers-1-5mm-shaft"
  manufacturer: "BETAFPV"
  name: "HQ 4025 2-Blade Propellers 1.5mm Shaft"
  weight_g: 1.4
}
cameras: {
  uuid: "71466628-d07a-440c-b36b-a4517de2cbd2"
  id: "x-knight-canopy"
  manufacturer: "BETAFPV"
  name: "X-Knight Canopy"
  weight_g: 142.9
}
cameras: {
  uuid: "15e79617-7cb9-4553-829e-ce87176fd560"
  id: "caddx-vista-digital-hd-system"
  manufacturer: "BETAFPV"
  name: "Caddx Vista Digital HD System"
  description: "Caddx Vista Digital HD System for DJI HD FPV"

  weight_g: 66.9}
cameras: {
  uuid: "d5b69557-aaad-4ad4-a527-f6567d753004"
  id: "caddxfpv-custom-sticker-free-gift"
  manufacturer: "CADDX FPV"
  name: "CaddxFPV Custom Sticker - Free Gift"

  weight_g: 67}
cameras: {
  uuid: "165f5240-8b21-4c9d-8fcb-eb07a0d4ef40"
  id: "caddxfpv-sticker"
  manufacturer: "CADDX FPV"
  name: "CaddxFPV Sticker"

  weight_g: 5.9}
cameras: {
  uuid: "0c466031-28e4-4343-be01-0acb80c2b466"
  id: "caddxfpv-hq-3-blade-propeller-set"
  manufacturer: "CADDX FPV"
  name: "CaddxFPV HQ 3-Blade Propeller Set"
  description: "CaddxFPV HQ 3-Blade Propeller Set (2CW + 2CCW)"

  weight_g: 5}
cameras: {
  uuid: "b34abce8-2792-4f77-8637-afa714ed0fa0"
  id: "caddxfpv-protos-sticker"
  manufacturer: "CADDX FPV"
  name: "CaddxFPV Protos Sticker"

  weight_g: 104.4}
cameras: {
  uuid: "9deab3b5-cb71-4336-9805-b51ea6b54d96"
  id: "caddxfpv-logo-tee"
  manufacturer: "CADDX FPV"
  name: "CaddxFPV Logo Tee"

  weight_g: 5.9}
cameras: {
  uuid: "bcf91dbe-67b4-40dd-ad04-c068d93a8303"
  id: "caddxfpv-logo-cap"
  manufacturer: "CADDX FPV"
  name: "CaddxFPV Logo Cap"

  weight_g: 5.9}
cameras: {
  uuid: "aa9df92b-661f-4480-a762-dddcd78a0012"
  id: "caddxfpv-gofilm-20-power-cord-xt30"
  manufacturer: "CADDXFPV"
  name: "CADDXFPV Gofilm 20 Power Cord XT30"

  weight_g: 38.5}
cameras: {
  uuid: "591cec5a-7e3a-4593-b3fb-ea55447e8a24"
  id: "caddxfpv-hqprop-t2x2x3-2-3-blade-t-mount"
  manufacturer: "CADDXFPV"
  name: "CADDXFPV HQprop T2X2X3 2 3-Blade T-Mount"
  description: "CADDXFPV HQprop T2X2X3 2 3-Blade T-Mount Propeller Set (2x CW / 2x CCW)"

  weight_g: 1.5}
cameras: {
  uuid: "a320ffc5-2ebc-4b21-b600-07a41271cc7a"
  id: "caddxfpv-canvas-tote-bag"
  manufacturer: "CADDXFPV"
  name: "CADDXFPV Canvas Tote Bag"

  weight_g: 160}
cameras: {
  uuid: "9b0c01d0-8fe8-4a57-94d6-c714fc746a5e"
  id: "caddxfpv-banner"
  manufacturer: "CADDXFPV"
  name: "CADDXFPV Banner"

  weight_g: 5.9}
cameras: {
  uuid: "37e24bae-086a-4c98-9b7f-750cd182f2a1"
  id: "caddxfpv-circle"
  manufacturer: "CADDXFPV"
  name: "CADDXFPV Circle"

  weight_g: 5.9}
cameras: {
  uuid: "15d527ba-42f6-43f7-8b2a-47a07701b5a3"
  id: "caddxfpv-arches"
  manufacturer: "CADDXFPV"
  name: "CADDXFPV Arches"

  weight_g: 5.9}
cameras: {
  uuid: "a56cc1ef-2ff3-4aa0-8a66-d7eebe1182ec"
  id: "donut-5145-toroidal-5-props"
  manufacturer: "Foxeer"
  name: "Donut 5145 Toroidal 5 Props"
  weight_g: 4.3
  description: "Donut 5145 Toroidal 5 Props - Choose Color"
}
cameras: {
  uuid: "9f5351b9-21ba-4997-ab38-e7693e76e8d6"
  id: "rotor-riot-kwad-crew-annual-membership"
  manufacturer: "Rotor Riot"
  name: "Rotor Riot Kwad Crew Annual Membership"

  weight_g: 30}
cameras: {
  uuid: "e5427a2c-26e9-49a1-972e-61882c2378a6"
  id: "hglrc-l-series-cameras-low-latency-night"
  manufacturer: "HGLRC"
  name: "HGLRC L-series cameras low latency night"
  description: "HGLRC L-series cameras low latency night vision for FPV Drone"

  weight_g: 11.8}
cameras: {
  uuid: "a6fdb2e3-b95f-4383-833f-9d849df28234"
  id: "runcam-air-unit-wasp-digital-hd"
  manufacturer: "FlyFish-RC"
  name: "RUNCAM Air Unit Wasp Digital HD"
  weight_g: 236.6
  description: "RUNCAM Air Unit Wasp Digital HD FPV Camera System"
}
cameras: {
  uuid: "e44638fc-3761-4c25-9339-090918b520b1"
  id: "runcam-link-wasp-digital-hd-fpv"
  manufacturer: "FlyFish-RC"
  name: "RunCam Link Wasp Digital HD FPV"
  weight_g: 236.6
  description: "RunCam Link Wasp Digital HD FPV Camera System"
}
cameras: {
  uuid: "3de0cd41-8385-44c2-958e-ecddf4dc1fbe"
  id: "nimble65-65mm-analog-1s-mini-whoop"
  manufacturer: "sub250"
  name: "Nimble65 65mm Analog 1S Mini Whoop"
  weight_g: 21
  description: "Nimble65 65mm Analog 1S Mini Whoop Quadcopter"
}
cameras: {
  uuid: "5dfb793c-e1ba-4e5c-b372-d3f7e828d848"
  id: "caddx-camera-for-whoopfly16-nimble65"
  manufacturer: "Sub250"
  name: "Caddx  Camera for Whoopfly16 Nimble65"

  weight_g: 5.9}
cameras: {
  uuid: "e83a5635-68e6-4708-9e8c-154750033395"
  id: "caddx-walnut-fpv-action-camera"
  manufacturer: "Caddx"
  name: "Caddx Walnut FPV Action Camera"
  weight_g: 5.9
}
cameras: {
  uuid: "275a68ac-a872-4fed-860b-4535d696b527"
  id: "caddx-ant-analog-camera-for-nanofly16"
  manufacturer: "sub250"
  name: "Caddx Ant Analog Camera for Nanofly16"

  weight_g: 2}
cameras: {
  uuid: "8334ca23-ce9f-42ac-baa1-1a862ccd11ff"
  id: "caddx-ant-lite-4-3-fpv-camera"
  manufacturer: "FPVCycle"
  name: "Caddx Ant Lite 4:3 FPV Camera"
  description: "Caddx Ant Lite 4:3 FPV Camera - FPVCycle Edition"

  weight_g: 1.7}
cameras: {
  uuid: "9ea9df99-9f44-47b7-8f55-7b16a09cd050"
  id: "fpvcycle-nd-filter"
  manufacturer: "FPVCycle"
  name: "FPVCycle ND Filter"
  description: "FPVCycle ND Filter for GoPro and other Cameras - ND16 - 2 Pack"

  weight_g: 1}
cameras: {
  uuid: "f49bc7c3-45f7-4799-b0cb-1f3bcbeebc23"
  id: "beebrain-v2-camera-mount-and-canopy"
  manufacturer: "FPVCycle"
  name: "BeeBrain V2 Camera Mount and Canopy"
  weight_g: 1
}
cameras: {
  uuid: "3952e2c1-5183-437a-925a-150b9cb3199b"
  id: "c04-camera-and-vtx-module-2"
  manufacturer: "BETAFPV"
  name: "C04 Camera and VTX Module"
  is_internal_only: true
  description: "C04 Camera and VTX Module (Internal Camera)"

  weight_g: 1.45}
cameras: {
  uuid: "7839bc63-6106-48cd-9efe-6f222eac2c34"
  id: "betafpv-nd-filter"
  manufacturer: "BETAFPV"
  name: "BETAFPV ND Filter"
  is_internal_only: true
  description: "BETAFPV ND Filter for DJI O3 Camera (Internal Camera)"

  weight_g: 1}
cameras: {
  uuid: "b4b13a52-cb5e-4cc5-bf10-019917d51098"
  id: "cetus-lite-camera-and-vtx-module-2"
  manufacturer: "BETAFPV"
  name: "Cetus Lite Camera and VTX Module"
  is_internal_only: true
  description: "Cetus Lite Camera and VTX Module (Internal Camera)"

  weight_g: 1.8}
cameras: {
  uuid: "31edf0b8-ee1d-4ad5-8d0a-771aa988922e"
  id: "micro-canopy"
  manufacturer: "BETAFPV"
  name: "Micro Canopy"
  is_internal_only: true
  description: "Micro Canopy for HD Camera (Internal Camera)"

  weight_g: 2.66}
cameras: {
  uuid: "893cb6df-2165-4651-9513-03f9d7149723"
  id: "canopy"
  manufacturer: "BETAFPV"
  name: "Canopy"
  is_internal_only: true
  description: "Canopy for Micro Camera 2022 (Internal Camera)"

  weight_g: 2.66}
cameras: {
  uuid: "3ae6147a-62c0-41af-807b-498187ad1841"
  id: "internal-cam-0e66cabf-e465-4b43-a227-99c191abeb83"
  manufacturer: "BETAFPV"
  name: "Z01 Camera VTX Holder (Internal Camera)"
  is_internal_only: true

  weight_g: 4.14}
cameras: {
  uuid: "affe1a98-59c1-4995-9557-024ba6ac663b"
  id: "h01-aio-camera-5-8g-25mw-vtx-2"
  manufacturer: "BETAFPV"
  name: "H01 AIO Camera 5.8G 25mW VTX"
  is_internal_only: true
  description: "H01 AIO Camera 5.8G 25mW VTX (Internal Camera)"

  weight_g: 32}
cameras: {
  uuid: "a9840e42-a32f-405e-a506-e088b7e9b3c9"
  id: "walksnail-camera-nd-filter-2"
  manufacturer: "CADDX FPV"
  name: "Walksnail Camera ND Filter"
  is_internal_only: true
  description: "Walksnail Camera ND Filter (Internal Camera)"

  weight_g: 1}
cameras: {
  uuid: "efc0f4d9-c140-4c9a-a16d-4f4f21891ed2"
  id: "walksnail-avatar-hd-nano-camera-v3-2"
  manufacturer: "CADDXFPV"
  name: "Walksnail Avatar HD Nano Camera  V3"
  is_internal_only: true
  description: "Walksnail Avatar HD Nano Camera  V3 (Internal Camera)"

  weight_g: 3}
cameras: {
  uuid: "fd823327-4899-463a-8aaf-cb77832924ad"
  id: "walksnail-avatar-hd-camera-v2-2"
  manufacturer: "CADDXFPV"
  name: "Walksnail Avatar HD Camera V2"
  is_internal_only: true
  description: "Walksnail Avatar HD Camera V2 (Internal Camera)"

  weight_g: 1.8}
cameras: {
  uuid: "8ebbe145-186c-47e0-86f8-cca28ff6100c"
  id: "tbs-crossfire-micro-tx-v2-transmitter-2"
  manufacturer: "Team Black Sheep"
  name: "TBS Crossfire Micro TX V2 Transmitter"
  is_internal_only: true
  description: "TBS Crossfire Micro TX V2 Transmitter Module - NDAA (Internal Camera)"

  weight_g: 0.5}
cameras: {
  uuid: "a3e1de00-ce8d-4de5-9568-75f87ec72a72"
  id: "punch-shorty-avatar-v2-dji-o3-2"
  manufacturer: "Noozle3D"
  name: "Punch & Shorty Avatar V2/DJI O3"
  is_internal_only: true
  description: "Punch & Shorty Avatar V2/DJI O3 Camera Mount (Internal Camera)"

  weight_g: 390}
cameras: {
  uuid: "76fa078d-0b74-4ecb-bdf2-627df586c1fc"
  id: "avatar-hd-moonlight-camera"
  manufacturer: "Walksnail"
  name: "Avatar HD Moonlight Camera"
  is_internal_only: true
  description: "Avatar HD Moonlight Camera with Cable (Internal Camera)"

  weight_g: 1.8}
cameras: {
  uuid: "0397717f-d7b4-4fb0-9db7-0dd1b03f0b95"
  id: "avatar-hd-moonlight-vtx-module-2"
  manufacturer: "Walksnail"
  name: "Avatar HD Moonlight VTX Module"
  is_internal_only: true
  description: "Avatar HD Moonlight VTX Module - Without Camera For Avatar HD Video System (Internal Camera)"

  weight_g: 41.6}
cameras: {
  uuid: "b41d2102-c94d-48f0-86b2-7d8be89c77de"
  id: "skylite-skyliner-mk3-dji-o3-6"
  manufacturer: "Rotor Riot"
  name: "Skylite / Skyliner MK3 DJI O3"
  is_internal_only: true
  description: "Skylite / Skyliner MK3 DJI O3 Camera Mount - MJF TPU (Internal Camera)"

  weight_g: 36.4}
cameras: {
  uuid: "6c32270a-28c6-4c48-b109-5319a46cab3b"
  id: "avatar-mini-1s-vtx-6"
  manufacturer: "Walksnail"
  name: "Avatar Mini 1S VTX"
  is_internal_only: true
  description: "Avatar Mini 1S VTX Without Camera for Avatar HD Video System (Internal Camera)"

  weight_g: 1.8}
cameras: {
  uuid: "b71f5bda-a749-46db-b18b-ec41078d33fe"
  id: "avatar-hd-lite-camera"
  manufacturer: "Walksnail"
  name: "Avatar HD Lite Camera"
  is_internal_only: true
  description: "Avatar HD Lite Camera with Cable (Internal Camera)"

  weight_g: 1.8}
cameras: {
  uuid: "5638698c-925e-4d7a-ac25-6ac0e2a32dc1"
  id: "avatar-hd-pro-camera"
  manufacturer: "Walksnail"
  name: "Avatar HD Pro Camera"
  is_internal_only: true
  description: "Avatar HD Pro Camera with Cable (Internal Camera)"

  weight_g: 9.5}
cameras: {
  uuid: "2c64a195-38b7-4cb7-ae95-ffa50ab633b2"
  id: "avatar-hd-camera-v2"
  manufacturer: "Walksnail"
  name: "Avatar HD Camera V2"
  is_internal_only: true
  description: "Avatar HD Camera V2 with Cable (Internal Camera)"

  weight_g: 9.5}
cameras: {
  uuid: "84db6a38-680a-4e18-bba7-4c5759d8a9d9"
  id: "skylite-skyliner-mk3-dji-o3-7"
  manufacturer: "Noozle3D"
  name: "Skylite / Skyliner MK3 DJI O3"
  is_internal_only: true
  description: "Skylite / Skyliner MK3 DJI O3 Camera Mount - Choose Color (Internal Camera)"

  weight_g: 8.3}
cameras: {
  uuid: "c6042efb-d2fc-464f-a6fa-4a1a11986e9a"
  id: "c04-camera-and-vtx-module-3"
  manufacturer: "BETAFPV"
  name: "C04 Camera and VTX Module"
  is_internal_only: true
  description: "C04 Camera and VTX Module (Internal Camera)"

  weight_g: 1.45}
cameras: {
  uuid: "7bb59852-4441-42f2-a39a-3946eb3e6434"
  id: "betafpv-nd-filter-2"
  manufacturer: "BETAFPV"
  name: "BETAFPV ND Filter"
  is_internal_only: true
  description: "BETAFPV ND Filter for DJI O3 Camera (Internal Camera)"

  weight_g: 1}
cameras: {
  uuid: "7fef63f6-221b-49a7-a75c-6a7e1c3117ea"
  id: "cetus-lite-camera-and-vtx-module-3"
  manufacturer: "BETAFPV"
  name: "Cetus Lite Camera and VTX Module"
  is_internal_only: true
  description: "Cetus Lite Camera and VTX Module (Internal Camera)"

  weight_g: 1.8}
cameras: {
  uuid: "f100cbef-80b3-4adf-bf6f-c5a01802b527"
  id: "micro-canopy-2"
  manufacturer: "BETAFPV"
  name: "Micro Canopy"
  is_internal_only: true
  description: "Micro Canopy for HD Camera (Internal Camera)"

  weight_g: 2.66}
cameras: {
  uuid: "72e5c3c6-aabd-4155-8d42-317a64e7380b"
  id: "canopy-2"
  manufacturer: "BETAFPV"
  name: "Canopy"
  is_internal_only: true
  description: "Canopy for Micro Camera 2022 (Internal Camera)"

  weight_g: 2.66}
cameras: {
  uuid: "6d7af870-5146-489c-9f5e-b41fef31f5e9"
  id: "internal-cam-6f5303f0-18e4-40e3-b3ff-3ab57c5fed2a"
  manufacturer: "BETAFPV"
  name: "Z01 Camera VTX Holder (Internal Camera)"
  is_internal_only: true

  weight_g: 4.14}
cameras: {
  uuid: "d6e24edc-371b-437d-9479-1902bbd1620b"
  id: "h01-aio-camera-5-8g-25mw-vtx-3"
  manufacturer: "BETAFPV"
  name: "H01 AIO Camera 5.8G 25mW VTX"
  is_internal_only: true
  description: "H01 AIO Camera 5.8G 25mW VTX (Internal Camera)"

  weight_g: 32}
cameras: {
  uuid: "a8d3c4e2-00a1-40bd-953e-29b140fe52b8"
  id: "walksnail-camera-nd-filter-3"
  manufacturer: "CADDX FPV"
  name: "Walksnail Camera ND Filter"
  is_internal_only: true
  description: "Walksnail Camera ND Filter (Internal Camera)"

  weight_g: 1}
cameras: {
  uuid: "6050bc22-e8ac-41b8-8982-b561f9f8999c"
  id: "walksnail-avatar-hd-nano-camera-v3-3"
  manufacturer: "CADDXFPV"
  name: "Walksnail Avatar HD Nano Camera  V3"
  is_internal_only: true
  description: "Walksnail Avatar HD Nano Camera  V3 (Internal Camera)"

  weight_g: 3}
cameras: {
  uuid: "7efe74ac-6926-42cf-916a-d31efd76775d"
  id: "walksnail-avatar-hd-camera-v2-3"
  manufacturer: "CADDXFPV"
  name: "Walksnail Avatar HD Camera V2"
  is_internal_only: true
  description: "Walksnail Avatar HD Camera V2 (Internal Camera)"

  weight_g: 1.8}
cameras: {
  uuid: "bf715803-5971-478c-afbc-76cb9aa67bfa"
  id: "tbs-crossfire-micro-tx-v2-transmitter-3"
  manufacturer: "Team Black Sheep"
  name: "TBS Crossfire Micro TX V2 Transmitter"
  is_internal_only: true
  description: "TBS Crossfire Micro TX V2 Transmitter Module - NDAA (Internal Camera)"

  weight_g: 0.5}
cameras: {
  uuid: "ec9cc6f1-f291-47b6-bf10-b4add14da0cf"
  id: "punch-shorty-avatar-v2-dji-o3-3"
  manufacturer: "Noozle3D"
  name: "Punch & Shorty Avatar V2/DJI O3"
  is_internal_only: true
  description: "Punch & Shorty Avatar V2/DJI O3 Camera Mount (Internal Camera)"

  weight_g: 390}
cameras: {
  uuid: "a5e2eeaf-9076-4350-83cc-49f78bc57cb9"
  id: "avatar-hd-moonlight-camera-2"
  manufacturer: "Walksnail"
  name: "Avatar HD Moonlight Camera"
  is_internal_only: true
  description: "Avatar HD Moonlight Camera with Cable (Internal Camera)"

  weight_g: 1.8}
cameras: {
  uuid: "0a5453e2-f073-4e8d-89be-b8b8d81df47b"
  id: "avatar-hd-moonlight-vtx-module-3"
  manufacturer: "Walksnail"
  name: "Avatar HD Moonlight VTX Module"
  is_internal_only: true
  description: "Avatar HD Moonlight VTX Module - Without Camera For Avatar HD Video System (Internal Camera)"

  weight_g: 41.6}
cameras: {
  uuid: "2c5b6146-2e5b-42c6-8a5d-ade3fc03c1c8"
  id: "skylite-skyliner-mk3-dji-o3-8"
  manufacturer: "Rotor Riot"
  name: "Skylite / Skyliner MK3 DJI O3"
  is_internal_only: true
  description: "Skylite / Skyliner MK3 DJI O3 Camera Mount - MJF TPU (Internal Camera)"

  weight_g: 36.4}
cameras: {
  uuid: "92b1f38d-ea33-49dd-b82b-34ec7e3e5c57"
  id: "avatar-mini-1s-vtx-7"
  manufacturer: "Walksnail"
  name: "Avatar Mini 1S VTX"
  is_internal_only: true
  description: "Avatar Mini 1S VTX Without Camera for Avatar HD Video System (Internal Camera)"

  weight_g: 1.8}
cameras: {
  uuid: "465cf3e3-eb90-42a8-b099-5e7af8847128"
  id: "avatar-hd-lite-camera-2"
  manufacturer: "Walksnail"
  name: "Avatar HD Lite Camera"
  is_internal_only: true
  description: "Avatar HD Lite Camera with Cable (Internal Camera)"

  weight_g: 1.8}
cameras: {
  uuid: "9e4b6a0f-04fb-493d-8a76-ef31a5d0df92"
  id: "avatar-hd-pro-camera-2"
  manufacturer: "Walksnail"
  name: "Avatar HD Pro Camera"
  is_internal_only: true
  description: "Avatar HD Pro Camera with Cable (Internal Camera)"

  weight_g: 9.5}
cameras: {
  uuid: "52a630a1-9ce3-4713-8fba-a823eb862443"
  id: "avatar-hd-camera-v2-2"
  manufacturer: "Walksnail"
  name: "Avatar HD Camera V2"
  is_internal_only: true
  description: "Avatar HD Camera V2 with Cable (Internal Camera)"

  weight_g: 9.5}
cameras: {
  uuid: "2710a442-d640-49c3-bb75-fb18702ac6f7"
  id: "skylite-skyliner-mk3-dji-o3-9"
  manufacturer: "Noozle3D"
  name: "Skylite / Skyliner MK3 DJI O3"
  is_internal_only: true
  description: "Skylite / Skyliner MK3 DJI O3 Camera Mount - Choose Color (Internal Camera)"

  weight_g: 8.3}
cameras: {
  uuid: "e7e622d0-22ad-4d7b-8aef-e8446a155e02"
  id: "c04-camera-and-vtx-module-4"
  manufacturer: "BETAFPV"
  name: "C04 Camera and VTX Module"
  is_internal_only: true
  description: "C04 Camera and VTX Module (Internal Camera)"

  weight_g: 1.45}
cameras: {
  uuid: "f88e66e8-125f-423f-b04e-a021e065aab8"
  id: "betafpv-nd-filter-3"
  manufacturer: "BETAFPV"
  name: "BETAFPV ND Filter"
  is_internal_only: true
  description: "BETAFPV ND Filter for DJI O3 Camera (Internal Camera)"

  weight_g: 1}
cameras: {
  uuid: "8a6471fe-c90d-4f81-9f9e-370defacef6c"
  id: "cetus-lite-camera-and-vtx-module-4"
  manufacturer: "BETAFPV"
  name: "Cetus Lite Camera and VTX Module"
  is_internal_only: true
  description: "Cetus Lite Camera and VTX Module (Internal Camera)"

  weight_g: 1.8}
cameras: {
  uuid: "3e5d1ae4-2669-475d-9240-8ae29879ade8"
  id: "micro-canopy-3"
  manufacturer: "BETAFPV"
  name: "Micro Canopy"
  is_internal_only: true
  description: "Micro Canopy for HD Camera (Internal Camera)"

  weight_g: 2.66}
cameras: {
  uuid: "2435d35e-2e0c-43a6-9c8b-294cc0260605"
  id: "canopy-3"
  manufacturer: "BETAFPV"
  name: "Canopy"
  is_internal_only: true
  description: "Canopy for Micro Camera 2022 (Internal Camera)"

  weight_g: 2.66}
cameras: {
  uuid: "44d092c0-a18a-4644-b59a-c136950a0b60"
  id: "internal-cam-52170b0c-b668-4671-8a17-b8b60ebed774"
  manufacturer: "BETAFPV"
  name: "Z01 Camera VTX Holder (Internal Camera)"
  is_internal_only: true

  weight_g: 4.14}
cameras: {
  uuid: "40adaee2-4507-48af-9336-0d8a6ee603f7"
  id: "h01-aio-camera-5-8g-25mw-vtx-4"
  manufacturer: "BETAFPV"
  name: "H01 AIO Camera 5.8G 25mW VTX"
  is_internal_only: true
  description: "H01 AIO Camera 5.8G 25mW VTX (Internal Camera)"

  weight_g: 32}
cameras: {
  uuid: "3988130a-f95f-4493-b2cd-7d24449ccf54"
  id: "walksnail-camera-nd-filter-4"
  manufacturer: "CADDX FPV"
  name: "Walksnail Camera ND Filter"
  is_internal_only: true
  description: "Walksnail Camera ND Filter (Internal Camera)"

  weight_g: 1}
cameras: {
  uuid: "f5285cbc-1dfa-4e88-9de3-27fcbfbf911f"
  id: "walksnail-avatar-hd-nano-camera-v3-4"
  manufacturer: "CADDXFPV"
  name: "Walksnail Avatar HD Nano Camera  V3"
  is_internal_only: true
  description: "Walksnail Avatar HD Nano Camera  V3 (Internal Camera)"

  weight_g: 3}
cameras: {
  uuid: "f892e6aa-2d2d-436f-8b0f-a008809e2291"
  id: "walksnail-avatar-hd-camera-v2-4"
  manufacturer: "CADDXFPV"
  name: "Walksnail Avatar HD Camera V2"
  is_internal_only: true
  description: "Walksnail Avatar HD Camera V2 (Internal Camera)"

  weight_g: 1.8}
cameras: {
  uuid: "09cd4546-3d2b-4ae6-b68d-d5b282d9f195"
  id: "tbs-crossfire-micro-tx-v2-transmitter-4"
  manufacturer: "Team Black Sheep"
  name: "TBS Crossfire Micro TX V2 Transmitter"
  is_internal_only: true
  description: "TBS Crossfire Micro TX V2 Transmitter Module - NDAA (Internal Camera)"

  weight_g: 0.5}
cameras: {
  uuid: "d9f35540-33dd-4f3d-afc5-4f7034b2d32a"
  id: "punch-shorty-avatar-v2-dji-o3-4"
  manufacturer: "Noozle3D"
  name: "Punch & Shorty Avatar V2/DJI O3"
  is_internal_only: true
  description: "Punch & Shorty Avatar V2/DJI O3 Camera Mount (Internal Camera)"

  weight_g: 390}
cameras: {
  uuid: "7ece214e-2136-4010-be97-d031ad6890a2"
  id: "avatar-hd-moonlight-camera-3"
  manufacturer: "Walksnail"
  name: "Avatar HD Moonlight Camera"
  is_internal_only: true
  description: "Avatar HD Moonlight Camera with Cable (Internal Camera)"

  weight_g: 1.8}
cameras: {
  uuid: "5076bd2d-20c7-4fce-a9b9-91009ee51894"
  id: "avatar-hd-moonlight-vtx-module-4"
  manufacturer: "Walksnail"
  name: "Avatar HD Moonlight VTX Module"
  is_internal_only: true
  description: "Avatar HD Moonlight VTX Module - Without Camera For Avatar HD Video System (Internal Camera)"

  weight_g: 41.6}
cameras: {
  uuid: "3f5dd7e6-2573-43f8-acc2-c4575317f28d"
  id: "skylite-skyliner-mk3-dji-o3-10"
  manufacturer: "Rotor Riot"
  name: "Skylite / Skyliner MK3 DJI O3"
  is_internal_only: true
  description: "Skylite / Skyliner MK3 DJI O3 Camera Mount - MJF TPU (Internal Camera)"

  weight_g: 36.4}
cameras: {
  uuid: "4b3c9e01-f3f9-4cbd-8ac4-1ede66c0e7e5"
  id: "avatar-mini-1s-vtx-8"
  manufacturer: "Walksnail"
  name: "Avatar Mini 1S VTX"
  is_internal_only: true
  description: "Avatar Mini 1S VTX Without Camera for Avatar HD Video System (Internal Camera)"

  weight_g: 1.8}
cameras: {
  uuid: "5b9a8d74-bd35-40fb-9548-27b03f873019"
  id: "avatar-hd-lite-camera-3"
  manufacturer: "Walksnail"
  name: "Avatar HD Lite Camera"
  is_internal_only: true
  description: "Avatar HD Lite Camera with Cable (Internal Camera)"

  weight_g: 1.8}
cameras: {
  uuid: "d2683d44-3e20-4f77-8267-0b327bad935c"
  id: "avatar-hd-pro-camera-3"
  manufacturer: "Walksnail"
  name: "Avatar HD Pro Camera"
  is_internal_only: true
  description: "Avatar HD Pro Camera with Cable (Internal Camera)"

  weight_g: 9.5}
cameras: {
  uuid: "e37142f1-82fa-4b3f-bd93-1d8929990606"
  id: "avatar-hd-camera-v2-3"
  manufacturer: "Walksnail"
  name: "Avatar HD Camera V2"
  is_internal_only: true
  description: "Avatar HD Camera V2 with Cable (Internal Camera)"

  weight_g: 9.5}
cameras: {
  uuid: "c38400c1-1a05-4387-b9c0-131d736ca537"
  id: "skylite-skyliner-mk3-dji-o3-11"
  manufacturer: "Noozle3D"
  name: "Skylite / Skyliner MK3 DJI O3"
  is_internal_only: true
  description: "Skylite / Skyliner MK3 DJI O3 Camera Mount - Choose Color (Internal Camera)"

  weight_g: 8.3}
cameras: {
  uuid: "ae8159e5-08b9-4731-b7b3-85729f4a7292"
  id: "hglrc-zeus-nano-vtx-350mw-16x16-2"
  manufacturer: "HGLRC"
  name: "HGLRC Zeus nano VTX 350mW 16x16"
  is_internal_only: true
  description: "HGLRC Zeus nano VTX 350mW 16x16 20x20 25.5x25.5 mm For FPV Racing Drone (Internal Camera)"

  weight_g: 2.4}
