frames:  {
  uuid:  "73382232-1424-4e72-aed7-6a663a5608ec"
  id:  "impulserc-apex-evo-5\""
  manufacturer:  "ImpulseRC"
  name:  "ImpulseRC Apex EVO 5\""
  weight_g:  138
  wheelbase_mm:  225
  max_prop_size_mm:  129.54
  geometry:  "Deadcat"
  description:  "ImpulseRC ImpulseRC Apex EVO 5\" Deadcat drone frame with 225.0mm wheelbase, supporting up to 129.5mm props, weighing 138.0g."
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://www.getfpv.com/fpv/frames.html"
  }
}
frames:  {
  uuid:  "295b1a5b-c9c9-49bd-9eb3-93422d525bf8"
  id:  "iflight-aos-5-v5"
  manufacturer:  "iFlight"
  name:  "iFlight AOS 5 V5"
  weight_g:  120
  wheelbase_mm:  228
  max_prop_size_mm:  132.08
  geometry:  "True-X"
  description:  "iFlight iFlight AOS 5 V5 True-X drone frame with 228.0mm wheelbase, supporting up to 132.1mm props, weighing 120.0g."
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://www.getfpv.com/fpv/frames.html"
  }
}
frames:  {
  uuid:  "498c4fd2-cf55-4022-ac48-cc400e490313"
  id:  "flyfishrc-volador-ii-vx5"
  manufacturer:  "FlyFishRC"
  name:  "FlyFishRC Volador II VX5"
  weight_g:  177.4
  wheelbase_mm:  225
  max_prop_size_mm:  129.54
  geometry:  "Deadcat"
  description:  "FlyFishRC FlyFishRC Volador II VX5 Deadcat drone frame with 225.0mm wheelbase, supporting up to 129.5mm props, weighing 177.4g."
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PRODUCT_PAGE
    url:  "https://flyfish-rc.com/collections/frames"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://flyfish-rc.com/collections/frames"
  }
}
frames:  {
  uuid:  "8fd51fba-8f88-4178-9797-f73ad4e1b45b"
  id:  "caddx-gofilm-20-frame"
  manufacturer:  "Caddx"
  name:  "Caddx Gofilm 20 Frame"
  weight_g:  38.5
  wheelbase_mm:  94
  max_prop_size_mm:  51.05
  geometry:  "True-X"
  description:  "Caddx Caddx Gofilm 20 Frame True-X drone frame with 94.0mm wheelbase, supporting up to 51.0mm props, weighing 38.5g."
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://www.getfpv.com/fpv/frames.html"
  }
}
frames:  {
  uuid:  "923b27f5-5b9f-47d4-9920-98c5477bc577"
  id:  "happymodel-mobula8-frame"
  manufacturer:  "Happymodel"
  name:  "Happymodel Mobula8 Frame"
  weight_g:  7.75
  wheelbase_mm:  80
  max_prop_size_mm:  51.05
  geometry:  "True-X"
  description:  "Happymodel Happymodel Mobula8 Frame True-X drone frame with 80.0mm wheelbase, supporting up to 51.0mm props, weighing 7.8g."
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://www.getfpv.com/fpv/frames.html"
  }
}
frames:  {
  uuid:  "322f0ecd-c122-4eb8-b709-5325247be75c"
  id:  "betafpv-meteor75-pro-frame"
  manufacturer:  "BETAFPV"
  name:  "BetaFPV Meteor75 Pro Frame"
  weight_g:  7.73
  wheelbase_mm:  80.8
  max_prop_size_mm:  44.96
  geometry:  "True-X"
  description:  "BETAFPV BetaFPV Meteor75 Pro Frame True-X drone frame with 80.8mm wheelbase, supporting up to 45.0mm props, weighing 7.7g."
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PRODUCT_PAGE
    url:  "https://betafpv.com/collections/frames"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_DOCUMENTATION
    url:  "https://support.betafpv.com"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://betafpv.com/collections/frames"
  }
}
frames:  {
  uuid:  "01a11091-1f13-7669-9fc3-1a04513f663e"
  id:  "betafpv-pavo35"
  manufacturer:  "BETAFPV"
  name:  "BetaFPV Pavo35 Brushless Whoop Frame"
  weight_g:  113.9
  wheelbase_mm:  148
  max_prop_size_mm:  88.9
  geometry:  "Whoop"
  description:  "BETAFPV BetaFPV Pavo35 Brushless Whoop Frame Whoop drone frame with 148.0mm wheelbase, supporting up to 88.9mm props, weighing 113.9g."
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PRODUCT_PAGE
    url:  "https://betafpv.com/collections/frames"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_DOCUMENTATION
    url:  "https://support.betafpv.com"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://betafpv.com/collections/frames"
  }
}
frames:  {
  uuid:  "01a11091-1f13-7669-9fc3-1a0f09b08af6"
  id:  "darwinfpv-babyape-pro-v2"
  manufacturer:  "DarwinFPV"
  name:  "DarwinFPV BabyApe Pro V2 Frame"
  weight_g:  35.7
  wheelbase_mm:  93.9
  max_prop_size_mm:  50.8
  geometry:  "True X"
  description:  "DarwinFPV DarwinFPV BabyApe Pro V2 Frame True X drone frame with 93.9mm wheelbase, supporting up to 50.8mm props, weighing 35.7g."
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PRODUCT_PAGE
    url:  "https://darwinfpv.com/collections/frame"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://darwinfpv.com/collections/frame"
  }
}
frames:  {
  uuid:  "9f7e3250-b461-473d-9337-5f8b6de97b98"
  id:  "meteor75-pro-ii-brushless-whoop-frame"
  manufacturer:  "BETAFPV"
  name:  "Meteor75 Pro II Brushless Whoop Frame"
  weight_g:  4.6
  wheelbase_mm:  70
  max_prop_size_mm:  31
  geometry:  "Whoop"
  description:  "BETAFPV Meteor75 Pro II Brushless Whoop Frame Whoop drone frame with 70.0mm wheelbase, supporting up to 31.0mm props, weighing 4.6g."
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PRODUCT_PAGE
    url:  "https://betafpv.com/collections/frames"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_DOCUMENTATION
    url:  "https://support.betafpv.com"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://betafpv.com/collections/frames"
  }
}
frames:  {
  uuid:  "4b3bb0c4-d86e-49f7-8bd9-cabeeaac8cba"
  id:  "meteor65-pro-ii-brushless-whoop-frame"
  manufacturer:  "BETAFPV"
  name:  "Meteor65 Pro II Brushless Whoop Frame"
  weight_g:  4.6
  wheelbase_mm:  70
  max_prop_size_mm:  31
  geometry:  "Whoop"
  description:  "BETAFPV Meteor65 Pro II Brushless Whoop Frame Whoop drone frame with 70.0mm wheelbase, supporting up to 31.0mm props, weighing 4.6g."
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PRODUCT_PAGE
    url:  "https://betafpv.com/collections/frames"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_DOCUMENTATION
    url:  "https://support.betafpv.com"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://betafpv.com/collections/frames"
  }
}
frames:  {
  uuid:  "897c310c-aa29-4044-b690-4df80f4841d7"
  id:  "aquila20-brushless-whoop-frame"
  manufacturer:  "BETAFPV"
  name:  "Aquila20 Brushless Whoop Frame"
  weight_g:  35.7
  wheelbase_mm:  93.9
  max_prop_size_mm:  50.8
  geometry:  "Whoop"
  description:  "BETAFPV Aquila20 Brushless Whoop Frame Whoop drone frame with 93.9mm wheelbase, supporting up to 50.8mm props, weighing 35.7g."
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PRODUCT_PAGE
    url:  "https://betafpv.com/collections/frames"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_DOCUMENTATION
    url:  "https://support.betafpv.com"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://betafpv.com/collections/frames"
  }
}
frames:  {
  uuid:  "e3b85283-67b5-4f38-a425-6bff050bbc8c"
  id:  "air65-champion-brushless-whoop-frame"
  manufacturer:  "BETAFPV"
  name:  "Air65 Champion Brushless Whoop Frame"
  weight_g:  2.2
  wheelbase_mm:  65
  max_prop_size_mm:  31
  geometry:  "Whoop"
  description:  "BETAFPV Air65 Champion Brushless Whoop Frame Whoop drone frame with 65.0mm wheelbase, supporting up to 31.0mm props, weighing 2.2g."
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PRODUCT_PAGE
    url:  "https://betafpv.com/collections/frames"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_DOCUMENTATION
    url:  "https://support.betafpv.com"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://betafpv.com/collections/frames"
  }
}
frames:  {
  uuid:  "fc7fc867-9fd5-47cb-8e03-bfb1d447cd03"
  id:  "pavo20-pro-ii-brushless-whoop-frame"
  manufacturer:  "BETAFPV"
  name:  "Pavo20 Pro II Brushless Whoop Frame"
  weight_g:  35.7
  wheelbase_mm:  93.9
  max_prop_size_mm:  50.8
  geometry:  "Whoop"
  description:  "BETAFPV Pavo20 Pro II Brushless Whoop Frame Whoop drone frame with 93.9mm wheelbase, supporting up to 50.8mm props, weighing 35.7g."
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PRODUCT_PAGE
    url:  "https://betafpv.com/collections/frames"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_DOCUMENTATION
    url:  "https://support.betafpv.com"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://betafpv.com/collections/frames"
  }
}
frames:  {
  uuid:  "c87dc2c1-732b-43a5-8044-bd193132af88"
  id:  "pavo-pico-ii-brushless-whoop-frame"
  manufacturer:  "BETAFPV"
  name:  "Pavo Pico II Brushless Whoop Frame"
  weight_g:  19
  wheelbase_mm:  80
  max_prop_size_mm:  40
  geometry:  "Whoop"
  description:  "BETAFPV Pavo Pico II Brushless Whoop Frame Whoop drone frame with 80.0mm wheelbase, supporting up to 40.0mm props, weighing 19.0g."
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PRODUCT_PAGE
    url:  "https://betafpv.com/collections/frames"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_DOCUMENTATION
    url:  "https://support.betafpv.com"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://betafpv.com/collections/frames"
  }
}
frames:  {
  uuid:  "a1c01820-381d-4764-a3df-455151d1f247"
  id:  "air75-ii-brushless-whoop-frame"
  manufacturer:  "BETAFPV"
  name:  "Air75 II Brushless Whoop Frame"
  weight_g:  4
  wheelbase_mm:  75
  max_prop_size_mm:  40
  geometry:  "Whoop"
  description:  "BETAFPV Air75 II Brushless Whoop Frame Whoop drone frame with 75.0mm wheelbase, supporting up to 40.0mm props, weighing 4.0g."
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PRODUCT_PAGE
    url:  "https://betafpv.com/collections/frames"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_DOCUMENTATION
    url:  "https://support.betafpv.com"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://betafpv.com/collections/frames"
  }
}
frames:  {
  uuid:  "259ca8f0-14d4-4525-a944-05803452268b"
  id:  "air65-ii-brushless-whoop-frame"
  manufacturer:  "BETAFPV"
  name:  "Air65 II Brushless Whoop Frame"
  weight_g:  2.65
  wheelbase_mm:  65
  max_prop_size_mm:  31
  geometry:  "Whoop"
  description:  "BETAFPV Air65 II Brushless Whoop Frame Whoop drone frame with 65.0mm wheelbase, supporting up to 31.0mm props, weighing 2.7g."
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PRODUCT_PAGE
    url:  "https://betafpv.com/collections/frames"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_DOCUMENTATION
    url:  "https://support.betafpv.com"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://betafpv.com/collections/frames"
  }
}
frames:  {
  uuid:  "10a092c4-55c8-43af-b125-998aa30b7d60"
  id:  "pavo20-pro-brushless-whoop-frame"
  manufacturer:  "BETAFPV"
  name:  "Pavo20 Pro Brushless Whoop Frame"
  weight_g:  35.7
  wheelbase_mm:  93.9
  max_prop_size_mm:  50.8
  geometry:  "Whoop"
  description:  "BETAFPV Pavo20 Pro Brushless Whoop Frame Whoop drone frame with 93.9mm wheelbase, supporting up to 50.8mm props, weighing 35.7g."
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PRODUCT_PAGE
    url:  "https://betafpv.com/collections/frames"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_DOCUMENTATION
    url:  "https://support.betafpv.com"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://betafpv.com/collections/frames"
  }
}
frames:  {
  uuid:  "b7927287-7978-45ad-81d5-35a268872d7b"
  id:  "pavo-femto-brushless-whoop-frame"
  manufacturer:  "BETAFPV"
  name:  "Pavo Femto Brushless Whoop Frame"
  weight_g:  8.64
  wheelbase_mm:  75
  max_prop_size_mm:  40
  geometry:  "Whoop"
  description:  "BETAFPV Pavo Femto Brushless Whoop Frame Whoop drone frame with 75.0mm wheelbase, supporting up to 40.0mm props, weighing 8.6g."
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PRODUCT_PAGE
    url:  "https://betafpv.com/collections/frames"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_DOCUMENTATION
    url:  "https://support.betafpv.com"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://betafpv.com/collections/frames"
  }
}
frames:  {
  uuid:  "15418cec-962b-4aef-a6a6-d37dc357aabc"
  id:  "x-knight-carbon-fiber-frame-kit"
  manufacturer:  "BETAFPV"
  name:  "X-Knight Carbon Fiber Frame Kit"
  weight_g:  19
  wheelbase_mm:  80
  max_prop_size_mm:  40
  geometry:  "True X"
  description:  "BETAFPV X-Knight Carbon Fiber Frame Kit True X drone frame with 80.0mm wheelbase, supporting up to 40.0mm props, weighing 19.0g."
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PRODUCT_PAGE
    url:  "https://betafpv.com/collections/frames"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_DOCUMENTATION
    url:  "https://support.betafpv.com"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://betafpv.com/collections/frames"
  }
}
frames:  {
  uuid:  "daea0f68-49fa-4e1e-b885-5b22e60cee60"
  id:  "pavo25-frame-kit"
  manufacturer:  "BETAFPV"
  name:  "Pavo25 Frame Kit"
  weight_g:  35.7
  wheelbase_mm:  93.9
  max_prop_size_mm:  50.8
  geometry:  "Whoop"
  description:  "BETAFPV Pavo25 Frame Kit Whoop drone frame with 93.9mm wheelbase, supporting up to 50.8mm props, weighing 35.7g."
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PRODUCT_PAGE
    url:  "https://betafpv.com/collections/frames"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_DOCUMENTATION
    url:  "https://support.betafpv.com"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://betafpv.com/collections/frames"
  }
}
frames:  {
  uuid:  "5a6f0c7d-2686-4f2f-9642-d62e85af098f"
  id:  "air75-brushless-whoop-frame"
  manufacturer:  "BETAFPV"
  name:  "Air75 Brushless Whoop Frame"
  weight_g:  4.45
  wheelbase_mm:  75
  max_prop_size_mm:  40
  geometry:  "Whoop"
  description:  "BETAFPV Air75 Brushless Whoop Frame Whoop drone frame with 75.0mm wheelbase, supporting up to 40.0mm props, weighing 4.4g."
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PRODUCT_PAGE
    url:  "https://betafpv.com/collections/frames"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_DOCUMENTATION
    url:  "https://support.betafpv.com"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://betafpv.com/collections/frames"
  }
}
frames:  {
  uuid:  "399e90a0-055c-4157-ab29-0cd39589aef3"
  id:  "pavo35-brushless-whoop-frame"
  manufacturer:  "BETAFPV"
  name:  "Pavo35 Brushless Whoop Frame"
  weight_g:  113.9
  wheelbase_mm:  148
  max_prop_size_mm:  88.9
  geometry:  "Whoop"
  description:  "BETAFPV Pavo35 Brushless Whoop Frame Whoop drone frame with 148.0mm wheelbase, supporting up to 88.9mm props, weighing 113.9g."
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PRODUCT_PAGE
    url:  "https://betafpv.com/collections/frames"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_DOCUMENTATION
    url:  "https://support.betafpv.com"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://betafpv.com/collections/frames"
  }
}
frames:  {
  uuid:  "5453fbc1-e672-4256-81f2-d783d76ec0f8"
  id:  "pavo25-v2-brushless-whoop-frame"
  manufacturer:  "BETAFPV"
  name:  "Pavo25 V2 Brushless Whoop Frame"
  weight_g:  35.7
  wheelbase_mm:  93.9
  max_prop_size_mm:  50.8
  geometry:  "Whoop"
  description:  "BETAFPV Pavo25 V2 Brushless Whoop Frame Whoop drone frame with 93.9mm wheelbase, supporting up to 50.8mm props, weighing 35.7g."
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PRODUCT_PAGE
    url:  "https://betafpv.com/collections/frames"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_DOCUMENTATION
    url:  "https://support.betafpv.com"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://betafpv.com/collections/frames"
  }
}
frames:  {
  uuid:  "ba6fa85c-98cc-4396-ae29-2e2284bf2c53"
  id:  "pavo20-brushless-whoop-frame"
  manufacturer:  "BETAFPV"
  name:  "Pavo20 Brushless Whoop Frame"
  weight_g:  35.7
  wheelbase_mm:  93.9
  max_prop_size_mm:  50.8
  geometry:  "Whoop"
  description:  "BETAFPV Pavo20 Brushless Whoop Frame Whoop drone frame with 93.9mm wheelbase, supporting up to 50.8mm props, weighing 35.7g."
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PRODUCT_PAGE
    url:  "https://betafpv.com/collections/frames"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_DOCUMENTATION
    url:  "https://support.betafpv.com"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://betafpv.com/collections/frames"
  }
}
frames:  {
  uuid:  "52efdcae-96a8-4666-b46e-fc8197de5cad"
  id:  "pavo-pico-brushless-whoop-frame"
  manufacturer:  "BETAFPV"
  name:  "Pavo Pico Brushless Whoop Frame"
  weight_g:  19
  wheelbase_mm:  80
  max_prop_size_mm:  40
  geometry:  "Whoop"
  description:  "BETAFPV Pavo Pico Brushless Whoop Frame Whoop drone frame with 80.0mm wheelbase, supporting up to 40.0mm props, weighing 19.0g."
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PRODUCT_PAGE
    url:  "https://betafpv.com/collections/frames"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_DOCUMENTATION
    url:  "https://support.betafpv.com"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://betafpv.com/collections/frames"
  }
}
frames:  {
  uuid:  "1e2fc8e0-1ff7-4bc9-8338-eb3be9dbc16d"
  id:  "air65-brushless-whoop-frame"
  manufacturer:  "BETAFPV"
  name:  "Air65 Brushless Whoop Frame"
  weight_g:  2.2
  wheelbase_mm:  65
  max_prop_size_mm:  31
  geometry:  "Whoop"
  description:  "BETAFPV Air65 Brushless Whoop Frame Whoop drone frame with 65.0mm wheelbase, supporting up to 31.0mm props, weighing 2.2g."
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PRODUCT_PAGE
    url:  "https://betafpv.com/collections/frames"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_DOCUMENTATION
    url:  "https://support.betafpv.com"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://betafpv.com/collections/frames"
  }
}
frames:  {
  uuid:  "87131dff-79ff-49be-b529-22d576675743"
  id:  "meteor75-pro-brushless-whoop-frame"
  manufacturer:  "BETAFPV"
  name:  "Meteor75 Pro Brushless Whoop Frame"
  weight_g:  7.73
  wheelbase_mm:  80.8
  max_prop_size_mm:  40
  geometry:  "Whoop"
  description:  "BETAFPV Meteor75 Pro Brushless Whoop Frame Whoop drone frame with 80.8mm wheelbase, supporting up to 40.0mm props, weighing 7.7g."
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PRODUCT_PAGE
    url:  "https://betafpv.com/collections/frames"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_DOCUMENTATION
    url:  "https://support.betafpv.com"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://betafpv.com/collections/frames"
  }
}
frames:  {
  uuid:  "d13a0487-0f69-40f3-97ea-4a6400ec50a8"
  id:  "meteor85-brushless-whoop-frame"
  manufacturer:  "BETAFPV"
  name:  "Meteor85 Brushless Whoop Frame"
  weight_g:  4.6
  wheelbase_mm:  70
  max_prop_size_mm:  31
  geometry:  "Whoop"
  description:  "BETAFPV Meteor85 Brushless Whoop Frame Whoop drone frame with 70.0mm wheelbase, supporting up to 31.0mm props, weighing 4.6g."
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PRODUCT_PAGE
    url:  "https://betafpv.com/collections/frames"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_DOCUMENTATION
    url:  "https://support.betafpv.com"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://betafpv.com/collections/frames"
  }
}
frames:  {
  uuid:  "68f9ece3-bf8e-4eeb-b8b9-2599ea9a4937"
  id:  "cetus-x-brushless-whoop-frame"
  manufacturer:  "BETAFPV"
  name:  "Cetus X Brushless Whoop Frame"
  weight_g:  55
  wheelbase_mm:  95
  max_prop_size_mm:  50.8
  geometry:  "Whoop"
  description:  "BETAFPV Cetus X Brushless Whoop Frame Whoop drone frame with 95.0mm wheelbase, supporting up to 50.8mm props, weighing 55.0g."
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PRODUCT_PAGE
    url:  "https://betafpv.com/collections/frames"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_DOCUMENTATION
    url:  "https://support.betafpv.com"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://betafpv.com/collections/frames"
  }
}
frames:  {
  uuid:  "a2d038cd-36e0-4e41-bbb2-74341a81dab5"
  id:  "cetus-pro-brushless-whoop-frame"
  manufacturer:  "BETAFPV"
  name:  "Cetus Pro Brushless Whoop Frame"
  weight_g:  4.6
  wheelbase_mm:  70
  max_prop_size_mm:  31
  geometry:  "Whoop"
  description:  "BETAFPV Cetus Pro Brushless Whoop Frame Whoop drone frame with 70.0mm wheelbase, supporting up to 31.0mm props, weighing 4.6g."
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PRODUCT_PAGE
    url:  "https://betafpv.com/collections/frames"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_DOCUMENTATION
    url:  "https://support.betafpv.com"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://betafpv.com/collections/frames"
  }
}
frames:  {
  uuid:  "afa961c7-0906-4da4-82e2-ae879f22ca81"
  id:  "pavo360-frame-kit"
  manufacturer:  "BETAFPV"
  name:  "Pavo360 Frame Kit"
  weight_g:  35.7
  wheelbase_mm:  93.9
  max_prop_size_mm:  50.8
  geometry:  "Whoop"
  description:  "BETAFPV Pavo360 Frame Kit Whoop drone frame with 93.9mm wheelbase, supporting up to 50.8mm props, weighing 35.7g."
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PRODUCT_PAGE
    url:  "https://betafpv.com/collections/frames"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_DOCUMENTATION
    url:  "https://support.betafpv.com"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://betafpv.com/collections/frames"
  }
}
frames:  {
  uuid:  "aead85a2-635c-4d7e-b4a1-e38edc71c4bb"
  id:  "pavo30-pro-frame-kit"
  manufacturer:  "BETAFPV"
  name:  "Pavo30 Pro Frame Kit"
  weight_g:  35.7
  wheelbase_mm:  93.9
  max_prop_size_mm:  50.8
  geometry:  "Whoop"
  description:  "BETAFPV Pavo30 Pro Frame Kit Whoop drone frame with 93.9mm wheelbase, supporting up to 50.8mm props, weighing 35.7g."
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PRODUCT_PAGE
    url:  "https://betafpv.com/collections/frames"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_DOCUMENTATION
    url:  "https://support.betafpv.com"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://betafpv.com/collections/frames"
  }
}
frames:  {
  uuid:  "2998d238-4574-4a4c-9d33-0c0f77704b64"
  id:  "meteor65-pro-brushless-whoop-frame"
  manufacturer:  "BETAFPV"
  name:  "Meteor65 Pro Brushless Whoop Frame"
  weight_g:  3.2
  wheelbase_mm:  65
  max_prop_size_mm:  31
  geometry:  "Whoop"
  description:  "BETAFPV Meteor65 Pro Brushless Whoop Frame Whoop drone frame with 65.0mm wheelbase, supporting up to 31.0mm props, weighing 3.2g."
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PRODUCT_PAGE
    url:  "https://betafpv.com/collections/frames"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_DOCUMENTATION
    url:  "https://support.betafpv.com"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://betafpv.com/collections/frames"
  }
}
frames:  {
  uuid:  "a3d2f778-4fb3-4db5-8720-a322907d5ef4"
  id:  "x-knight-35-frame-kit"
  manufacturer:  "BETAFPV"
  name:  "X-Knight 35 Frame Kit"
  weight_g:  142.9
  wheelbase_mm:  155
  max_prop_size_mm:  101.6
  geometry:  "True X"
  description:  "BETAFPV X-Knight 35 Frame Kit True X drone frame with 155.0mm wheelbase, supporting up to 101.6mm props, weighing 142.9g."
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PRODUCT_PAGE
    url:  "https://betafpv.com/collections/frames"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_DOCUMENTATION
    url:  "https://support.betafpv.com"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://betafpv.com/collections/frames"
  }
}
frames:  {
  uuid:  "baa3310c-71c0-48f4-ac7a-1ff289be009e"
  id:  "pavo30-frame-kit"
  manufacturer:  "BETAFPV"
  name:  "Pavo30 Frame Kit"
  weight_g:  19
  wheelbase_mm:  80
  max_prop_size_mm:  40
  geometry:  "Whoop"
  description:  "BETAFPV Pavo30 Frame Kit Whoop drone frame with 80.0mm wheelbase, supporting up to 40.0mm props, weighing 19.0g."
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PRODUCT_PAGE
    url:  "https://betafpv.com/collections/frames"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_DOCUMENTATION
    url:  "https://support.betafpv.com"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://betafpv.com/collections/frames"
  }
}
frames:  {
  uuid:  "dcdeaaa3-585a-4ccf-bd50-31abcdfa5b58"
  id:  "beta95x-v3-frame-kit"
  manufacturer:  "BETAFPV"
  name:  "Beta95X V3 Frame Kit"
  weight_g:  19
  wheelbase_mm:  80
  max_prop_size_mm:  40
  geometry:  "True X"
  description:  "BETAFPV Beta95X V3 Frame Kit True X drone frame with 80.0mm wheelbase, supporting up to 40.0mm props, weighing 19.0g."
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PRODUCT_PAGE
    url:  "https://betafpv.com/collections/frames"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_DOCUMENTATION
    url:  "https://support.betafpv.com"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://betafpv.com/collections/frames"
  }
}
frames:  {
  uuid:  "1b9034cb-2b5e-417a-a2f4-6ce10b46a991"
  id:  "meteor75-micro-brushless-whoop-frame"
  manufacturer:  "BETAFPV"
  name:  "Meteor75 Micro Brushless Whoop Frame"
  weight_g:  7.73
  wheelbase_mm:  80.8
  max_prop_size_mm:  40
  geometry:  "Whoop"
  description:  "BETAFPV Meteor75 Micro Brushless Whoop Frame Whoop drone frame with 80.8mm wheelbase, supporting up to 40.0mm props, weighing 7.7g."
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PRODUCT_PAGE
    url:  "https://betafpv.com/collections/frames"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_DOCUMENTATION
    url:  "https://support.betafpv.com"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://betafpv.com/collections/frames"
  }
}
frames:  {
  uuid:  "6f1641f0-97f4-45a5-bab7-b5af78adac2a"
  id:  "beta75x-v2-micro-brushless-whoop-frame"
  manufacturer:  "BETAFPV"
  name:  "Beta75X V2 Micro Brushless Whoop Frame"
  weight_g:  4
  wheelbase_mm:  75
  max_prop_size_mm:  40
  geometry:  "Whoop"
  description:  "BETAFPV Beta75X V2 Micro Brushless Whoop Frame Whoop drone frame with 75.0mm wheelbase, supporting up to 40.0mm props, weighing 4.0g."
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PRODUCT_PAGE
    url:  "https://betafpv.com/collections/frames"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_DOCUMENTATION
    url:  "https://support.betafpv.com"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://betafpv.com/collections/frames"
  }
}
frames:  {
  uuid:  "1cf1b9d6-7086-451f-a1f1-feb20259a6a9"
  id:  "x-knight-carbon-fiber-5-frame-v2-kit"
  manufacturer:  "BETAFPV"
  name:  "X-Knight Carbon Fiber 5'' Frame V2 Kit"
  weight_g:  142.9
  wheelbase_mm:  200
  max_prop_size_mm:  129.54
  geometry:  "True X"
  description:  "BETAFPV X-Knight Carbon Fiber 5'' Frame V2 Kit True X drone frame with 200.0mm wheelbase, supporting up to 129.5mm props, weighing 142.9g."
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PRODUCT_PAGE
    url:  "https://betafpv.com/collections/frames"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_DOCUMENTATION
    url:  "https://support.betafpv.com"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://betafpv.com/collections/frames"
  }
}
frames:  {
  uuid:  "9ac32330-6d03-40e1-9608-a1cd16caabee"
  id:  "twiglet-2-5-frame-kit"
  manufacturer:  "BETAFPV"
  name:  "TWIGLET 2.5'' Frame Kit"
  weight_g:  19
  wheelbase_mm:  80
  max_prop_size_mm:  40
  geometry:  "True X"
  description:  "BETAFPV TWIGLET 2.5'' Frame Kit True X drone frame with 80.0mm wheelbase, supporting up to 40.0mm props, weighing 19.0g."
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PRODUCT_PAGE
    url:  "https://betafpv.com/collections/frames"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_DOCUMENTATION
    url:  "https://support.betafpv.com"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://betafpv.com/collections/frames"
  }
}
frames:  {
  uuid:  "0681bd40-b3c6-46c3-9dca-6b17595bf7a8"
  id:  "twig-xl-3-frame-kit"
  manufacturer:  "BETAFPV"
  name:  "TWIG XL 3 Frame Kit"
  weight_g:  138
  wheelbase_mm:  153
  max_prop_size_mm:  88.9
  geometry:  "True X"
  description:  "BETAFPV TWIG XL 3 Frame Kit True X drone frame with 153.0mm wheelbase, supporting up to 88.9mm props, weighing 138.0g."
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PRODUCT_PAGE
    url:  "https://betafpv.com/collections/frames"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_DOCUMENTATION
    url:  "https://support.betafpv.com"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://betafpv.com/collections/frames"
  }
}
frames:  {
  uuid:  "02f18100-0738-45fa-a5c9-78b62a90134a"
  id:  "beta95x-frame-kit"
  manufacturer:  "BETAFPV"
  name:  "Beta95X Frame Kit"
  weight_g:  19
  wheelbase_mm:  80
  max_prop_size_mm:  40
  geometry:  "True X"
  description:  "BETAFPV Beta95X Frame Kit True X drone frame with 80.0mm wheelbase, supporting up to 40.0mm props, weighing 19.0g."
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PRODUCT_PAGE
    url:  "https://betafpv.com/collections/frames"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_DOCUMENTATION
    url:  "https://support.betafpv.com"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://betafpv.com/collections/frames"
  }
}
frames:  {
  uuid:  "bfe08cf8-baec-4eb3-b592-2648358fde5f"
  id:  "beta75-pro-micro-brushless-whoop-frame"
  manufacturer:  "BETAFPV"
  name:  "Beta75 Pro Micro Brushless Whoop Frame"
  weight_g:  7.73
  wheelbase_mm:  80.8
  max_prop_size_mm:  40
  geometry:  "Whoop"
  description:  "BETAFPV Beta75 Pro Micro Brushless Whoop Frame Whoop drone frame with 80.8mm wheelbase, supporting up to 40.0mm props, weighing 7.7g."
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PRODUCT_PAGE
    url:  "https://betafpv.com/collections/frames"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_DOCUMENTATION
    url:  "https://support.betafpv.com"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://betafpv.com/collections/frames"
  }
}
frames:  {
  uuid:  "08b2bee0-776a-474b-9395-4905c912bd04"
  id:  "meteor65-micro-brushless-whoop-frame"
  manufacturer:  "BETAFPV"
  name:  "Meteor65 Micro Brushless Whoop Frame"
  weight_g:  4.6
  wheelbase_mm:  70
  max_prop_size_mm:  31
  geometry:  "Whoop"
  description:  "BETAFPV Meteor65 Micro Brushless Whoop Frame Whoop drone frame with 70.0mm wheelbase, supporting up to 31.0mm props, weighing 4.6g."
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PRODUCT_PAGE
    url:  "https://betafpv.com/collections/frames"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_DOCUMENTATION
    url:  "https://support.betafpv.com"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://betafpv.com/collections/frames"
  }
}
frames:  {
  uuid:  "b4e9b5e0-5dab-4445-a5f5-15727633844d"
  id:  "hx115-t700-carbon-fiber-frame"
  manufacturer:  "BETAFPV"
  name:  "HX115 T700 Carbon Fiber Frame"
  weight_g:  113.9
  wheelbase_mm:  148
  max_prop_size_mm:  88.9
  geometry:  "True X"
  description:  "BETAFPV HX115 T700 Carbon Fiber Frame True X drone frame with 148.0mm wheelbase, supporting up to 88.9mm props, weighing 113.9g."
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PRODUCT_PAGE
    url:  "https://betafpv.com/collections/frames"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_DOCUMENTATION
    url:  "https://support.betafpv.com"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://betafpv.com/collections/frames"
  }
}
frames:  {
  uuid:  "3352901c-ed21-4f34-832c-f28ff76d4f82"
  id:  "hx100-carbon-fiber-frame"
  manufacturer:  "BETAFPV"
  name:  "HX100 Carbon Fiber Frame"
  weight_g:  200
  wheelbase_mm:  367
  max_prop_size_mm:  177.8
  geometry:  "True X"
  description:  "BETAFPV HX100 Carbon Fiber Frame True X drone frame with 367.0mm wheelbase, supporting up to 177.8mm props, weighing 200.0g."
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PRODUCT_PAGE
    url:  "https://betafpv.com/collections/frames"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_DOCUMENTATION
    url:  "https://support.betafpv.com"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://betafpv.com/collections/frames"
  }
}
frames:  {
  uuid:  "e68f8302-e73f-47ad-8dee-61c6702f90de"
  id:  "stiffener-brace-of-carbon-fiber"
  manufacturer:  "BETAFPV"
  name:  "Stiffener Brace of Carbon Fiber"
  weight_g:  20
  wheelbase_mm:  85
  max_prop_size_mm:  50.8
  geometry:  "True X"
  description:  "Stiffener Brace of Carbon Fiber for Beta85X Frame (2 PCS)"
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PRODUCT_PAGE
    url:  "https://betafpv.com/collections/frames"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_DOCUMENTATION
    url:  "https://support.betafpv.com"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://betafpv.com/collections/frames"
  }
}
frames:  {
  uuid:  "77b37507-376d-4e43-967d-1441dcea5d45"
  id:  "beta85x-4s-4k-frame-kit-upgrade"
  manufacturer:  "BETAFPV"
  name:  "Beta85X 4S 4K Frame Kit (Upgrade)"
  weight_g:  10.3
  wheelbase_mm:  85
  max_prop_size_mm:  50.8
  geometry:  "True X"
  description:  "BETAFPV Beta85X 4S 4K Frame Kit (Upgrade) True X drone frame with 85.0mm wheelbase, supporting up to 50.8mm props, weighing 10.3g."
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PRODUCT_PAGE
    url:  "https://betafpv.com/collections/frames"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_DOCUMENTATION
    url:  "https://support.betafpv.com"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://betafpv.com/collections/frames"
  }
}
frames:  {
  uuid:  "8688e221-32da-47e8-9bb9-5c20c7fdc232"
  id:  "beta75-pro-2-whoop-frame"
  manufacturer:  "BETAFPV"
  name:  "Beta75 Pro 2 Whoop Frame"
  weight_g:  35.7
  wheelbase_mm:  93.9
  max_prop_size_mm:  50.8
  geometry:  "Whoop"
  description:  "BETAFPV Beta75 Pro 2 Whoop Frame Whoop drone frame with 93.9mm wheelbase, supporting up to 50.8mm props, weighing 35.7g."
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PRODUCT_PAGE
    url:  "https://betafpv.com/collections/frames"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_DOCUMENTATION
    url:  "https://support.betafpv.com"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://betafpv.com/collections/frames"
  }
}
frames:  {
  uuid:  "989196e6-e646-4a0e-8197-54bf1babcdd5"
  id:  "beta65x-beta65-pro-2-micro-whoop-frame"
  manufacturer:  "BETAFPV"
  name:  "Beta65X / Beta65 Pro 2 Micro Whoop Frame"
  weight_g:  35.7
  wheelbase_mm:  93.9
  max_prop_size_mm:  50.8
  geometry:  "Whoop"
  description:  "BETAFPV Beta65X / Beta65 Pro 2 Micro Whoop Frame Whoop drone frame with 93.9mm wheelbase, supporting up to 50.8mm props, weighing 35.7g."
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PRODUCT_PAGE
    url:  "https://betafpv.com/collections/frames"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_DOCUMENTATION
    url:  "https://support.betafpv.com"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://betafpv.com/collections/frames"
  }
}
frames:  {
  uuid:  "61c2d2b1-8874-48cb-ae57-3fa93a2b2a1d"
  id:  "beta75x-whoop-frame"
  manufacturer:  "BETAFPV"
  name:  "Beta75X Whoop Frame"
  weight_g:  4
  wheelbase_mm:  75
  max_prop_size_mm:  40
  geometry:  "Whoop"
  description:  "BETAFPV Beta75X Whoop Frame Whoop drone frame with 75.0mm wheelbase, supporting up to 40.0mm props, weighing 4.0g."
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PRODUCT_PAGE
    url:  "https://betafpv.com/collections/frames"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_DOCUMENTATION
    url:  "https://support.betafpv.com"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://betafpv.com/collections/frames"
  }
}
frames:  {
  uuid:  "276e22ec-3dd0-492a-b5b2-0f871f2d0a17"
  id:  "beta65-pro-micro-brushless-whoop-frame"
  manufacturer:  "BETAFPV"
  name:  "Beta65 Pro Micro Brushless Whoop Frame"
  weight_g:  4.6
  wheelbase_mm:  70
  max_prop_size_mm:  31
  geometry:  "Whoop"
  description:  "BETAFPV Beta65 Pro Micro Brushless Whoop Frame Whoop drone frame with 70.0mm wheelbase, supporting up to 31.0mm props, weighing 4.6g."
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PRODUCT_PAGE
    url:  "https://betafpv.com/collections/frames"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_DOCUMENTATION
    url:  "https://support.betafpv.com"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://betafpv.com/collections/frames"
  }
}
frames:  {
  uuid:  "ecd3d399-bc3d-4f31-bc3b-094ee1b368b7"
  id:  "protos-drone-frame"
  manufacturer:  "CADDX FPV"
  name:  "Protos Drone Frame"
  weight_g:  104.4
  wheelbase_mm:  220
  max_prop_size_mm:  129.54
  geometry:  "True X"
  description:  "CADDX FPV Protos Drone Frame True X drone frame with 220.0mm wheelbase, supporting up to 129.5mm props, weighing 104.4g."
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://www.getfpv.com/fpv/frames.html"
  }
}
frames:  {
  uuid:  "b3a04e3d-b47e-48d2-9af7-71d6835067db"
  id:  "caddxfpv-gofilm-20-frame"
  manufacturer:  "CADDXFPV"
  name:  "CADDXFPV Gofilm 20 Frame"
  weight_g:  38.5
  wheelbase_mm:  94
  max_prop_size_mm:  50.8
  geometry:  "True X"
  description:  "CADDXFPV CADDXFPV Gofilm 20 Frame True X drone frame with 94.0mm wheelbase, supporting up to 50.8mm props, weighing 38.5g."
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://www.getfpv.com/fpv/frames.html"
  }
}
frames:  {
  uuid:  "b3bdea49-e3b0-439e-b8f5-b979d169514f"
  id:  "baby-babyape-v4-frame"
  manufacturer:  "DarwinFPV"
  name:  "Baby BabyApe V4 Frame"
  weight_g:  125
  wheelbase_mm:  220
  max_prop_size_mm:  129.54
  geometry:  "True X"
  description:  "DarwinFPV Baby BabyApe V4 Frame True X drone frame with 220.0mm wheelbase, supporting up to 129.5mm props, weighing 125.0g."
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PRODUCT_PAGE
    url:  "https://darwinfpv.com/collections/frame"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://darwinfpv.com/collections/frame"
  }
}
frames:  {
  uuid:  "e4561bb2-ee70-4ff4-91c7-e9bbb02fa512"
  id:  "darwinfpv-apestyle-x5-drone-frame"
  manufacturer:  "DarwinFPV"
  name:  "DarwinFPV ApeStyle X5 Drone Frame"
  weight_g:  177.4
  wheelbase_mm:  225
  max_prop_size_mm:  129.54
  geometry:  "Deadcat"
  description:  "DarwinFPV DarwinFPV ApeStyle X5 Drone Frame Deadcat drone frame with 225.0mm wheelbase, supporting up to 129.5mm props, weighing 177.4g."
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PRODUCT_PAGE
    url:  "https://darwinfpv.com/collections/frame"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://darwinfpv.com/collections/frame"
  }
}
frames:  {
  uuid:  "d363ccbd-887a-4ef2-8025-ca0b0ee86571"
  id:  "darwinfpv-toruk15-long-range-fpv-drone"
  manufacturer:  "DarwinFPV"
  name:  "DarwinFPV Toruk15 Long Range FPV Drone"
  weight_g:  250
  wheelbase_mm:  220
  max_prop_size_mm:  129.54
  geometry:  "Deadcat"
  description:  "DarwinFPV Toruk15  Long Range FPV Drone Frame"
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PRODUCT_PAGE
    url:  "https://darwinfpv.com/collections/frame"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://darwinfpv.com/collections/frame"
  }
}
frames:  {
  uuid:  "960ee197-cf5a-4659-ad32-c6b178195e62"
  id:  "babyape-pro-3-5-inch-freestyle"
  manufacturer:  "DarwinFPV"
  name:  "BabyApe Ⅲ Pro 3.5 Inch Freestyle"
  weight_g:  250
  wheelbase_mm:  156
  max_prop_size_mm:  88
  geometry:  "Wide-X"
  description:  "BabyApe Ⅲ Pro 3.5 Inch Freestyle FPV Drone Frame"
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PRODUCT_PAGE
    url:  "https://darwinfpv.com/collections/frame"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://darwinfpv.com/collections/frame"
  }
}
frames:  {
  uuid:  "fef91f43-ad50-4acf-8e6c-1629f31b62a9"
  id:  "babyape-3-inch-freestyle-fpv"
  manufacturer:  "DarwinFPV"
  name:  "BabyApe Ⅲ 3 Inch Freestyle FPV"
  weight_g:  250
  wheelbase_mm:  156
  max_prop_size_mm:  76
  geometry:  "Wide-X"
  description:  "BabyApe Ⅲ 3 Inch Freestyle FPV Drone Frame"
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PRODUCT_PAGE
    url:  "https://darwinfpv.com/collections/frame"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://darwinfpv.com/collections/frame"
  }
}
frames:  {
  uuid:  "4f43a983-553f-4c1b-89e5-705628932743"
  id:  "babyape-mini-2-inch-freestyle-frame"
  manufacturer:  "DarwinFPV"
  name:  "BabyApe Ⅲ Mini 2 Inch Freestyle Frame"
  weight_g:  70.5
  wheelbase_mm:  160
  max_prop_size_mm:  50
  geometry:  "Squashed-X"
  description:  "DarwinFPV BabyApe Ⅲ Mini 2 Inch Freestyle Frame Squashed-X drone frame with 160.0mm wheelbase, supporting up to 50.0mm props, weighing 70.5g."
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PRODUCT_PAGE
    url:  "https://darwinfpv.com/collections/frame"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://darwinfpv.com/collections/frame"
  }
}
frames:  {
  uuid:  "4409042c-9fb0-4fc7-b2ba-0b9bdfafa674"
  id:  "darwinfpv-hulk-iii-mini-frame"
  manufacturer:  "DarwinFPV"
  name:  "DarwinFPV HULK III Mini Frame"
  weight_g:  125
  wheelbase_mm:  220
  max_prop_size_mm:  129.54
  geometry:  "True X"
  description:  "DarwinFPV DarwinFPV HULK III Mini Frame True X drone frame with 220.0mm wheelbase, supporting up to 129.5mm props, weighing 125.0g."
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PRODUCT_PAGE
    url:  "https://darwinfpv.com/collections/frame"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://darwinfpv.com/collections/frame"
  }
}
frames:  {
  uuid:  "803f997e-b14d-49e3-9c8c-1b1bff479514"
  id:  "darwinfpv-x10-long-range-fpv-drone-frame"
  manufacturer:  "DarwinFPV"
  name:  "DarwinFPV X10 Long Range FPV Drone Frame"
  weight_g:  186.4
  wheelbase_mm:  225
  max_prop_size_mm:  129.54
  geometry:  "Deadcat"
  description:  "DarwinFPV DarwinFPV X10 Long Range FPV Drone Frame Deadcat drone frame with 225.0mm wheelbase, supporting up to 129.5mm props, weighing 186.4g."
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PRODUCT_PAGE
    url:  "https://darwinfpv.com/collections/frame"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://darwinfpv.com/collections/frame"
  }
}
frames:  {
  uuid:  "1f5b7c61-58b5-431d-98b8-a6b4e09bb6aa"
  id:  "darwinfpv-foldape4-analog-frame"
  manufacturer:  "DarwinFPV"
  name:  "DarwinFPV FoldApe4 Analog Frame"
  weight_g:  125
  wheelbase_mm:  220
  max_prop_size_mm:  129.54
  geometry:  "True X"
  description:  "DarwinFPV DarwinFPV FoldApe4 Analog Frame True X drone frame with 220.0mm wheelbase, supporting up to 129.5mm props, weighing 125.0g."
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PRODUCT_PAGE
    url:  "https://darwinfpv.com/collections/frame"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://darwinfpv.com/collections/frame"
  }
}
frames:  {
  uuid:  "f926d440-2090-4f93-96f3-4662663667f3"
  id:  "darwin-x9-quadcopter-frame"
  manufacturer:  "DarwinFPV"
  name:  "DARWIN X9 Quadcopter Frame"
  weight_g:  287.8
  wheelbase_mm:  363
  max_prop_size_mm:  177.8
  geometry:  "True-X"
  description:  "DarwinFPV DARWIN X9 Quadcopter Frame True-X drone frame with 363.0mm wheelbase, supporting up to 177.8mm props, weighing 287.8g."
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PRODUCT_PAGE
    url:  "https://darwinfpv.com/collections/frame"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://darwinfpv.com/collections/frame"
  }
}
frames:  {
  uuid:  "681cafac-3af5-4418-a8a6-888d1a87d448"
  id:  "darwin-hulk-waterproof-fpv-drone"
  manufacturer:  "DarwinFPV"
  name:  "DARWIN HULK Ⅱ Waterproof FPV Drone"
  weight_g:  105.3
  wheelbase_mm:  227
  max_prop_size_mm:  129.54
  geometry:  "True X"
  description:  "DARWIN HULK Ⅱ Waterproof  FPV Drone Frame"
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PRODUCT_PAGE
    url:  "https://darwinfpv.com/collections/frame"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://darwinfpv.com/collections/frame"
  }
}
frames:  {
  uuid:  "6b74a4b7-7faf-4579-bce8-c99639fb784a"
  id:  "darwinfpv-babyape-3-5-inch-fpv"
  manufacturer:  "DarwinFPV"
  name:  "DarwinFPV BabyApe Ⅱ 3.5 inch FPV"
  weight_g:  250
  wheelbase_mm:  156
  max_prop_size_mm:  88
  geometry:  "Wide-X"
  description:  "DarwinFPV BabyApe Ⅱ 3.5 inch FPV Drone Frame"
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PRODUCT_PAGE
    url:  "https://darwinfpv.com/collections/frame"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://darwinfpv.com/collections/frame"
  }
}
frames:  {
  uuid:  "ebd5e092-cb6e-49ef-8802-ce21a2aa7496"
  id:  "darwin-cineape-25-whoop-frame"
  manufacturer:  "DarwinFPV"
  name:  "Darwin CineApe 25 Whoop Frame"
  weight_g:  47.8
  wheelbase_mm:  112
  max_prop_size_mm:  76.2
  geometry:  "Whoop"
  description:  "DarwinFPV Darwin CineApe 25 Whoop Frame Whoop drone frame with 112.0mm wheelbase, supporting up to 76.2mm props, weighing 47.8g."
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PRODUCT_PAGE
    url:  "https://darwinfpv.com/collections/frame"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://darwinfpv.com/collections/frame"
  }
}
frames:  {
  uuid:  "0326536d-0119-4609-85c7-73a7505b593c"
  id:  "baby-babyape-v2-frame"
  manufacturer:  "DarwinFPV"
  name:  "Baby BabyApe V2 Frame"
  weight_g:  125
  wheelbase_mm:  220
  max_prop_size_mm:  129.54
  geometry:  "True X"
  description:  "DarwinFPV Baby BabyApe V2 Frame True X drone frame with 220.0mm wheelbase, supporting up to 129.5mm props, weighing 125.0g."
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PRODUCT_PAGE
    url:  "https://darwinfpv.com/collections/frame"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://darwinfpv.com/collections/frame"
  }
}
frames:  {
  uuid:  "a2f84c6e-c5a9-40cf-a597-f4deae9023c6"
  id:  "darwinfpv-hulk-waterproof-frame"
  manufacturer:  "DarwinFPV"
  name:  "DarwinFPV HULK Waterproof Frame"
  weight_g:  125
  wheelbase_mm:  220
  max_prop_size_mm:  129.54
  geometry:  "True X"
  description:  "DarwinFPV DarwinFPV HULK Waterproof Frame True X drone frame with 220.0mm wheelbase, supporting up to 129.5mm props, weighing 125.0g."
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PRODUCT_PAGE
    url:  "https://darwinfpv.com/collections/frame"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://darwinfpv.com/collections/frame"
  }
}
frames:  {
  uuid:  "dc11d671-201b-4a8c-ae14-285905076000"
  id:  "darwin-tinyape-freestyle-frame"
  manufacturer:  "DarwinFPV"
  name:  "Darwin TinyApe Freestyle Frame"
  weight_g:  70.5
  wheelbase_mm:  160
  max_prop_size_mm:  101.6
  geometry:  "Squashed-X"
  description:  "DarwinFPV Darwin TinyApe Freestyle Frame Squashed-X drone frame with 160.0mm wheelbase, supporting up to 101.6mm props, weighing 70.5g."
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PRODUCT_PAGE
    url:  "https://darwinfpv.com/collections/frame"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://darwinfpv.com/collections/frame"
  }
}
frames:  {
  uuid:  "1982a5f0-80de-491e-ae4a-840a56c1ee06"
  id:  "darwin-baby-ape-3-quadcopter-frame"
  manufacturer:  "DarwinFPV"
  name:  "Darwin Baby Ape 3'' Quadcopter Frame"
  weight_g:  74.1
  wheelbase_mm:  143
  max_prop_size_mm:  88.9
  geometry:  "True-X"
  description:  "DarwinFPV Darwin Baby Ape 3'' Quadcopter Frame True-X drone frame with 143.0mm wheelbase, supporting up to 88.9mm props, weighing 74.1g."
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PRODUCT_PAGE
    url:  "https://darwinfpv.com/collections/frame"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://darwinfpv.com/collections/frame"
  }
}
frames:  {
  uuid:  "f4e44a92-6907-4177-af99-763e7ddf9a57"
  id:  "newbeedrone-cockroach-65mm-brushed-liteaf-racing"
  manufacturer:  "NewBeeDrone"
  name:  "NewBeeDrone Cockroach 65mm Brushed LiteAF Racing"
  weight_g:  3.3
  wheelbase_mm:  75
  max_prop_size_mm:  40
  geometry:  "True X"
  description:  "NewBeeDrone Cockroach 65mm Brushed LiteAF Racing Frame"
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://www.getfpv.com/fpv/frames.html"
  }
}
frames:  {
  uuid:  "8df9bbb1-0f79-4531-a3a5-d0d3d931ae16"
  id:  "newbeedrone-cockroach-75mm-brushless-liteaf-racing"
  manufacturer:  "NewBeeDrone"
  name:  "NewBeeDrone Cockroach 75mm Brushless LiteAF Racing"
  weight_g:  3.3
  wheelbase_mm:  75
  max_prop_size_mm:  40
  geometry:  "True X"
  description:  "NewBeeDrone Cockroach 75mm Brushless LiteAF Racing Frame"
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://www.getfpv.com/fpv/frames.html"
  }
}
frames:  {
  uuid:  "32ce4984-f380-4bd4-9b23-90d0317b7b92"
  id:  "newbeedrone-lionbee-3inch-frame"
  manufacturer:  "NewBeeDrone"
  name:  "NewBeeDrone LionBee 3inch Frame"
  weight_g:  3.3
  wheelbase_mm:  75
  max_prop_size_mm:  76
  geometry:  "True X"
  description:  "NewBeeDrone NewBeeDrone LionBee 3inch Frame True X drone frame with 75.0mm wheelbase, supporting up to 76.0mm props, weighing 3.3g."
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://www.getfpv.com/fpv/frames.html"
  }
}
frames:  {
  uuid:  "18e04626-53ad-4d9e-b695-e2db5141ba07"
  id:  "newbeedrone-x-webleedfpv-cockroach-65mm-liteaf"
  manufacturer:  "NewBeeDrone"
  name:  "NewBeeDrone X weBLEEDfpv Cockroach 65mm LiteAF"
  weight_g:  2.8
  wheelbase_mm:  65
  max_prop_size_mm:  31
  geometry:  "True X"
  description:  "NewBeeDrone X weBLEEDfpv Cockroach 65mm LiteAF RED Frame"
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://www.getfpv.com/fpv/frames.html"
  }
}
frames:  {
  uuid:  "6c7a6c48-5a8d-43ed-b34f-9029766b285b"
  id:  "newbeedrone-stingerbee-hd-o4-pro-3"
  manufacturer:  "NewBeeDrone"
  name:  "NewBeeDrone StingerBee HD O4 Pro 3”"
  weight_g:  184
  wheelbase_mm:  220
  max_prop_size_mm:  129.54
  geometry:  "True X"
  description:  "NewBeeDrone StingerBee HD O4 Pro 3” Frame Kit"
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://www.getfpv.com/fpv/frames.html"
  }
}
frames:  {
  uuid:  "4f66ce21-de6a-4a53-a059-a357aa5c123a"
  id:  "newbeedrone-savagebee-pusher-frame-kit"
  manufacturer:  "NewBeeDrone"
  name:  "NewBeeDrone SavageBee Pusher Frame Kit"
  weight_g:  3.3
  wheelbase_mm:  75
  max_prop_size_mm:  40
  geometry:  "True X"
  description:  "NewBeeDrone NewBeeDrone SavageBee Pusher Frame Kit True X drone frame with 75.0mm wheelbase, supporting up to 40.0mm props, weighing 3.3g."
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://www.getfpv.com/fpv/frames.html"
  }
}
frames:  {
  uuid:  "62d60f2f-96f8-4c06-9344-e9dc19f139de"
  id:  "newbeedrone-cockroach-65mm-brushless-liteaf-racing"
  manufacturer:  "NewBeeDrone"
  name:  "NewBeeDrone Cockroach 65mm Brushless LiteAF Racing"
  weight_g:  3.3
  wheelbase_mm:  75
  max_prop_size_mm:  40
  geometry:  "True X"
  description:  "NewBeeDrone Cockroach 65mm Brushless LiteAF Racing Frame"
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://www.getfpv.com/fpv/frames.html"
  }
}
frames:  {
  uuid:  "e394e0bd-dc1c-4ecc-8553-c8aa21bad934"
  id:  "newbeedrone-cockroach-65mm-frame-3d-printed"
  manufacturer:  "NewBeeDrone"
  name:  "NewBeeDrone Cockroach 65mm Frame 3D Printed"
  weight_g:  2.8
  wheelbase_mm:  65
  max_prop_size_mm:  31
  geometry:  "True X"
  description:  "NewBeeDrone Cockroach 65mm Frame 3D Printed Battery Mount"
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://www.getfpv.com/fpv/frames.html"
  }
}
frames:  {
  uuid:  "5f7b117b-cb5e-41fd-b7f0-ac1f2a315213"
  id:  "newbeedrone-cockroach-82-brushless-super-durable-frame"
  manufacturer:  "NewBeeDrone"
  name:  "NewBeeDrone Cockroach 82 Brushless Super-Durable Frame"
  weight_g:  3.3
  wheelbase_mm:  75
  max_prop_size_mm:  40
  geometry:  "True X"
  description:  "NewBeeDrone Cockroach 82 Brushless Super-Durable Frame (Plastic Part and Carbon Fiber & Accessory)"
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://www.getfpv.com/fpv/frames.html"
  }
}
frames:  {
  uuid:  "b717ba35-c2ce-45ae-9081-23ed82f1bec3"
  id:  "newbeedrone-cockroach-82-brushless-super-durable-frame-2"
  manufacturer:  "NewBeeDrone"
  name:  "NewBeeDrone Cockroach 82 Brushless Super-Durable Frame"
  weight_g:  3.3
  wheelbase_mm:  75
  max_prop_size_mm:  40
  geometry:  "True X"
  description:  "NewBeeDrone Cockroach 82 Brushless Super-Durable Frame 82mm Plastic Part Only"
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://www.getfpv.com/fpv/frames.html"
  }
}
frames:  {
  uuid:  "d190b2a8-e79a-471f-a479-4fc360ad4b00"
  id:  "newbeedrone-75mm-cockroach75-brushless-extreme-durable-frame"
  manufacturer:  "NewBeeDrone"
  name:  "NewBeeDrone 75mm Cockroach75 Brushless Extreme-Durable Frame"
  weight_g:  3.3
  wheelbase_mm:  75
  max_prop_size_mm:  40
  geometry:  "True X"
  description:  "NewBeeDrone NewBeeDrone 75mm Cockroach75 Brushless Extreme-Durable Frame True X drone frame with 75.0mm wheelbase, supporting up to 40.0mm props, weighing 3.3g."
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://www.getfpv.com/fpv/frames.html"
  }
}
frames:  {
  uuid:  "b55829cc-b0b3-4fa0-a4cf-367fd8ad9360"
  id:  "newbeedrone-cockroach-v3-65mm-brushless-ultra"
  manufacturer:  "NewBeeDrone"
  name:  "NewBeeDrone Cockroach V3 65mm Brushless Ultra"
  weight_g:  2.8
  wheelbase_mm:  65
  max_prop_size_mm:  31
  geometry:  "True X"
  description:  "NewBeeDrone Cockroach V3 65mm Brushless Ultra Light Frame"
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://www.getfpv.com/fpv/frames.html"
  }
}
frames:  {
  uuid:  "1958ca5a-439e-4d90-8360-97228c1f5849"
  id:  "newbeedrone-inertia-5-dc-fpv-frame"
  manufacturer:  "NewBeeDrone"
  name:  "NewBeeDrone Inertia 5 DC  FPV Frame"
  weight_g:  197
  wheelbase_mm:  230
  max_prop_size_mm:  129.54
  geometry:  "Wide-X"
  description:  "NewBeeDrone Inertia 5 DC (Dead Cat Style) FPV Frame"
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://www.getfpv.com/fpv/frames.html"
  }
}
frames:  {
  uuid:  "86b9dc1a-5835-4a7f-b5c6-7be981903df9"
  id:  "newbeedrone-mosquito-xl-frame"
  manufacturer:  "NewBeeDrone"
  name:  "NewBeeDrone Mosquito XL Frame"
  weight_g:  3.3
  wheelbase_mm:  75
  max_prop_size_mm:  40
  geometry:  "True X"
  description:  "NewBeeDrone NewBeeDrone Mosquito XL Frame True X drone frame with 75.0mm wheelbase, supporting up to 40.0mm props, weighing 3.3g."
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://www.getfpv.com/fpv/frames.html"
  }
}
frames:  {
  uuid:  "4744b26e-992c-42ec-b022-bfb53ce811d9"
  id:  "newbeedrone-v2-65mm-cockroach-brushless-super-durable"
  manufacturer:  "NewBeeDrone"
  name:  "NewBeeDrone V2 65mm Cockroach Brushless Super-Durable"
  weight_g:  2.8
  wheelbase_mm:  65
  max_prop_size_mm:  31
  geometry:  "True X"
  description:  "NewBeeDrone V2 65mm Cockroach Brushless Super-Durable Frame"
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://www.getfpv.com/fpv/frames.html"
  }
}
frames:  {
  uuid:  "0c480cb5-8f02-4a08-956f-4d5db6f261ba"
  id:  "newbeedrone-mosquito-frame"
  manufacturer:  "NewBeeDrone"
  name:  "NewBeeDrone Mosquito Frame"
  weight_g:  3.3
  wheelbase_mm:  75
  max_prop_size_mm:  40
  geometry:  "True X"
  description:  "NewBeeDrone NewBeeDrone Mosquito Frame True X drone frame with 75.0mm wheelbase, supporting up to 40.0mm props, weighing 3.3g."
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://www.getfpv.com/fpv/frames.html"
  }
}
frames:  {
  uuid:  "f546eaa7-8954-451d-a984-5d13d2482b06"
  id:  "newbeedrone-65mm-cockroach-brushless-super-durable-frame"
  manufacturer:  "NewBeeDrone"
  name:  "NewBeeDrone 65mm Cockroach Brushless Super-Durable Frame"
  weight_g:  2.8
  wheelbase_mm:  65
  max_prop_size_mm:  31
  geometry:  "True X"
  description:  "NewBeeDrone NewBeeDrone 65mm Cockroach Brushless Super-Durable Frame True X drone frame with 65.0mm wheelbase, supporting up to 31.0mm props, weighing 2.8g."
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://www.getfpv.com/fpv/frames.html"
  }
}
frames:  {
  uuid:  "02a5f77e-d8f1-4b36-9fa0-8b252d665d51"
  id:  "newbeedrone-cockroach-brushed-super-durable-frame-65mm"
  manufacturer:  "NewBeeDrone"
  name:  "NewBeeDrone Cockroach Brushed Super-Durable Frame 65mm"
  weight_g:  2.8
  wheelbase_mm:  65
  max_prop_size_mm:  31
  geometry:  "True X"
  description:  "NewBeeDrone NewBeeDrone Cockroach Brushed Super-Durable Frame 65mm True X drone frame with 65.0mm wheelbase, supporting up to 31.0mm props, weighing 2.8g."
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://www.getfpv.com/fpv/frames.html"
  }
}
frames:  {
  uuid:  "db8d9317-d436-40d3-bc21-512ad3952ed1"
  id:  "lil-matey2-3-5-frame"
  manufacturer:  "Pirat"
  name:  "Lil Matey2 3.5 Frame"
  weight_g:  58
  wheelbase_mm:  220
  max_prop_size_mm:  129.54
  geometry:  "True-X"
  description:  "Pirat Lil Matey2 3.5 Frame True-X drone frame with 220.0mm wheelbase, supporting up to 129.5mm props, weighing 58.0g."
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://www.getfpv.com/fpv/frames.html"
  }
}
frames:  {
  uuid:  "2e38e004-b0c8-420b-bcee-6647fae1be4c"
  id:  "echo-5-frame"
  manufacturer:  "ImpulseRC"
  name:  "Echo 5 Frame"
  weight_g:  121
  wheelbase_mm:  220
  max_prop_size_mm:  129.54
  geometry:  "True X"
  description:  "ImpulseRC Echo 5 Frame True X drone frame with 220.0mm wheelbase, supporting up to 129.5mm props, weighing 121.0g."
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://www.getfpv.com/fpv/frames.html"
  }
}
frames:  {
  uuid:  "484ec143-cc53-419c-95ed-989d50b6ccec"
  id:  "tanq-s-3-5-frame-by-letsflyrc"
  manufacturer:  "Rotor Riot"
  name:  "TANQ S 3.5 Frame - By LetsFlyRC"
  weight_g:  70.5
  wheelbase_mm:  160
  max_prop_size_mm:  101.6
  geometry:  "Squashed-X"
  description:  "Rotor Riot TANQ S 3.5 Frame - By LetsFlyRC Squashed-X drone frame with 160.0mm wheelbase, supporting up to 101.6mm props, weighing 70.5g."
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://www.getfpv.com/fpv/frames.html"
  }
}
frames:  {
  uuid:  "1bcf7db6-6808-4b57-922a-040717dad78e"
  id:  "tanq-2-5-racing-frame-by-letsflyrc"
  manufacturer:  "Rotor Riot"
  name:  "TANQ 2 5 Racing Frame - By LetsFlyRC"
  weight_g:  177.4
  wheelbase_mm:  225
  max_prop_size_mm:  129.54
  geometry:  "Deadcat"
  description:  "Rotor Riot TANQ 2 5 Racing Frame - By LetsFlyRC Deadcat drone frame with 225.0mm wheelbase, supporting up to 129.5mm props, weighing 177.4g."
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://www.getfpv.com/fpv/frames.html"
  }
}
frames:  {
  uuid:  "d6d004d6-f9bb-453f-8829-2c01aabe2acf"
  id:  "tanq-2-5-deadcat-frame-by-letsflyrc"
  manufacturer:  "Rotor Riot"
  name:  "TANQ 2 5 Deadcat Frame - By LetsFlyRC"
  weight_g:  186.4
  wheelbase_mm:  225
  max_prop_size_mm:  129.54
  geometry:  "Deadcat"
  description:  "Rotor Riot TANQ 2 5 Deadcat Frame - By LetsFlyRC Deadcat drone frame with 225.0mm wheelbase, supporting up to 129.5mm props, weighing 186.4g."
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://www.getfpv.com/fpv/frames.html"
  }
}
frames:  {
  uuid:  "8345a861-a9f6-49c7-99c8-98abdc8ac00a"
  id:  "tanq-2-8-deadcat-frame-by-letsflyrc"
  manufacturer:  "Rotor Riot"
  name:  "TANQ 2 8 Deadcat Frame - By LetsFlyRC"
  weight_g:  186.4
  wheelbase_mm:  225
  max_prop_size_mm:  129.54
  geometry:  "Deadcat"
  description:  "Rotor Riot TANQ 2 8 Deadcat Frame - By LetsFlyRC Deadcat drone frame with 225.0mm wheelbase, supporting up to 129.5mm props, weighing 186.4g."
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://www.getfpv.com/fpv/frames.html"
  }
}
frames:  {
  uuid:  "cc64a5af-6deb-4e50-92da-c60d49470dc4"
  id:  "tanq-2-5-frame-by-letsflyrc"
  manufacturer:  "Rotor Riot"
  name:  "TANQ 2 5 Frame - By LetsFlyRC"
  weight_g:  177.4
  wheelbase_mm:  225
  max_prop_size_mm:  129.54
  geometry:  "Deadcat"
  description:  "Rotor Riot TANQ 2 5 Frame - By LetsFlyRC Deadcat drone frame with 225.0mm wheelbase, supporting up to 129.5mm props, weighing 177.4g."
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://www.getfpv.com/fpv/frames.html"
  }
}
frames:  {
  uuid:  "665415e7-251a-4bf4-acd2-643ea5eca28f"
  id:  "cl2-xr-7-deadcat-frame"
  manufacturer:  "Rotor Riot"
  name:  "CL2-XR 7 Deadcat Frame"
  weight_g:  185
  wheelbase_mm:  288
  max_prop_size_mm:  177.8
  geometry:  "Deadcat"
  description:  "Rotor Riot CL2-XR 7 Deadcat Frame Deadcat drone frame with 288.0mm wheelbase, supporting up to 177.8mm props, weighing 185.0g."
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://www.getfpv.com/fpv/frames.html"
  }
}
frames:  {
  uuid:  "c0a33d05-6d42-490f-82cb-2bd58eadbb3e"
  id:  "cl2-air-5-frame"
  manufacturer:  "Rotor Riot"
  name:  "CL2-AIR 5 Frame"
  weight_g:  70.5
  wheelbase_mm:  160
  max_prop_size_mm:  101.6
  geometry:  "Squashed-X"
  description:  "Rotor Riot CL2-AIR 5 Frame Squashed-X drone frame with 160.0mm wheelbase, supporting up to 101.6mm props, weighing 70.5g."
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://www.getfpv.com/fpv/frames.html"
  }
}
frames:  {
  uuid:  "d394f545-9fb3-436d-972f-a7929f8fabf5"
  id:  "mobula7-v4-75mm-frame"
  manufacturer:  "Happymodel"
  name:  "Mobula7 V4 75mm Frame"
  weight_g:  5.4
  wheelbase_mm:  75
  max_prop_size_mm:  40
  geometry:  "True X"
  description:  "Mobula7 V4 75mm Frame - 1S - Choose Color"
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://www.getfpv.com/fpv/frames.html"
  }
}
frames:  {
  uuid:  "b3833e50-8ff1-42f0-809d-760237a1bb56"
  id:  "mobula7-v3-75mm-frame"
  manufacturer:  "Happymodel"
  name:  "Mobula7 V3 75mm Frame"
  weight_g:  5.4
  wheelbase_mm:  75
  max_prop_size_mm:  40
  geometry:  "True X"
  description:  "Mobula7 V3 75mm Frame - 2S - Choose Color"
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://www.getfpv.com/fpv/frames.html"
  }
}
frames:  {
  uuid:  "88e7f950-c19b-41d3-b1c9-04ac9898780b"
  id:  "skyliner-mk3-5-frame"
  manufacturer:  "Rotor Riot"
  name:  "Skyliner MK3 5 Frame"
  weight_g:  125
  wheelbase_mm:  213
  max_prop_size_mm:  129.54
  geometry:  "True X"
  description:  "Rotor Riot Skyliner MK3 5 Frame True X drone frame with 213.0mm wheelbase, supporting up to 129.5mm props, weighing 125.0g."
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://www.getfpv.com/fpv/frames.html"
  }
}
frames:  {
  uuid:  "316ae38a-87e9-45a2-b137-fd9b61346123"
  id:  "skylite-3-3-5-frame-by-le-drib"
  manufacturer:  "Rotor Riot"
  name:  "SkyLite 3-3.5 Frame by Le Drib"
  weight_g:  4
  wheelbase_mm:  75
  max_prop_size_mm:  40
  geometry:  "True X"
  description:  "Rotor Riot SkyLite 3-3.5 Frame by Le Drib True X drone frame with 75.0mm wheelbase, supporting up to 40.0mm props, weighing 4.0g."
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://www.getfpv.com/fpv/frames.html"
  }
}
frames:  {
  uuid:  "252a8b18-c1a7-4604-a3dc-400abc5c9ff7"
  id:  "cl2-5-frame"
  manufacturer:  "Rotor Riot"
  name:  "CL2 5 Frame"
  weight_g:  52
  wheelbase_mm:  189
  max_prop_size_mm:  101.6
  geometry:  "True X"
  description:  "Rotor Riot CL2 5 Frame True X drone frame with 189.0mm wheelbase, supporting up to 101.6mm props, weighing 52.0g."
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://www.getfpv.com/fpv/frames.html"
  }
}
frames:  {
  uuid:  "448791ec-687c-4fb6-9284-3a04f9c96a40"
  id:  "moxy-5-frame"
  manufacturer:  "Rotor Riot"
  name:  "Moxy 5 Frame"
  weight_g:  125
  wheelbase_mm:  220
  max_prop_size_mm:  129.54
  geometry:  "True X"
  description:  "Rotor Riot Moxy 5 Frame True X drone frame with 220.0mm wheelbase, supporting up to 129.5mm props, weighing 125.0g."
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://www.getfpv.com/fpv/frames.html"
  }
}
frames:  {
  uuid:  "78a2e2c2-70ea-421c-86c6-c58d069d3a5f"
  id:  "hglrc-my10-10-inch-long-range"
  manufacturer:  "HGLRC"
  name:  "HGLRC MY10 10-inch Long Range /"
  weight_g:  217
  wheelbase_mm:  415
  max_prop_size_mm:  177.8
  geometry:  "True X"
  description:  "HGLRC MY10 10-inch Long Range / Training Frame"
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PRODUCT_PAGE
    url:  "https://www.hglrc.net/collections/frame"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://www.hglrc.net/collections/frame"
  }
}
frames:  {
  uuid:  "c83649e8-c723-4605-a3fa-4a116ff595e1"
  id:  "hglrc-my5-5-inch-freestyle-training-frame"
  manufacturer:  "HGLRC"
  name:  "HGLRC MY5 5-inch Freestyle /Training Frame"
  weight_g:  120
  wheelbase_mm:  210
  max_prop_size_mm:  129.54
  geometry:  "True X"
  description:  "HGLRC HGLRC MY5 5-inch Freestyle /Training Frame True X drone frame with 210.0mm wheelbase, supporting up to 129.5mm props, weighing 120.0g."
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PRODUCT_PAGE
    url:  "https://www.hglrc.net/collections/frame"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://www.hglrc.net/collections/frame"
  }
}
frames:  {
  uuid:  "f13fc97e-cdf2-4888-9d69-5551cbba953c"
  id:  "hglrc-rekon8-pro-8-inch-long-range-frame"
  manufacturer:  "HGLRC"
  name:  "HGLRC Rekon8 PRO 8-inch long-range Frame"
  weight_g:  124.2
  wheelbase_mm:  218
  max_prop_size_mm:  129.54
  geometry:  "True X"
  description:  "HGLRC Rekon8 PRO 8-inch long-range Frame Compatible With O4"
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PRODUCT_PAGE
    url:  "https://www.hglrc.net/collections/frame"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://www.hglrc.net/collections/frame"
  }
}
frames:  {
  uuid:  "a89372ca-c6d9-4920-9929-61bc82071ba7"
  id:  "hglrc-nblade-max-5-inch-true"
  manufacturer:  "HGLRC"
  name:  "HGLRC Nblade MAX 5 inch True"
  weight_g:  125
  wheelbase_mm:  225
  max_prop_size_mm:  127
  geometry:  "True X"
  description:  "HGLRC Nblade MAX 5 inch True X / DC Freestyle Cinematic FPV Frame"
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PRODUCT_PAGE
    url:  "https://www.hglrc.net/collections/frame"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://www.hglrc.net/collections/frame"
  }
}
frames:  {
  uuid:  "6b1eb3e4-e670-4b4e-8c93-c7e4ad09f60e"
  id:  "hglrc-my10-10-inch-long-range-payload"
  manufacturer:  "HGLRC"
  name:  "HGLRC MY10 10-inch Long-range & Payload"
  weight_g:  217
  wheelbase_mm:  415
  max_prop_size_mm:  177.8
  geometry:  "True X"
  description:  "HGLRC MY10 10-inch Long-range & Payload FPV Frame"
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PRODUCT_PAGE
    url:  "https://www.hglrc.net/collections/frame"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://www.hglrc.net/collections/frame"
  }
}
frames:  {
  uuid:  "2c1aaad6-b502-4fab-ba12-1b38dc4822fb"
  id:  "hglrc-my7-7-inch-long-range-train"
  manufacturer:  "HGLRC"
  name:  "HGLRC MY7 7-inch Long-range & Train"
  weight_g:  217
  wheelbase_mm:  335
  max_prop_size_mm:  177.8
  geometry:  "True X"
  description:  "HGLRC MY7 7-inch Long-range & Train ing FPV Frame"
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PRODUCT_PAGE
    url:  "https://www.hglrc.net/collections/frame"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://www.hglrc.net/collections/frame"
  }
}
frames:  {
  uuid:  "2b0a57d5-a30f-4edd-bcde-3bb9c550e5c5"
  id:  "hglrc-my5-5-inch-freestyle-training"
  manufacturer:  "HGLRC"
  name:  "HGLRC MY5 5-inch Freestyle & Training"
  weight_g:  120
  wheelbase_mm:  210
  max_prop_size_mm:  129.54
  geometry:  "True X"
  description:  "HGLRC MY5 5-inch Freestyle & Training FPV Frame"
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PRODUCT_PAGE
    url:  "https://www.hglrc.net/collections/frame"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://www.hglrc.net/collections/frame"
  }
}
frames:  {
  uuid:  "902bae4e-7a79-4469-ab1a-a0e95860c095"
  id:  "hglrc-wind5-lite-v2-racing-frame"
  manufacturer:  "HGLRC"
  name:  "HGLRC Wind5 Lite V2 Racing Frame"
  weight_g:  25
  wheelbase_mm:  195
  max_prop_size_mm:  101.6
  geometry:  "True-X"
  description:  "HGLRC Wind5 Lite V2 Racing Frame (camouflage)"
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PRODUCT_PAGE
    url:  "https://www.hglrc.net/collections/frame"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://www.hglrc.net/collections/frame"
  }
}
frames:  {
  uuid:  "33178d8d-ebd1-403f-95e0-dd6936caeb32"
  id:  "hglrc-rekon-5-lite-frame"
  manufacturer:  "HGLRC"
  name:  "HGLRC Rekon 5 Lite Frame"
  weight_g:  25
  wheelbase_mm:  206
  max_prop_size_mm:  129.54
  geometry:  "True-X"
  description:  "HGLRC HGLRC Rekon 5 Lite Frame True-X drone frame with 206.0mm wheelbase, supporting up to 129.5mm props, weighing 25.0g."
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PRODUCT_PAGE
    url:  "https://www.hglrc.net/collections/frame"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://www.hglrc.net/collections/frame"
  }
}
frames:  {
  uuid:  "1447f677-56a4-4743-a6c7-d0db6ee71ca5"
  id:  "hglrc-wind5-lite-v2-frame-kit-for-racing"
  manufacturer:  "HGLRC"
  name:  "HGLRC Wind5 Lite V2 Frame Kit for racing"
  weight_g:  80
  wheelbase_mm:  208
  max_prop_size_mm:  129.54
  geometry:  "True-X"
  description:  "HGLRC HGLRC Wind5 Lite V2 Frame Kit for racing True-X drone frame with 208.0mm wheelbase, supporting up to 129.5mm props, weighing 80.0g."
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PRODUCT_PAGE
    url:  "https://www.hglrc.net/collections/frame"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://www.hglrc.net/collections/frame"
  }
}
frames:  {
  uuid:  "4b61b186-dcb5-4a3d-96c4-30ddc491a5f2"
  id:  "hglrc-2-inch-talon-frame-for-cinewhoop"
  manufacturer:  "HGLRC"
  name:  "HGLRC 2-inch Talon frame for cinewhoop"
  weight_g:  53.4
  wheelbase_mm:  100
  max_prop_size_mm:  50.8
  geometry:  "Whoop"
  description:  "HGLRC HGLRC 2-inch Talon frame for cinewhoop Whoop drone frame with 100.0mm wheelbase, supporting up to 50.8mm props, weighing 53.4g."
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PRODUCT_PAGE
    url:  "https://www.hglrc.net/collections/frame"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://www.hglrc.net/collections/frame"
  }
}
frames:  {
  uuid:  "b6a161e5-183a-44ed-a08b-f16f660130d0"
  id:  "rekon-y6-5-inch-frame"
  manufacturer:  "HGLRC"
  name:  "Rekon Y6 5-inch frame"
  weight_g:  72.2
  wheelbase_mm:  210
  max_prop_size_mm:  129.54
  geometry:  "True X"
  description:  "Rekon Y6 5-inch frame compatible Analog/O3/O4/Moonlight Kit VTX long-range FPV frame/5MM arm kit"
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PRODUCT_PAGE
    url:  "https://www.hglrc.net/collections/frame"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://www.hglrc.net/collections/frame"
  }
}
frames:  {
  uuid:  "248e9bfb-45a5-422d-bd1d-e166eb20518c"
  id:  "hglrc-petrel-85whoop-ultra-light-indoor-frame"
  manufacturer:  "HGLRC"
  name:  "HGLRC Petrel 85Whoop Ultra-light Indoor Frame"
  weight_g:  42.2
  wheelbase_mm:  150
  max_prop_size_mm:  88.9
  geometry:  "Whoop"
  description:  "HGLRC Petrel 85Whoop Ultra-light Indoor Frame for FPV Racing Drone"
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PRODUCT_PAGE
    url:  "https://www.hglrc.net/collections/frame"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://www.hglrc.net/collections/frame"
  }
}
frames:  {
  uuid:  "56b62171-3d3d-486b-94b4-3d8fb693db9c"
  id:  "hglrc-draknight-2-inch-o4-analog-frame-ultralight"
  manufacturer:  "HGLRC"
  name:  "HGLRC Draknight 2-inch O4/Analog Frame Ultralight"
  weight_g:  46
  wheelbase_mm:  106
  max_prop_size_mm:  76.2
  geometry:  "True X"
  description:  "HGLRC Draknight 2-inch O4/Analog Frame Ultralight toothpicks/freestyle"
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PRODUCT_PAGE
    url:  "https://www.hglrc.net/collections/frame"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://www.hglrc.net/collections/frame"
  }
}
frames:  {
  uuid:  "ab17cef5-dbda-4d25-bde9-cd5fa38fec8d"
  id:  "hunter-5-fpv-racing-t700-frame-kit"
  manufacturer:  "FlyFish RC"
  name:  "Hunter 5 FPV Racing T700 Frame Kit"
  weight_g:  186.4
  wheelbase_mm:  225
  max_prop_size_mm:  129.54
  geometry:  "Deadcat"
  description:  "FlyFish RC Hunter 5 FPV Racing T700 Frame Kit Deadcat drone frame with 225.0mm wheelbase, supporting up to 129.5mm props, weighing 186.4g."
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://www.getfpv.com/fpv/frames.html"
  }
}
frames:  {
  uuid:  "97400e2b-466a-404f-a058-1d1db054a236"
  id:  "volador-vd4-o4-pro-deadcat-fpv"
  manufacturer:  "FlyFishRC"
  name:  "Volador VD4 O4 Pro Deadcat FPV"
  weight_g:  127
  wheelbase_mm:  183
  max_prop_size_mm:  101.6
  geometry:  "Deadcat"
  description:  "Volador VD4 O4 Pro Deadcat FPV T700 Frame Kit"
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PRODUCT_PAGE
    url:  "https://flyfish-rc.com/collections/frames"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://flyfish-rc.com/collections/frames"
  }
}
frames:  {
  uuid:  "cd02a300-b798-42bc-95d1-ed65b074f7fb"
  id:  "tony-5-o4-pro-sub250-fpv-freestyle-frame"
  manufacturer:  "FlyFishRC"
  name:  "Tony 5 O4 Pro Sub250 FPV Freestyle Frame"
  weight_g:  248.7
  wheelbase_mm:  215
  max_prop_size_mm:  129.54
  geometry:  "True-X"
  description:  "FlyFishRC Tony 5 O4 Pro Sub250 FPV Freestyle Frame True-X drone frame with 215.0mm wheelbase, supporting up to 129.5mm props, weighing 248.7g."
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PRODUCT_PAGE
    url:  "https://flyfish-rc.com/collections/frames"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://flyfish-rc.com/collections/frames"
  }
}
frames:  {
  uuid:  "9008cfee-fee8-46f5-9460-7155e909e5ee"
  id:  "atlas-4-o4-pro-lr-fpv-frame"
  manufacturer:  "FlyFishRC"
  name:  "Atlas 4 O4 Pro LR FPV Frame"
  weight_g:  127
  wheelbase_mm:  183
  max_prop_size_mm:  101.6
  geometry:  "Deadcat"
  description:  "FlyFishRC Atlas 4 O4 Pro LR FPV Frame Deadcat drone frame with 183.0mm wheelbase, supporting up to 101.6mm props, weighing 127.0g."
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PRODUCT_PAGE
    url:  "https://flyfish-rc.com/collections/frames"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://flyfish-rc.com/collections/frames"
  }
}
frames:  {
  uuid:  "0f26794c-4384-4f1d-b10e-9a4b37b82a1f"
  id:  "volador-ii-5-6inch-frame-o4-pro"
  manufacturer:  "FlyFishRC"
  name:  "Volador II 5-6inch Frame O4 Pro"
  weight_g:  127
  wheelbase_mm:  183
  max_prop_size_mm:  152
  geometry:  "Deadcat"
  description:  "Volador II 5-6inch Frame O4 Pro TPU Part Set"
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PRODUCT_PAGE
    url:  "https://flyfish-rc.com/collections/frames"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://flyfish-rc.com/collections/frames"
  }
}
frames:  {
  uuid:  "eed7c0bb-aff8-44c9-b8a1-db3a323e9742"
  id:  "volador-vx3-vx3-5-o4-pro-freestyle"
  manufacturer:  "FlyFish RC"
  name:  "Volador VX3 VX3.5 O4 Pro Freestyle"
  weight_g:  70.5
  wheelbase_mm:  160
  max_prop_size_mm:  101.6
  geometry:  "Squashed-X"
  description:  "Volador VX3 VX3.5 O4 Pro Freestyle Frame Kit"
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://www.getfpv.com/fpv/frames.html"
  }
}
frames:  {
  uuid:  "79e840d1-97a7-42ec-8274-7ddc4957ead6"
  id:  "volador-ii-vx5-o4-pro-fpv"
  manufacturer:  "FlyFish RC"
  name:  "Volador II VX5 O4 Pro FPV"
  weight_g:  177.4
  wheelbase_mm:  225
  max_prop_size_mm:  129.54
  geometry:  "Deadcat"
  description:  "Volador II VX5 O4 Pro FPV Freestyle T700 Frame Kit"
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://www.getfpv.com/fpv/frames.html"
  }
}
frames:  {
  uuid:  "638793db-cfbe-4977-a0d6-15ce1fe96881"
  id:  "volador-ii-vd5-o4-pro-deadcat"
  manufacturer:  "FlyFish RC"
  name:  "Volador II VD5 O4 Pro Deadcat"
  weight_g:  186.4
  wheelbase_mm:  225
  max_prop_size_mm:  129.54
  geometry:  "Deadcat"
  description:  "Volador II VD5 O4 Pro Deadcat FPV T700 Frame Kit"
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://www.getfpv.com/fpv/frames.html"
  }
}
frames:  {
  uuid:  "33276e28-74e0-4213-ba0f-c1e5b9bd8117"
  id:  "volador-ii-vx6-o4-pro-fpv"
  manufacturer:  "FlyFishRC"
  name:  "Volador II VX6 O4 Pro FPV"
  weight_g:  188.2
  wheelbase_mm:  268
  max_prop_size_mm:  152.4
  geometry:  "Deadcat"
  description:  "Volador II VX6 O4 Pro FPV Freestyle T700 Frame Kit"
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PRODUCT_PAGE
    url:  "https://flyfish-rc.com/collections/frames"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://flyfish-rc.com/collections/frames"
  }
}
frames:  {
  uuid:  "50993d46-8b6f-4dc6-ab03-7ca318274725"
  id:  "volador-ii-vd6-o4-pro-deadcat"
  manufacturer:  "FlyFishRC"
  name:  "Volador II VD6 O4 Pro Deadcat"
  weight_g:  200
  wheelbase_mm:  260
  max_prop_size_mm:  152.4
  geometry:  "Deadcat"
  description:  "Volador II VD6 O4 Pro Deadcat FPV T700 Frame Kit"
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PRODUCT_PAGE
    url:  "https://flyfish-rc.com/collections/frames"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://flyfish-rc.com/collections/frames"
  }
}
frames:  {
  uuid:  "c1021079-2ecb-4501-b3d9-5f3ec3b87a44"
  id:  "fifty5-o4-pro-freestyle-fpv-frame-kit"
  manufacturer:  "FlyFishRC"
  name:  "FIFTY5 O4 Pro Freestyle FPV Frame Kit"
  weight_g:  70.5
  wheelbase_mm:  160
  max_prop_size_mm:  101.6
  geometry:  "Squashed-X"
  description:  "FlyFishRC FIFTY5 O4 Pro Freestyle FPV Frame Kit Squashed-X drone frame with 160.0mm wheelbase, supporting up to 101.6mm props, weighing 70.5g."
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PRODUCT_PAGE
    url:  "https://flyfish-rc.com/collections/frames"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://flyfish-rc.com/collections/frames"
  }
}
frames:  {
  uuid:  "bac31f73-dd36-4256-a79d-2896bebd7a68"
  id:  "atlas-4-lr-fpv-frame"
  manufacturer:  "FlyFishRC"
  name:  "Atlas 4 LR FPV Frame"
  weight_g:  127
  wheelbase_mm:  183
  max_prop_size_mm:  101.6
  geometry:  "Deadcat"
  description:  "FlyFishRC Atlas 4 LR FPV Frame Deadcat drone frame with 183.0mm wheelbase, supporting up to 101.6mm props, weighing 127.0g."
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PRODUCT_PAGE
    url:  "https://flyfish-rc.com/collections/frames"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://flyfish-rc.com/collections/frames"
  }
}
frames:  {
  uuid:  "29c1e8f9-1b14-4c55-bcaf-92b7874abdff"
  id:  "tony-5-sub250-fpv-freestyle-frame"
  manufacturer:  "FlyFishRC"
  name:  "Tony 5 Sub250 FPV Freestyle Frame"
  weight_g:  248.7
  wheelbase_mm:  215
  max_prop_size_mm:  129.54
  geometry:  "True-X"
  description:  "FlyFishRC Tony 5 Sub250 FPV Freestyle Frame True-X drone frame with 215.0mm wheelbase, supporting up to 129.5mm props, weighing 248.7g."
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PRODUCT_PAGE
    url:  "https://flyfish-rc.com/collections/frames"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://flyfish-rc.com/collections/frames"
  }
}
frames:  {
  uuid:  "2d21b0a3-006c-407b-b1bd-c3856fc95b5d"
  id:  "fifty5-o3-freestyle-fpv-frame-kit"
  manufacturer:  "FlyFishRC"
  name:  "FIFTY5 O3 Freestyle FPV Frame Kit"
  weight_g:  127.7
  wheelbase_mm:  255
  max_prop_size_mm:  152.4
  geometry:  "True-X"
  description:  "FlyFishRC FIFTY5 O3 Freestyle FPV Frame Kit True-X drone frame with 255.0mm wheelbase, supporting up to 152.4mm props, weighing 127.7g."
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PRODUCT_PAGE
    url:  "https://flyfish-rc.com/collections/frames"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://flyfish-rc.com/collections/frames"
  }
}
frames:  {
  uuid:  "c5ce19cf-f105-45fc-a58a-9dd26a44a241"
  id:  "volador-vx3-vx3-5-o3-freestyle-frame-kit"
  manufacturer:  "FlyFishRC"
  name:  "Volador VX3 VX3.5 O3 Freestyle Frame Kit"
  weight_g:  70.5
  wheelbase_mm:  160
  max_prop_size_mm:  101.6
  geometry:  "Squashed-X"
  description:  "FlyFishRC Volador VX3 VX3.5 O3 Freestyle Frame Kit Squashed-X drone frame with 160.0mm wheelbase, supporting up to 101.6mm props, weighing 70.5g."
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PRODUCT_PAGE
    url:  "https://flyfish-rc.com/collections/frames"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://flyfish-rc.com/collections/frames"
  }
}
frames:  {
  uuid:  "bab776d7-ab18-4ed7-a54a-c49546e5ef6e"
  id:  "volador-ii-vx5-o3-fpv-freestyle"
  manufacturer:  "FlyFish RC"
  name:  "Volador II VX5 O3 FPV Freestyle"
  weight_g:  177.4
  wheelbase_mm:  225
  max_prop_size_mm:  129.54
  geometry:  "Deadcat"
  description:  "Volador II VX5 O3 FPV Freestyle T700 Frame Kit"
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://www.getfpv.com/fpv/frames.html"
  }
}
frames:  {
  uuid:  "c20093d0-6e4f-4141-ba8d-449270ac3dac"
  id:  "volador-ii-vd5-o3-deadcat-fpv"
  manufacturer:  "FlyFish RC"
  name:  "Volador II VD5 O3 Deadcat FPV"
  weight_g:  186.4
  wheelbase_mm:  225
  max_prop_size_mm:  129.54
  geometry:  "Deadcat"
  description:  "Volador II VD5 O3 Deadcat FPV T700 Frame Kit"
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://www.getfpv.com/fpv/frames.html"
  }
}
frames:  {
  uuid:  "3c44683b-2b79-41ec-ac6e-500c747f050c"
  id:  "volador-ii-vx6-o3-fpv-freestyle"
  manufacturer:  "FlyFishRC"
  name:  "Volador II VX6 O3 FPV Freestyle"
  weight_g:  188.2
  wheelbase_mm:  268
  max_prop_size_mm:  152.4
  geometry:  "Deadcat"
  description:  "Volador II VX6 O3 FPV Freestyle T700 Frame Kit"
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PRODUCT_PAGE
    url:  "https://flyfish-rc.com/collections/frames"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://flyfish-rc.com/collections/frames"
  }
}
frames:  {
  uuid:  "fef245b6-4ab2-402e-851d-25d26ce49e99"
  id:  "volador-ii-vd6-o3-deadcat-fpv"
  manufacturer:  "FlyFishRC"
  name:  "Volador II VD6 O3 Deadcat FPV"
  weight_g:  200
  wheelbase_mm:  260
  max_prop_size_mm:  152.4
  geometry:  "Deadcat"
  description:  "Volador II VD6 O3 Deadcat FPV T700 Frame Kit"
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PRODUCT_PAGE
    url:  "https://flyfish-rc.com/collections/frames"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://flyfish-rc.com/collections/frames"
  }
}
frames:  {
  uuid:  "3e8ac709-2f7f-454f-aec5-69577b171bfa"
  id:  "volador-vd5-deadcat-fpv-lr-t700"
  manufacturer:  "FlyFishRC"
  name:  "Volador VD5 Deadcat FPV LR T700"
  weight_g:  186.4
  wheelbase_mm:  225
  max_prop_size_mm:  129.54
  geometry:  "Deadcat"
  description:  "Volador VD5 Deadcat FPV LR T700 Frame Kit"
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PRODUCT_PAGE
    url:  "https://flyfish-rc.com/collections/frames"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://flyfish-rc.com/collections/frames"
  }
}
frames:  {
  uuid:  "ad444354-b0c6-4e9c-8b8b-b28c5b861e14"
  id:  "volador-vd6-deadcat-fpv-lr-t700"
  manufacturer:  "FlyFishRC"
  name:  "Volador VD6 Deadcat FPV LR T700"
  weight_g:  200
  wheelbase_mm:  260
  max_prop_size_mm:  152.4
  geometry:  "Deadcat"
  description:  "Volador VD6 Deadcat FPV LR T700 Frame Kit"
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PRODUCT_PAGE
    url:  "https://flyfish-rc.com/collections/frames"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://flyfish-rc.com/collections/frames"
  }
}
frames:  {
  uuid:  "d7d3ebfb-bea9-4879-ad79-6b9b4d57af7a"
  id:  "volador-vx5-fpv-freestyle-t700-frame-kit"
  manufacturer:  "FlyFishRC"
  name:  "Volador VX5 FPV Freestyle T700 Frame Kit"
  weight_g:  177.4
  wheelbase_mm:  225
  max_prop_size_mm:  129.54
  geometry:  "Deadcat"
  description:  "FlyFishRC Volador VX5 FPV Freestyle T700 Frame Kit Deadcat drone frame with 225.0mm wheelbase, supporting up to 129.5mm props, weighing 177.4g."
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PRODUCT_PAGE
    url:  "https://flyfish-rc.com/collections/frames"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://flyfish-rc.com/collections/frames"
  }
}
frames:  {
  uuid:  "0e4dfbe7-be55-49d0-8c0c-9a868d3d1f23"
  id:  "volador-vx6-fpv-freestyle-t700-frame-kit"
  manufacturer:  "FlyFishRC"
  name:  "Volador VX6 FPV Freestyle T700 Frame Kit"
  weight_g:  188.2
  wheelbase_mm:  268
  max_prop_size_mm:  152.4
  geometry:  "Deadcat"
  description:  "FlyFishRC Volador VX6 FPV Freestyle T700 Frame Kit Deadcat drone frame with 268.0mm wheelbase, supporting up to 152.4mm props, weighing 188.2g."
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PRODUCT_PAGE
    url:  "https://flyfish-rc.com/collections/frames"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://flyfish-rc.com/collections/frames"
  }
}
frames:  {
  uuid:  "6f7e8b3b-53bd-4a67-a5c2-7dbdc65fbc09"
  id:  "dollyfly25-v2-o4-pro-frame-and-parts"
  manufacturer:  "sub250"
  name:  "DollyFly25 V2 O4 Pro Frame and Parts"
  weight_g:  248.7
  wheelbase_mm:  215
  max_prop_size_mm:  129.54
  geometry:  "True-X"
  description:  "sub250 DollyFly25 V2 O4 Pro Frame and Parts True-X drone frame with 215.0mm wheelbase, supporting up to 129.5mm props, weighing 248.7g."
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://www.getfpv.com/fpv/frames.html"
  }
}
frames:  {
  uuid:  "dfa4533f-65c8-4a41-a1e9-517f10079c34"
  id:  "sub250-dollyfly16-hd-o4-pro-frame-parts"
  manufacturer:  "Sub250"
  name:  "Sub250 DollyFly16 HD O4 Pro Frame Parts"
  weight_g:  88
  wheelbase_mm:  85
  max_prop_size_mm:  50.8
  geometry:  "True X"
  description:  "Sub250 Sub250 DollyFly16 HD O4 Pro Frame Parts True X drone frame with 85.0mm wheelbase, supporting up to 50.8mm props, weighing 88.0g."
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://www.getfpv.com/fpv/frames.html"
  }
}
frames:  {
  uuid:  "4361774c-dc01-439a-9603-1021a90f7112"
  id:  "sub250-dollyfly25-o3-frame-kit-and"
  manufacturer:  "Sub250"
  name:  "Sub250 DollyFly25 O3 Frame Kit and"
  weight_g:  180
  wheelbase_mm:  120
  max_prop_size_mm:  76.2
  geometry:  "True X"
  description:  "Sub250 DollyFly25 O3 Frame Kit and Frame Part"
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://www.getfpv.com/fpv/frames.html"
  }
}
frames:  {
  uuid:  "3069b245-6a3c-4fa9-a682-a44ed458b7b0"
  id:  "sub250-nf16-1-6-inch-frame-for-nanofly16"
  manufacturer:  "Sub250"
  name:  "Sub250 NF16 1.6 inch Frame for Nanofly16"
  weight_g:  8.3
  wheelbase_mm:  77
  max_prop_size_mm:  40
  geometry:  "True X"
  description:  "Sub250 Sub250 NF16 1.6 inch Frame for Nanofly16 True X drone frame with 77.0mm wheelbase, supporting up to 40.0mm props, weighing 8.3g."
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://www.getfpv.com/fpv/frames.html"
  }
}
frames:  {
  uuid:  "54b419f4-b2c9-43be-a539-145af24e9718"
  id:  "fpvcycle-cinesplore-2-frame-kit"
  manufacturer:  "FPVCycle"
  name:  "FPVCycle Cinesplore 2 Frame Kit"
  weight_g:  53.4
  wheelbase_mm:  100
  max_prop_size_mm:  50.8
  geometry:  "True X"
  description:  "FPVCycle FPVCycle Cinesplore 2 Frame Kit True X drone frame with 100.0mm wheelbase, supporting up to 50.8mm props, weighing 53.4g."
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://www.getfpv.com/fpv/frames.html"
  }
}
frames:  {
  uuid:  "e55cd74d-1aef-46ba-a628-11ddba8638ff"
  id:  "sonicare-x4-5-frame-kit"
  manufacturer:  "FPVCycle"
  name:  "Sonicare (X4) 5 Frame Kit"
  weight_g:  121
  wheelbase_mm:  220
  max_prop_size_mm:  129.54
  geometry:  "True X"
  description:  "FPVCycle Sonicare (X4) 5 Frame Kit True X drone frame with 220.0mm wheelbase, supporting up to 129.5mm props, weighing 121.0g."
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://www.getfpv.com/fpv/frames.html"
  }
}
frames:  {
  uuid:  "9122a86f-d3ff-4d1f-ac85-9b927c68d05f"
  id:  "fpvcycle-cineglide-7-frame"
  manufacturer:  "FPVCycle"
  name:  "FPVCycle CineGlide 7 Frame"
  weight_g:  49.5
  wheelbase_mm:  260
  max_prop_size_mm:  152.4
  geometry:  "True X"
  description:  "FPVCycle FPVCycle CineGlide 7 Frame True X drone frame with 260.0mm wheelbase, supporting up to 152.4mm props, weighing 49.5g."
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://www.getfpv.com/fpv/frames.html"
  }
}
frames:  {
  uuid:  "57b4e943-45f4-40a5-9dca-21a8270f2e84"
  id:  "fpvcycle-toothfairy-2-frame"
  manufacturer:  "FPVCycle"
  name:  "FPVCycle ToothFairy 2 Frame"
  weight_g:  58
  wheelbase_mm:  220
  max_prop_size_mm:  129.54
  geometry:  "True-X"
  description:  "FPVCycle FPVCycle ToothFairy 2 Frame True-X drone frame with 220.0mm wheelbase, supporting up to 129.5mm props, weighing 58.0g."
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://www.getfpv.com/fpv/frames.html"
  }
}
frames:  {
  uuid:  "2ca30025-3196-4b01-bf1e-47addf247345"
  id:  "fpvcycle-cinesplore-frame"
  manufacturer:  "FPVCycle"
  name:  "FPVCycle CineSplore Frame"
  weight_g:  201
  wheelbase_mm:  167
  max_prop_size_mm:  101.6
  geometry:  "True X"
  description:  "FPVCycle FPVCycle CineSplore Frame True X drone frame with 167.0mm wheelbase, supporting up to 101.6mm props, weighing 201.0g."
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://www.getfpv.com/fpv/frames.html"
  }
}
frames:  {
  uuid:  "6b3f0b89-f602-4a44-8ee6-4e02d61be726"
  id:  "fpvcycle-powerpick-frame"
  manufacturer:  "FPVCycle"
  name:  "FPVCycle PowerPick Frame"
  weight_g:  35.7
  wheelbase_mm:  93.9
  max_prop_size_mm:  50.8
  geometry:  "True X"
  description:  "FPVCycle PowerPick Frame  (Choose 4” or 5”)"
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://www.getfpv.com/fpv/frames.html"
  }
}
frames:  {
  uuid:  "f970a835-fa6c-4400-b18b-3d9aa0d51c32"
  id:  "fpvcycle-molar-5-race-frame"
  manufacturer:  "FPVCycle"
  name:  "FPVCycle MOLAR - 5 Race Frame"
  weight_g:  78
  wheelbase_mm:  208
  max_prop_size_mm:  129.54
  geometry:  "True X"
  description:  "FPVCycle FPVCycle MOLAR - 5 Race Frame True X drone frame with 208.0mm wheelbase, supporting up to 129.5mm props, weighing 78.0g."
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://www.getfpv.com/fpv/frames.html"
  }
}
frames:  {
  uuid:  "0e04d336-1756-4612-88a9-a617635b59d4"
  id:  "toothpick-3-frame-tp3"
  manufacturer:  "FPVCycle"
  name:  "ToothPick 3 Frame - TP3"
  weight_g:  17.5
  wheelbase_mm:  160
  max_prop_size_mm:  101.6
  geometry:  "Squashed-X"
  description:  "FPVCycle ToothPick 3 Frame - TP3 Squashed-X drone frame with 160.0mm wheelbase, supporting up to 101.6mm props, weighing 17.5g."
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://www.getfpv.com/fpv/frames.html"
  }
}
frames:  {
  uuid:  "48dc2f08-7703-4d5a-9557-d1d2cbacc31f"
  id:  "fpvcycle-babytooth-frame"
  manufacturer:  "FPVCycle"
  name:  "FPVCycle BabyTooth Frame"
  weight_g:  125
  wheelbase_mm:  220
  max_prop_size_mm:  129.54
  geometry:  "True X"
  description:  "FPVCycle BabyTooth Frame (CHOOSE THICKNESS)"
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://www.getfpv.com/fpv/frames.html"
  }
}
frames:  {
  uuid:  "592a05ee-d015-4dae-b8db-fecaac899484"
  id:  "fpvcycle-glide-5-frame"
  manufacturer:  "FPVCycle"
  name:  "FPVCycle Glide -  5 Frame"
  weight_g:  70.5
  wheelbase_mm:  160
  max_prop_size_mm:  101.6
  geometry:  "Squashed-X"
  description:  "FPVCycle FPVCycle Glide -  5 Frame Squashed-X drone frame with 160.0mm wheelbase, supporting up to 101.6mm props, weighing 70.5g."
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://www.getfpv.com/fpv/frames.html"
  }
}
frames:  {
  uuid:  "01923019-3008-7001-8001-000000000001"
  id:  "tbs-source-one-v5-frame"
  manufacturer:  "TBS"
  name:  "TBS Source One V5 5-Inch Frame"
  weight_g:  125
  wheelbase_mm:  226
  max_prop_size_mm:  129.54
  geometry:  "True X"
  description:  "Popular open-source community collaborative freestyle frame designed by Team BlackSheep for durability, cheap spare arms, and easy maintenance."
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PRODUCT_PAGE
    url:  "https://www.team-blacksheep.com/products/prod:source_one_v5"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_DOCUMENTATION
    url:  "https://github.com/tbs-trappy/source_one"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://www.getfpv.com/tbs-source-one-v5-5-frame.html"
  }
}
frames:  {
  uuid:  "01923019-3008-7001-8001-000000000002"
  id:  "speedybee-mario-5-dc-frame"
  manufacturer:  "SpeedyBee"
  name:  "SpeedyBee Mario 5 DC Frame"
  weight_g:  129
  wheelbase_mm:  227
  max_prop_size_mm:  129.54
  geometry:  "Deadcat"
  description:  "Aerodynamic 5-inch deadcat freestyle frame with zero props in view for DJI O3, injection-molded TPU protection, and dual 20x20/30x30 mounting."
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PRODUCT_PAGE
    url:  "https://www.speedybee.com/speedybee-mario-5-frame/"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://pyrodrone.com/products/speedybee-mario-5-dc-fpv-freestyle-frame-kit"
  }
}
frames:  {
  uuid:  "01923019-3008-7001-8001-000000000003"
  id:  "iflight-nazgul-evoque-f5-v2-frame"
  manufacturer:  "iFlight"
  name:  "iFlight Nazgul Evoque F5 V2 Frame"
  weight_g:  160
  wheelbase_mm:  225
  max_prop_size_mm:  129.54
  geometry:  "Squashed X"
  description:  "Flagship geometric frame with illuminated side panels, XT60 integrated plug, and CNC aluminum camera cage."
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PRODUCT_PAGE
    url:  "https://shop.iflight.com/evoque-f5-v2-frame-kit-pro1873"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://www.getfpv.com/iflight-nazgul-evoque-f5-v2-frame-kit-deadcat-squashed-x.html"
  }
}
frames:  {
  uuid:  "01923019-3008-7001-8001-000000000004"
  id:  "geprc-mark5-frame"
  manufacturer:  "GEPRC"
  name:  "GEPRC Mark5 5-Inch Freestyle Frame"
  weight_g:  130
  wheelbase_mm:  225
  max_prop_size_mm:  129.54
  geometry:  "Squashed X"
  description:  "High-rigidity freestyle frame with CNC 7075 aluminum camera plates and vibration-damped stack design."
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PRODUCT_PAGE
    url:  "https://geprc.com/product/geprc-mark5-frame-kit/"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://pyrodrone.com/products/geprc-mark-5-frame-kit"
  }
}
frames:  {
  uuid:  "01923019-3008-7001-8001-000000000005"
  id:  "flywoo-explorer-lr-4-v2-frame"
  manufacturer:  "Flywoo"
  name:  "Flywoo Explorer LR 4 V2 Frame"
  weight_g:  41
  wheelbase_mm:  168
  max_prop_size_mm:  101.6
  geometry:  "Deadcat"
  description:  "Ultralight Sub-250g 4-inch micro long-range frame designed by Dave_C FPV with deadcat geometry for obstruction-free flight recording."
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PRODUCT_PAGE
    url:  "https://flywoo.net/products/explorer-lr-4-v2-frame-kit"
  }
  reference_links:  {
    type:  REFERENCE_LINK_TYPE_PURCHASE
    url:  "https://www.getfpv.com/flywoo-explorer-lr-4-quad-frame-kit-v2.html"
  }
}
