-- Code generated by protoc-gen-sql. DO NOT EDIT.
CREATE TABLE IF NOT EXISTS antennas (
  uuid UUID NOT NULL,
  PRIMARY KEY (uuid),
  id TEXT UNIQUE NOT NULL,
  manufacturer TEXT NOT NULL,
  name TEXT NOT NULL,
  is_internal_only BOOLEAN NOT NULL,
  weight_g DECIMAL NOT NULL,
  connector TEXT NOT NULL,
  polarization TEXT NOT NULL,
  frequency_band_mhz INTEGER NOT NULL,
  length_mm DECIMAL NOT NULL,
  gain_dbi DECIMAL NOT NULL,
  description TEXT NOT NULL,
  reference_links JSONB,
  primary_display_image TEXT,
  media JSONB
);

CREATE INDEX IF NOT EXISTS idx_antennas_manufacturer ON antennas (manufacturer);

CREATE TABLE IF NOT EXISTS batteries (
  uuid UUID NOT NULL,
  PRIMARY KEY (uuid),
  id TEXT UNIQUE NOT NULL,
  manufacturer TEXT NOT NULL,
  name TEXT NOT NULL,
  weight_g DECIMAL NOT NULL,
  capacity_mah INTEGER NOT NULL,
  cell_count_s INTEGER NOT NULL,
  chemistry TEXT NOT NULL,
  connector TEXT NOT NULL,
  description TEXT NOT NULL,
  reference_links JSONB,
  primary_display_image TEXT,
  media JSONB,
  min_voltage DECIMAL NOT NULL,
  max_voltage DECIMAL NOT NULL,
  max_current_a DECIMAL NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_batteries_manufacturer ON batteries (manufacturer);

CREATE INDEX IF NOT EXISTS idx_batteries_cell_count_s ON batteries (cell_count_s);

CREATE TABLE IF NOT EXISTS builds (
  uuid UUID NOT NULL,
  PRIMARY KEY (uuid),
  id TEXT UNIQUE NOT NULL,
  name TEXT NOT NULL,
  description TEXT NOT NULL,
  frame_uuid UUID NOT NULL,
  motor_uuid UUID NOT NULL,
  flight_controller_uuid UUID NOT NULL,
  electronic_speed_controller_uuids UUID[],
  receiver_uuids UUID[],
  antenna_uuids UUID[],
  propeller_uuid UUID NOT NULL,
  camera_uuids UUID[],
  video_transmitter_uuid UUID NOT NULL,
  gps_receiver_uuid UUID,
  reference_links JSONB,
  primary_display_image TEXT,
  media JSONB
);

CREATE TABLE IF NOT EXISTS cameras (
  uuid UUID NOT NULL,
  PRIMARY KEY (uuid),
  id TEXT UNIQUE NOT NULL,
  manufacturer TEXT NOT NULL,
  name TEXT NOT NULL,
  is_internal_only BOOLEAN NOT NULL,
  weight_g DECIMAL NOT NULL,
  protocol TEXT NOT NULL,
  sensor_size TEXT NOT NULL,
  width_mm INTEGER NOT NULL,
  lens_size_mm DECIMAL NOT NULL,
  description TEXT NOT NULL,
  reference_links JSONB,
  primary_display_image TEXT,
  media JSONB
);

CREATE INDEX IF NOT EXISTS idx_cameras_manufacturer ON cameras (manufacturer);

CREATE TABLE IF NOT EXISTS electronic_speed_controllers (
  uuid UUID NOT NULL,
  PRIMARY KEY (uuid),
  id TEXT UNIQUE NOT NULL,
  manufacturer TEXT NOT NULL,
  name TEXT NOT NULL,
  is_internal_only BOOLEAN NOT NULL,
  weight_g DECIMAL NOT NULL,
  max_motors INTEGER NOT NULL,
  motor_current_max_a DECIMAL NOT NULL,
  motor_current_burst_a DECIMAL NOT NULL,
  firmware TEXT NOT NULL,
  description TEXT NOT NULL,
  reference_links JSONB,
  primary_display_image TEXT,
  media JSONB,
  min_voltage DECIMAL NOT NULL,
  max_voltage DECIMAL NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_electronic_speed_controllers_manufacturer ON electronic_speed_controllers (manufacturer);

CREATE TABLE IF NOT EXISTS flight_controllers (
  uuid UUID NOT NULL,
  PRIMARY KEY (uuid),
  id TEXT UNIQUE NOT NULL,
  manufacturer TEXT NOT NULL,
  name TEXT NOT NULL,
  is_internal_only BOOLEAN NOT NULL,
  weight_g DECIMAL NOT NULL,
  processor TEXT NOT NULL,
  gyro TEXT NOT NULL,
  internal_electronic_speed_controller_uuid UUID,
  internal_receiver_uuid UUID,
  internal_video_transmitter_uuid UUID,
  description TEXT NOT NULL,
  reference_links JSONB,
  primary_display_image TEXT,
  media JSONB,
  min_voltage DECIMAL NOT NULL,
  max_voltage DECIMAL NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_flight_controllers_manufacturer ON flight_controllers (manufacturer);

CREATE TABLE IF NOT EXISTS frames (
  uuid UUID NOT NULL,
  PRIMARY KEY (uuid),
  id TEXT UNIQUE NOT NULL,
  manufacturer TEXT NOT NULL,
  name TEXT NOT NULL,
  weight_g DECIMAL NOT NULL,
  wheelbase_mm DECIMAL NOT NULL,
  max_prop_size_mm DECIMAL NOT NULL,
  geometry TEXT NOT NULL,
  description TEXT NOT NULL,
  reference_links JSONB,
  primary_display_image TEXT,
  media JSONB
);

CREATE INDEX IF NOT EXISTS idx_frames_manufacturer ON frames (manufacturer);

CREATE TABLE IF NOT EXISTS gps_receivers (
  uuid UUID NOT NULL,
  PRIMARY KEY (uuid),
  id TEXT UNIQUE NOT NULL,
  manufacturer TEXT NOT NULL,
  name TEXT NOT NULL,
  is_internal_only BOOLEAN NOT NULL,
  weight_g DECIMAL NOT NULL,
  chipset TEXT NOT NULL,
  protocol TEXT NOT NULL,
  compass TEXT,
  input_voltage_min_v DECIMAL NOT NULL,
  input_voltage_max_v DECIMAL NOT NULL,
  description TEXT NOT NULL,
  reference_links JSONB,
  primary_display_image TEXT,
  media JSONB
);

CREATE INDEX IF NOT EXISTS idx_gps_receivers_manufacturer ON gps_receivers (manufacturer);

CREATE INDEX IF NOT EXISTS idx_gps_receivers_protocol ON gps_receivers (protocol);

CREATE TABLE IF NOT EXISTS motors (
  uuid UUID NOT NULL,
  PRIMARY KEY (uuid),
  id TEXT UNIQUE NOT NULL,
  manufacturer TEXT NOT NULL,
  name TEXT NOT NULL,
  weight_g DECIMAL NOT NULL,
  stator_diameter_mm DECIMAL NOT NULL,
  stator_height_mm DECIMAL NOT NULL,
  kv INTEGER NOT NULL,
  description TEXT NOT NULL,
  reference_links JSONB,
  primary_display_image TEXT,
  media JSONB,
  min_voltage DECIMAL NOT NULL,
  max_voltage DECIMAL NOT NULL,
  max_current_a DECIMAL NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_motors_manufacturer ON motors (manufacturer);

CREATE INDEX IF NOT EXISTS idx_motors_kv ON motors (kv);

CREATE TABLE IF NOT EXISTS propellers (
  uuid UUID NOT NULL,
  PRIMARY KEY (uuid),
  id TEXT UNIQUE NOT NULL,
  manufacturer TEXT NOT NULL,
  name TEXT NOT NULL,
  weight_g DECIMAL NOT NULL,
  diameter_mm DECIMAL NOT NULL,
  pitch_mm DECIMAL NOT NULL,
  blades INTEGER NOT NULL,
  material TEXT NOT NULL,
  description TEXT NOT NULL,
  reference_links JSONB,
  primary_display_image TEXT,
  media JSONB
);

CREATE INDEX IF NOT EXISTS idx_propellers_manufacturer ON propellers (manufacturer);

CREATE TABLE IF NOT EXISTS receivers (
  uuid UUID NOT NULL,
  PRIMARY KEY (uuid),
  id TEXT UNIQUE NOT NULL,
  manufacturer TEXT NOT NULL,
  name TEXT NOT NULL,
  is_internal_only BOOLEAN NOT NULL,
  weight_g DECIMAL NOT NULL,
  protocol TEXT NOT NULL,
  frequency_band_mhz INTEGER NOT NULL,
  has_telemetry BOOLEAN NOT NULL,
  antenna_uuids UUID[],
  description TEXT NOT NULL,
  reference_links JSONB,
  primary_display_image TEXT,
  media JSONB
);

CREATE INDEX IF NOT EXISTS idx_receivers_manufacturer ON receivers (manufacturer);

CREATE INDEX IF NOT EXISTS idx_receivers_protocol ON receivers (protocol);

CREATE TABLE IF NOT EXISTS video_transmitters (
  uuid UUID NOT NULL,
  PRIMARY KEY (uuid),
  id TEXT UNIQUE NOT NULL,
  manufacturer TEXT NOT NULL,
  name TEXT NOT NULL,
  is_internal_only BOOLEAN NOT NULL,
  weight_g DECIMAL NOT NULL,
  protocol TEXT NOT NULL,
  max_power_mw INTEGER NOT NULL,
  input_voltage_min_v DECIMAL NOT NULL,
  input_voltage_max_v DECIMAL NOT NULL,
  antenna_uuids UUID[],
  description TEXT NOT NULL,
  reference_links JSONB,
  primary_display_image TEXT,
  media JSONB
);

CREATE INDEX IF NOT EXISTS idx_video_transmitters_manufacturer ON video_transmitters (manufacturer);

CREATE INDEX IF NOT EXISTS idx_video_transmitters_protocol ON video_transmitters (protocol);

-- Foreign Keys
ALTER TABLE builds
ADD CONSTRAINT fk_builds_frame_uuid FOREIGN KEY (frame_uuid) REFERENCES frames (uuid);

ALTER TABLE builds
ADD CONSTRAINT fk_builds_motor_uuid FOREIGN KEY (motor_uuid) REFERENCES motors (uuid);

ALTER TABLE builds
ADD CONSTRAINT fk_builds_flight_controller_uuid FOREIGN KEY (flight_controller_uuid) REFERENCES flight_controllers (uuid);

ALTER TABLE builds
ADD CONSTRAINT fk_builds_propeller_uuid FOREIGN KEY (propeller_uuid) REFERENCES propellers (uuid);

ALTER TABLE builds
ADD CONSTRAINT fk_builds_video_transmitter_uuid FOREIGN KEY (video_transmitter_uuid) REFERENCES video_transmitters (uuid);

ALTER TABLE builds
ADD CONSTRAINT fk_builds_gps_receiver_uuid FOREIGN KEY (gps_receiver_uuid) REFERENCES gps_receivers (uuid);

ALTER TABLE flight_controllers
ADD CONSTRAINT fk_flight_controllers_internal_electronic_speed_controller_uuid FOREIGN KEY (internal_electronic_speed_controller_uuid) REFERENCES electronic_speed_controllers (uuid);

ALTER TABLE flight_controllers
ADD CONSTRAINT fk_flight_controllers_internal_receiver_uuid FOREIGN KEY (internal_receiver_uuid) REFERENCES receivers (uuid);

ALTER TABLE flight_controllers
ADD CONSTRAINT fk_flight_controllers_internal_video_transmitter_uuid FOREIGN KEY (internal_video_transmitter_uuid) REFERENCES video_transmitters (uuid);
