syntax = "proto3";

package quadsmith.v1;

import "google/protobuf/field_mask.proto";
import "quadsmith/v1/common.proto";
import "quadsmith/v1/component.proto";

message ChangeRequest {
  string id = 1;
  string user_id = 2;
  optional string component_id = 3; // Null if proposing a brand new component
  ComponentType target_type = 4;
  EditAction action = 5;
  Component proposed_component = 6;
  google.protobuf.FieldMask update_mask = 7; // Precise fields changed for updates
  optional string rationale = 8;
  ChangeStatus status = 9;
  optional string merged_into_id = 10;
  int64 created_at_unix_ms = 11;
  int64 updated_at_unix_ms = 12;
}

message ChangeRequestVote {
  string id = 1;
  string request_id = 2;
  string user_id = 3;
  bool is_upvote = 4;
  int64 created_at_unix_ms = 5;
}
