syntax = "proto3";

package quadsmith.v1;

enum SoftwareFlavorType {
  SOFTWARE_FLAVOR_TYPE_UNSPECIFIED = 0;
  SOFTWARE_FLAVOR_TYPE_FC_FIRMWARE = 1;
  SOFTWARE_FLAVOR_TYPE_ESC_FIRMWARE = 2;
  SOFTWARE_FLAVOR_TYPE_VTX_FIRMWARE = 3;
  SOFTWARE_FLAVOR_TYPE_OPERATING_SYSTEM = 4;
}

message SoftwareComponentProfile {
  string software_id = 1; // References parent Software entity (e.g. Betaflight)
  string version = 2;     // e.g. "4.4.2"
  optional string flavor_target = 3; // e.g. "STM32F405"
  SoftwareFlavorType flavor_type = 4;
  repeated string compatible_hardware_ids = 5;
}
