escs: {
  uuid: "59b0e835-da96-4143-9674-dc6a950ac7c7"
  id: "redfox-a3-f722-45a-aio"
  manufacturer: "Redfox"
  name: "Redfox A3 F722 45A AIO"
  weight_g: 8.7
  max_motors: 4
  continuous_amps: 45
  burst_amps: 55
  firmware: "BLHeli_32"
}
escs: {
  uuid: "5a5be012-c0c3-4986-99dd-97a7317148ce"
  id: "caddxf4-aio-20a"
  manufacturer: "CaddxF4"
  name: "CaddxF4 AIO 20A"
  weight_g: 5.3
  max_motors: 4
  continuous_amps: 20
  burst_amps: 25
  firmware: "BLHeli_32"
}
escs: {
  uuid: "043313ce-9ddb-47df-b915-56a28855f49e"
  id: "happymodel-x12-5-in-1-aio"
  manufacturer: "Happymodel"
  name: "Happymodel X12 5-IN-1 AIO"
  weight_g: 5.1
  max_motors: 4
  continuous_amps: 12
  burst_amps: 15
  firmware: "BLHeli_32"
}
escs: {
  uuid: "41135f85-6b65-4ccd-a019-9d9bd1973294"
  id: "betafpv-f4-1s-5a-aio"
  manufacturer: "BetaFPV"
  name: "BetaFPV F4 1S 5A AIO"
  weight_g: 2.96
  max_motors: 4
  continuous_amps: 5
  burst_amps: 6
  firmware: "BLHeli_32"
}
escs: {
  uuid: "19578f9c-b43e-4323-b6ee-8af447a274f4"
  id: "hglrc-zeus-48a"
  manufacturer: "HGLRC"
  name: "HGLRC Zeus 48A"
  weight_g: 18.3
  max_motors: 4
  continuous_amps: 48
  burst_amps: 55
  firmware: "BLHeli_32"
}
escs: {
  uuid: "0ceda915-f01c-4b27-bc8c-e01c22e58d2a"
  id: "hglrc-specter-60a-4-in-1-esc"
  manufacturer: "HGLRC"
  name: "HGLRC Specter 60A 4-in-1 ESC"
  weight_g: 19.5
  max_motors: 4
  continuous_amps: 60
  burst_amps: 65
  firmware: "BLHeli_32"
}
escs { uuid: "dcc61f92-5b46-4bbb-89c9-d5975c9c4c16" id: "matrix-1s-brushless-flight-controller-3in1-4in1" manufacturer: "BETAFPV" name: "Matrix 1S Brushless Flight Controller (3IN1/4IN1)" weight_g: 3.8 continuous_amps: 18 }
escs { uuid: "b25dc45e-1548-4215-8de5-7f5a32e341eb" id: "f4-brushless-flight-controller-and-esc-blheli-32" manufacturer: "BETAFPV" name: "F4 Brushless Flight Controller and ESC (BLHeli_32)" weight_g: 2.7 continuous_amps: 16 }
escs { uuid: "e77b139d-8def-4796-81d4-3cefc2d840d2" id: "f4-brushless-flight-controller-and-esc-v2-0-blheli-32" manufacturer: "BETAFPV" name: "F4 Brushless Flight Controller and ESC V2.0 (BLHeli_32)" weight_g: 4.2 continuous_amps: 16 }
escs { uuid: "c3f15498-dda4-4cd8-8b45-8e2ea29a269a" id: "beta75x-whoop-quadcopter-2s-12a-esc" manufacturer: "BETAFPV" name: "Beta75X Whoop Quadcopter (2S 12A ESC)" weight_g: 41.0 continuous_amps: 12 }
escs { uuid: "5b37f9b4-9eb2-4f43-bdc0-edbf827e1608" id: "beta75x-2s-whoop-quadcopter-6a-esc" manufacturer: "BETAFPV" name: "Beta75X 2S Whoop Quadcopter (6A ESC)" weight_g: 41.0 continuous_amps: 2 }
escs { uuid: "35e1e308-5ace-451b-b573-a93c5d2899ee" id: "f3-brushless-1s-flight-controller-esc-osd" manufacturer: "BETAFPV" name: "F3 Brushless 1S Flight Controller (ESC + OSD)" weight_g: 3.2 continuous_amps: 0 }
escs { uuid: "e139857a-59f5-4df8-bee1-f6736c521d47" id: "darwinfpv-cement-ultra-durable-blheli-32-am32-12s-8s-80a-waterproof-esc" manufacturer: "DarwinFPV - Official Store" name: "DarwinFPV 'Cement' Ultra-Durable BLHeli_32 AM32 12S 8S 80A Waterproof  ESC" weight_g: 0.0 continuous_amps: 32 }
escs { uuid: "ad0b6f98-4c7b-48a4-861d-757afe7f1b93" id: "darwinfpv-3-6s-f411-fc-4-in-1-30a-esc-stack" manufacturer: "DarwinFPV" name: "DarwinFPV 3-6S F411 FC 4 IN 1 30A ESC Stack" weight_g: 0.0 continuous_amps: 30 }
escs { uuid: "11c49b81-907d-49e0-b9ab-9f6285f405c0" id: "darwinfpv-betaflight-f4-fc-50a-dshot600-esc-stack" manufacturer: "DarwinFPV" name: "DarwinFPV Betaflight F4 FC 50A  DSHOT600 ESC Stack" weight_g: 10.8 continuous_amps: 50 }
escs { uuid: "71200654-3789-4592-934f-81336be485f8" id: "darwinfpv-fpv-esc-flight-controller-betaflight-f4-fc-30a-2-6s-blheli-32-4in1-dshot1200" manufacturer: "DarwinFPV" name: "DarwinFPV fpv ESC flight controller Betaflight F4 FC 30A 2-6S BLHeli_32 4in1 Dshot1200" weight_g: 5.1 continuous_amps: 30 }
escs { uuid: "2348ba8f-9576-44b0-9620-c28786da9a42" id: "newbeedrone-infinity200-v2-4in1-esc-55a" manufacturer: "NewBeeDrone" name: "NewBeeDrone Infinity200 V2 4IN1 ESC 55A" weight_g: 0.0 continuous_amps: 55 }
escs { uuid: "8b439f1d-ed5c-4cca-ae13-d20dcc372815" id: "lucid-90a-12s-am32-esc-ndaa" manufacturer: "Team Black Sheep" name: "Lucid 90A 12S AM32 ESC - NDAA" weight_g: 19.0 continuous_amps: 90 }
escs { uuid: "a31cfe82-973b-4ee5-accf-752843308665" id: "goku-gn745-v3-2-6s-25x25-aio-flight-controller-with-45a-32bit-esc-am32" manufacturer: "Flywoo" name: "Goku GN745 V3 2-6S 25x25 AIO Flight Controller with 45A 32bit ESC - AM32" weight_g: 9.4 continuous_amps: 25 }
escs { uuid: "ec186492-b783-4e46-82c3-71bc03893df1" id: "fettec-sfoc-50a-2-8s-20x20-4in1-esc" manufacturer: "FETtec" name: "FETtec SFOC 50A 2-8S 20x20 4in1 ESC" weight_g: 10.0 continuous_amps: 50 }
escs { uuid: "48761253-4708-4e98-b314-b0f4c48e711a" id: "goku-f405-hd-v2-1-2s-25x25-aio-flight-controller-with-12a-8bit-esc-elrs" manufacturer: "Flywoo" name: "Goku F405 HD V2 1-2S 25x25 AIO Flight Controller with 12A 8Bit ESC & ELRS" weight_g: 4.9 continuous_amps: 25 }
escs { uuid: "af59dfa0-30ee-4489-9865-9c3a2b1aebab" id: "kakute-g4-25x25-aio-flight-controller-with-35a-32bit-am32-esc" manufacturer: "Holybro" name: "Kakute G4 25x25 AIO Flight Controller with 35A 32Bit AM32 ESC" weight_g: 0.0 continuous_amps: 25 }
escs { uuid: "9fb974ba-e373-4086-84de-97a3d5423cce" id: "zorro-edgetx-radio-controller-4in1-or-elrs" manufacturer: "RadioMaster" name: "Zorro EdgeTX Radio Controller - 4in1 or ELRS" weight_g: 350.0 continuous_amps: 0 }
escs { uuid: "118bb614-d98a-4305-bba4-e1a35ea6439f" id: "matrix-1s-brushless-flight-controller-3in1-4in1" manufacturer: "BETAFPV" name: "Matrix 1S Brushless Flight Controller (3IN1/4IN1)" weight_g: 3.8 continuous_amps: 18 }
escs { uuid: "50ccf301-c495-4b11-8371-5d0983a7c347" id: "f4-brushless-flight-controller-and-esc-blheli-32" manufacturer: "BETAFPV" name: "F4 Brushless Flight Controller and ESC (BLHeli_32)" weight_g: 2.7 continuous_amps: 16 }
escs { uuid: "2d965066-76d8-428e-baaa-33719c6a52e8" id: "f4-brushless-flight-controller-and-esc-v2-0-blheli-32" manufacturer: "BETAFPV" name: "F4 Brushless Flight Controller and ESC V2.0 (BLHeli_32)" weight_g: 4.2 continuous_amps: 16 }
escs { uuid: "4cfd7e74-1b5b-4dd5-8fa5-d43a32ac2944" id: "beta75x-whoop-quadcopter-2s-12a-esc" manufacturer: "BETAFPV" name: "Beta75X Whoop Quadcopter (2S 12A ESC)" weight_g: 41.0 continuous_amps: 12 }
escs { uuid: "c9d3bd3e-7edc-445d-82f5-9adcc6ba0466" id: "beta75x-2s-whoop-quadcopter-6a-esc" manufacturer: "BETAFPV" name: "Beta75X 2S Whoop Quadcopter (6A ESC)" weight_g: 41.0 continuous_amps: 2 }
escs { uuid: "2c47b433-6917-4fd9-bf1a-e61ab7b75ab6" id: "f3-brushless-1s-flight-controller-esc-osd" manufacturer: "BETAFPV" name: "F3 Brushless 1S Flight Controller (ESC + OSD)" weight_g: 3.2 continuous_amps: 0 }
escs { uuid: "b82bef05-ee5f-4359-805c-e51225bb35ae" id: "darwinfpv-cement-ultra-durable-blheli-32-am32-12s-8s-80a-waterproof-esc" manufacturer: "DarwinFPV - Official Store" name: "DarwinFPV 'Cement' Ultra-Durable BLHeli_32 AM32 12S 8S 80A Waterproof  ESC" weight_g: 0.0 continuous_amps: 32 }
escs { uuid: "c6430d4f-02d8-4c98-8df5-1f1d99b99431" id: "darwinfpv-3-6s-f411-fc-4-in-1-30a-esc-stack" manufacturer: "DarwinFPV" name: "DarwinFPV 3-6S F411 FC 4 IN 1 30A ESC Stack" weight_g: 0.0 continuous_amps: 30 }
escs { uuid: "a1984caf-6bad-4eb9-bc91-cf6ac6c9cb96" id: "darwinfpv-24-in-1-multifunctional-precision-magnetic-bits-screws-kit" manufacturer: "DarwinFPV" name: "DarwinFPV 24 in 1 Multifunctional Precision Magnetic Bits Screws Kit" weight_g: 0.0 continuous_amps: 0 }
escs { uuid: "288ea4d0-6fba-475d-9ae9-7c82ef8a9553" id: "darwinfpv-betaflight-f4-fc-50a-dshot600-esc-stack" manufacturer: "DarwinFPV" name: "DarwinFPV Betaflight F4 FC 50A  DSHOT600 ESC Stack" weight_g: 10.8 continuous_amps: 50 }
escs { uuid: "72b993ab-f65e-4cdc-ac89-a3e7ecc2f4bb" id: "darwinfpv-fpv-esc-flight-controller-betaflight-f4-fc-30a-2-6s-blheli-32-4in1-dshot1200" manufacturer: "DarwinFPV" name: "DarwinFPV fpv ESC flight controller Betaflight F4 FC 30A 2-6S BLHeli_32 4in1 Dshot1200" weight_g: 5.1 continuous_amps: 30 }
escs { uuid: "f262f2c1-feff-4f1a-b02a-cf3e9a8098d3" id: "newbeedrone-infinity200-v2-4in1-esc-55a" manufacturer: "NewBeeDrone" name: "NewBeeDrone Infinity200 V2 4IN1 ESC 55A" weight_g: 0.0 continuous_amps: 55 }
escs { uuid: "c19fc71b-8a65-4635-a180-532cbced740e" id: "lucid-90a-12s-am32-esc-ndaa" manufacturer: "Team Black Sheep" name: "Lucid 90A 12S AM32 ESC - NDAA" weight_g: 19.0 continuous_amps: 90 }
escs { uuid: "a576a979-49ee-4805-9570-6537138aa9be" id: "goku-gn745-v3-2-6s-25x25-aio-flight-controller-with-45a-32bit-esc-am32" manufacturer: "Flywoo" name: "Goku GN745 V3 2-6S 25x25 AIO Flight Controller with 45A 32bit ESC - AM32" weight_g: 9.4 continuous_amps: 25 }
escs { uuid: "2f840235-6d5b-4c9b-82eb-08282fd2e12c" id: "fettec-sfoc-50a-2-8s-20x20-4in1-esc" manufacturer: "FETtec" name: "FETtec SFOC 50A 2-8S 20x20 4in1 ESC" weight_g: 10.0 continuous_amps: 50 }
escs { uuid: "5eca6f1c-6387-4bab-8200-a60c04e596b6" id: "goku-f405-hd-v2-1-2s-25x25-aio-flight-controller-with-12a-8bit-esc-elrs" manufacturer: "Flywoo" name: "Goku F405 HD V2 1-2S 25x25 AIO Flight Controller with 12A 8Bit ESC & ELRS" weight_g: 4.9 continuous_amps: 25 }
escs { uuid: "0c8987d1-2057-4227-a133-f22e1043ed90" id: "kakute-g4-25x25-aio-flight-controller-with-35a-32bit-am32-esc" manufacturer: "Holybro" name: "Kakute G4 25x25 AIO Flight Controller with 35A 32Bit AM32 ESC" weight_g: 0.0 continuous_amps: 25 }
escs { uuid: "991a1f10-d030-4430-aa62-8a94112f65df" id: "zorro-edgetx-radio-controller-4in1-or-elrs" manufacturer: "RadioMaster" name: "Zorro EdgeTX Radio Controller - 4in1 or ELRS" weight_g: 350.0 continuous_amps: 0 }
escs { uuid: "f241933f-20d1-464a-b111-93f4798b9174" id: "matrix-1s-brushless-flight-controller-3in1-4in1" manufacturer: "BETAFPV" name: "Matrix 1S Brushless Flight Controller (3IN1/4IN1)" weight_g: 3.8 continuous_amps: 18 }
escs { uuid: "fd136a2c-7ef0-4441-93d7-e4ca113ad798" id: "f4-brushless-flight-controller-and-esc-blheli-32" manufacturer: "BETAFPV" name: "F4 Brushless Flight Controller and ESC (BLHeli_32)" weight_g: 2.7 continuous_amps: 16 }
escs { uuid: "aa526c6b-e550-4064-b29a-66594a8b0e21" id: "f4-brushless-flight-controller-and-esc-v2-0-blheli-32" manufacturer: "BETAFPV" name: "F4 Brushless Flight Controller and ESC V2.0 (BLHeli_32)" weight_g: 4.2 continuous_amps: 16 }
escs { uuid: "0690d3bf-1ea7-4277-9817-158410dc6d99" id: "beta75x-whoop-quadcopter-2s-12a-esc" manufacturer: "BETAFPV" name: "Beta75X Whoop Quadcopter (2S 12A ESC)" weight_g: 41.0 continuous_amps: 12 }
escs { uuid: "b12eb2d6-7ac5-4373-9574-99271c079019" id: "beta75x-2s-whoop-quadcopter-6a-esc" manufacturer: "BETAFPV" name: "Beta75X 2S Whoop Quadcopter (6A ESC)" weight_g: 41.0 continuous_amps: 2 }
escs { uuid: "6a15b8ca-1741-4af9-a590-41500c645c71" id: "f3-brushless-1s-flight-controller-esc-osd" manufacturer: "BETAFPV" name: "F3 Brushless 1S Flight Controller (ESC + OSD)" weight_g: 3.2 continuous_amps: 0 }
escs { uuid: "4d317bef-27a5-4e24-889b-6822a0579cef" id: "darwinfpv-cement-ultra-durable-blheli-32-am32-12s-8s-80a-waterproof-esc" manufacturer: "DarwinFPV - Official Store" name: "DarwinFPV 'Cement' Ultra-Durable BLHeli_32 AM32 12S 8S 80A Waterproof  ESC" weight_g: 0.0 continuous_amps: 32 }
escs { uuid: "a9bf3117-aca3-414a-b3a7-1420f673917a" id: "darwinfpv-3-6s-f411-fc-4-in-1-30a-esc-stack" manufacturer: "DarwinFPV" name: "DarwinFPV 3-6S F411 FC 4 IN 1 30A ESC Stack" weight_g: 0.0 continuous_amps: 30 }
escs { uuid: "8fcd0c7a-6a94-4f3b-af52-e4a39c30ad5c" id: "darwinfpv-24-in-1-multifunctional-precision-magnetic-bits-screws-kit" manufacturer: "DarwinFPV" name: "DarwinFPV 24 in 1 Multifunctional Precision Magnetic Bits Screws Kit" weight_g: 0.0 continuous_amps: 0 }
escs { uuid: "618c9e19-0360-4e46-867d-a4317ea8bc8d" id: "darwinfpv-betaflight-f4-fc-50a-dshot600-esc-stack" manufacturer: "DarwinFPV" name: "DarwinFPV Betaflight F4 FC 50A  DSHOT600 ESC Stack" weight_g: 10.8 continuous_amps: 50 }
escs { uuid: "b9a3fe9b-ff4d-4b3e-9ad7-d48940767931" id: "darwinfpv-fpv-esc-flight-controller-betaflight-f4-fc-30a-2-6s-blheli-32-4in1-dshot1200" manufacturer: "DarwinFPV" name: "DarwinFPV fpv ESC flight controller Betaflight F4 FC 30A 2-6S BLHeli_32 4in1 Dshot1200" weight_g: 5.1 continuous_amps: 30 }
escs { uuid: "72057c93-2c8c-42e9-9dfc-2eae2d67cb97" id: "newbeedrone-infinity200-v2-4in1-esc-55a" manufacturer: "NewBeeDrone" name: "NewBeeDrone Infinity200 V2 4IN1 ESC 55A" weight_g: 0.0 continuous_amps: 55 }
escs { uuid: "194e50f5-1b07-4cfd-a27a-80b43e74f480" id: "lucid-90a-12s-am32-esc-ndaa" manufacturer: "Team Black Sheep" name: "Lucid 90A 12S AM32 ESC - NDAA" weight_g: 19.0 continuous_amps: 90 }
escs { uuid: "85a0132c-32f6-43ca-af76-f5540ec93944" id: "goku-gn745-v3-2-6s-25x25-aio-flight-controller-with-45a-32bit-esc-am32" manufacturer: "Flywoo" name: "Goku GN745 V3 2-6S 25x25 AIO Flight Controller with 45A 32bit ESC - AM32" weight_g: 9.4 continuous_amps: 25 }
escs { uuid: "19323054-2295-4da6-b9ca-b304482c4953" id: "fettec-sfoc-50a-2-8s-20x20-4in1-esc" manufacturer: "FETtec" name: "FETtec SFOC 50A 2-8S 20x20 4in1 ESC" weight_g: 10.0 continuous_amps: 50 }
escs { uuid: "54d4deb7-3f9e-4446-bca4-d1de3405b695" id: "goku-f405-hd-v2-1-2s-25x25-aio-flight-controller-with-12a-8bit-esc-elrs" manufacturer: "Flywoo" name: "Goku F405 HD V2 1-2S 25x25 AIO Flight Controller with 12A 8Bit ESC & ELRS" weight_g: 4.9 continuous_amps: 25 }
escs { uuid: "89f4edb7-6d1c-40d2-9d0d-0c7ab3c773c1" id: "kakute-g4-25x25-aio-flight-controller-with-35a-32bit-am32-esc" manufacturer: "Holybro" name: "Kakute G4 25x25 AIO Flight Controller with 35A 32Bit AM32 ESC" weight_g: 0.0 continuous_amps: 25 }
escs { uuid: "2d456c7c-dcb5-48c9-b65a-fa912ddd0d53" id: "zorro-edgetx-radio-controller-4in1-or-elrs" manufacturer: "RadioMaster" name: "Zorro EdgeTX Radio Controller - 4in1 or ELRS" weight_g: 350.0 continuous_amps: 0 }
escs { uuid: "a1c0e659-bff7-4508-8849-25120750e255" id: "hglrc-specter-60a-4in1-esc-3-6s-bl32-128k-with-heat-sink-for-fpv-racing-drone-freestyle" manufacturer: "HGLRC" name: "HGLRC SPECTER 60A 4in1 ESC 3-6S BL32 128K with Heat Sink for FPV Racing Drone Freestyle" weight_g: 19.5 continuous_amps: 60 }
escs { uuid: "2cc3c66a-d9d5-42ce-89ff-68c80560f139" id: "hglrc-60a-4in1-6s-bl32-mini-v1-esc-fpv-drone" manufacturer: "HGLRC" name: "HGLRC 60A 4IN1 6S BL32 MINI V1 ESC FPV Drone" weight_g: 0.0 continuous_amps: 60 }
escs { uuid: "dd2e76bf-c831-484a-8267-b9cd65a33787" id: "hglrc-60a-4in1-6s-8-bit-v2-esc-for-fpv-racing-drone" manufacturer: "HGLRC" name: "HGLRC 60A 4IN1 6S 8-bit V2 ESC For FPV Racing Drone" weight_g: 0.0 continuous_amps: 60 }
escs { uuid: "aafe496c-9d6a-4611-8919-8f4818a58db4" id: "hglrc-60a-4in1-mini-8s-32-bit-v1-esc-for-racing" manufacturer: "HGLRC" name: "HGLRC 60A 4IN1 MINI 8S 32-bit V1 ESC for racing" weight_g: 14.0 continuous_amps: 60 }
escs { uuid: "c2c3e035-cd09-4a92-9698-dbf520caf0e1" id: "hglrc-h743-8s-mini-v1-fc-60a-4in1-6s-bls-mini-esc" manufacturer: "HGLRC" name: "HGLRC H743 8S MINI V1 FC 60A 4IN1 6S BLS MINI ESC" weight_g: 6.8 continuous_amps: 60 }
escs { uuid: "f031b987-5640-4bd2-807b-40b4aabfd409" id: "hglrc-specter-90a-single-esc-high-performance-professional-esc-distribution-board" manufacturer: "HGLRC" name: "HGLRC SPECTER 90A single ESC High-performance professional ESC & distribution board" weight_g: 13.9 continuous_amps: 90 }
escs { uuid: "06193206-1745-4bb7-bce6-7b44b134c21e" id: "mamba-f100-blheli-32-am32-esc-8s" manufacturer: "DIATONE OFFICIAL" name: "MAMBA F100 BLHeli 32/AM32 ESC 8S" weight_g: 36.0 continuous_amps: 100 }
escs { uuid: "976f1132-68c4-47b9-8805-0ced16ade9dd" id: "mamba-f80-blheli-32-am32-esc-8s" manufacturer: "DIATONE OFFICIAL" name: "MAMBA F80 BLHeli 32 / AM32  ESC 8S" weight_g: 29.0 continuous_amps: 80 }
escs { uuid: "8b6a56c8-b3dd-4ad1-9827-fbf22ada7552" id: "diatone-esc-power-distribution-board-3-6s-for-rc-drone-fpv-racing" manufacturer: "DIATONE INNOVATIONS" name: "DIATONE ESC Power Distribution Board 3-6S for RC Drone FPV Racing" weight_g: 0.0 continuous_amps: 40 }
escs { uuid: "d6c7bf13-64f8-4ebe-aedc-b0a3fcc03c62" id: "mamba5-5-reactor-44-esc-blheli32-4in1-esc-44a-6s" manufacturer: "DIATONE OFFICIAL" name: "MAMBA5  5 Reactor 44 ESC BLHeli32 4IN1 ESC 44A 6S" weight_g: 0.0 continuous_amps: 44 }
escs { uuid: "80ad30eb-5d97-457a-b0de-89f1367c0bc5" id: "mamba-5-reactor-66-esc-blheli32-4in1-esc-66a-6s" manufacturer: "DIATONE OFFICIAL" name: "MAMBA 5 Reactor 66 ESC BLHeli32 4IN1 ESC 66A 6S" weight_g: 0.0 continuous_amps: 66 }
escs { uuid: "7a5383ec-7071-4ab3-8b32-bf801d77ba15" id: "mamba-f55-128k-am32-4in1-esc-55a-6s" manufacturer: "DIATONE INNOVATIONS" name: "MAMBA F55_128K AM32 4IN1 ESC 55A 6S" weight_g: 0.0 continuous_amps: 55 }
escs { uuid: "9e340938-4b61-42ef-acf2-6dc7b6c13004" id: "mamba-f65-128k-am32-4in1-esc-65a-6s" manufacturer: "DIATONE INNOVATIONS" name: "MAMBA  F65_128K AM32 4IN1 ESC 65A 6S" weight_g: 0.0 continuous_amps: 65 }
escs { uuid: "bda5a283-0aaf-46b1-acfe-f649f4e286c2" id: "mamba-f40-128k-am32-mini-4in1-esc-40a-6s" manufacturer: "DIATONE INNOVATIONS" name: "MAMBA  F40_128K AM32 MINI 4IN1 ESC 40A 6S" weight_g: 0.0 continuous_amps: 40 }
escs { uuid: "9b644d3c-26f4-4a20-ab2f-c30d8e91b28e" id: "mamba-f55-bls-dshot600-4in1-esc-55a-6s" manufacturer: "DIATONE INNOVATIONS" name: "MAMBA F55_BLS Dshot600 4IN1 ESC 55A 6S" weight_g: 0.0 continuous_amps: 55 }
escs { uuid: "ba0ca663-78b6-4107-a2a8-b4b74a3a98c8" id: "mamba-f40-bls-dshot600-4in1-esc-40a-6s" manufacturer: "DIATONE INNOVATIONS" name: "MAMBA F40_BLS Dshot600 4IN1 ESC 40A 6S" weight_g: 0.0 continuous_amps: 40 }
escs { uuid: "95ca2c75-f836-4cba-b0af-ac9aacaeaf37" id: "redfox-a1-f4-5a-4in1-1s-aio-fc-with-a30-power-able-for-whoopfly16-nanofly16-and-nanofly20" manufacturer: "Sub250" name: "Redfox A1 F4 5A 4in1 1S AIO FC with A30 Power able for Whoopfly16/ Nanofly16 and Nanofly20" weight_g: 0.0 continuous_amps: 16 }
escs { uuid: "16189d90-32b6-46ac-b36b-594e40f14645" id: "fpvcycle-darwinfpv-whoop-stack-flight-controller-6s-45a-esc" manufacturer: "FPVCycle" name: "FPVCycle DarwinFPV Whoop Stack Flight Controller + 6S 45A ESC" weight_g: 0.0 continuous_amps: 45 }
