receivers: {
  uuid: "b0cf2152-68ff-41ac-9bc5-c7b6d34f2543"
  id: "tbs-crossfire-nano-rx"
  manufacturer: "TBS"
  name: "TBS Crossfire Nano RX"
  weight_g: 0.5
  protocol: "TBS Crossfire (CRSF)"
  frequency_band_ghz: 2.4
}
receivers: {
  uuid: "8e3b3fae-9076-400d-89c3-f93faf3aa37d"
  id: "walksnail-avatar-vrx"
  manufacturer: "Walksnail"
  name: "Walksnail Avatar VRX"
  weight_g: 83
  protocol: "HDMI"
  frequency_band_ghz: 2.4
}
receivers: {
  uuid: "632437ac-1938-4574-85eb-b9b2aeb000ff"
  id: "tbs-tracer-nano-rx"
  manufacturer: "TBS"
  name: "TBS Tracer Nano RX"
  weight_g: 0.5
  protocol: "TBS Crossfire (CRSF)"
  frequency_band_ghz: 2.4
}
receivers: {
  uuid: "42e4ac1f-d5e8-4863-9eeb-f0d8ad8eeffd"
  id: "hglrc-hermes-expresslrs-2.4ghz"
  manufacturer: "HGLRC"
  name: "HGLRC Hermes ExpressLRS 2.4GHz"
  weight_g: 0.8
  protocol: "ExpressLRS (ELRS)"
  frequency_band_ghz: 2.4
}
receivers: {
  uuid: "d1a50985-ef0b-4357-b944-7367b21e24f5"
  id: "hglrc-hermes-expresslrs-900mhz"
  manufacturer: "HGLRC"
  name: "HGLRC Hermes ExpressLRS 900MHz"
  weight_g: 0.8
  protocol: "ExpressLRS (ELRS)"
  frequency_band_ghz: 2.4
}
receivers { uuid: "34c212ef-d9b5-4bdc-8b55-be9a0836305c" id: "literadio-4-radio-transmitter" manufacturer: "BETAFPV" name: "LiteRadio 4 Radio Transmitter" weight_g: 0.0 }
receivers { uuid: "e181ef41-1ef6-4ae0-8b4f-cb3976f0dffa" id: "superx-elrs-gemini-xross-receiver" manufacturer: "BETAFPV" name: "SuperX ELRS Gemini Xross Receiver" weight_g: 0.82 }
receivers { uuid: "d850dcfd-c847-4f66-bf3a-146d2e40a48c" id: "micro-tx-v2-module" manufacturer: "BETAFPV" name: "Micro TX V2 Module" weight_g: 54.8 }
receivers { uuid: "42c78e9d-738d-427a-903c-67d36569f68e" id: "nano-tx-v2-module" manufacturer: "BETAFPV" name: "Nano TX V2 Module" weight_g: 28.0 }
receivers { uuid: "d23d5af1-0ded-4636-a349-83983cd909f3" id: "superg-nano-transmitter" manufacturer: "BETAFPV" name: "SuperG Nano Transmitter" weight_g: 44.8 }
receivers { uuid: "d015fe96-1726-419a-b54d-d808f93aa8bc" id: "superp-14ch-diversity-receiver" manufacturer: "BETAFPV" name: "SuperP 14CH Diversity Receiver" weight_g: 15.5 }
receivers { uuid: "b64baa12-789b-467f-a52a-f2d42cefa06c" id: "superd-elrs-diversity-receiver" manufacturer: "BETAFPV" name: "SuperD ELRS Diversity Receiver" weight_g: 1.1 }
receivers { uuid: "65acf466-8b6d-4657-836d-5b9b12c5394d" id: "expresslrs-recovery-dongle" manufacturer: "BETAFPV" name: "ExpressLRS Recovery Dongle" weight_g: 0.0 }
receivers { uuid: "a01023d0-16b2-47c5-aafc-cb61c282b0c2" id: "literadio-3-pro-radio-transmitter" manufacturer: "BETAFPV" name: "LiteRadio 3 Pro Radio Transmitter" weight_g: 0.0 }
receivers { uuid: "4c6df08a-008d-46bb-b474-42517b276c5c" id: "elrs-micro-receiver" manufacturer: "BETAFPV" name: "ELRS Micro Receiver" weight_g: 1.1 }
receivers { uuid: "ecd4c1b0-4f96-4199-b99e-5e30c0454471" id: "elrs-micro-tx-module-case-and-cooling-fan" manufacturer: "BETAFPV" name: "ELRS Micro TX Module Case and Cooling Fan" weight_g: 20.0 }
receivers { uuid: "41688378-336e-4eb2-8830-755e850e0832" id: "micro-nano-module-adapter" manufacturer: "BETAFPV" name: "Micro-Nano Module Adapter" weight_g: 25.0 }
receivers { uuid: "7c44ba69-5c4f-4880-be5a-3f7a48faf6ae" id: "elrs-nano-tx-module" manufacturer: "BETAFPV" name: "ELRS Nano TX Module" weight_g: 0.0 }
receivers { uuid: "24458a4e-b564-47b9-8fa8-8941748a9b99" id: "literadio-2-se-radio-transmitter" manufacturer: "BETAFPV" name: "LiteRadio 2 SE Radio Transmitter" weight_g: 0.0 }
receivers { uuid: "86f33d78-dd7a-4eca-ad18-9e7fdf5280b6" id: "x-knight-360-fpv-quadcopter" manufacturer: "BETAFPV" name: "X-Knight 360 FPV Quadcopter" weight_g: 194.4 }
receivers { uuid: "35dcf16e-18aa-4975-a1e3-aee4acf4fa14" id: "literadio-2-radio-transmitter" manufacturer: "BETAFPV" name: "LiteRadio 2 Radio Transmitter" weight_g: 227.4 }
receivers { uuid: "7f09236d-da94-4b1f-b67e-8402c532e69f" id: "pagoda-2-5-8g-fpv-antenna-2pcs" manufacturer: "BETAFPV" name: "Pagoda 2 5.8G  FPV Antenna (2PCS)" weight_g: 9.0 }
receivers { uuid: "3a485ce2-9a9c-4848-babb-99cd2251471a" id: "ac900-dual-mode-receiver-frsky-futaba" manufacturer: "BETAFPV" name: "AC900 Dual Mode Receiver (FrSky & FUTABA)" weight_g: 0.9 }
receivers { uuid: "6a220766-0b18-414c-98b3-430901bd3a8e" id: "frsky-xm-sbus-mini-receiver-repair-component" manufacturer: "BETAFPV" name: "FrSky XM+ SBUS Mini Receiver (Repair Component)" weight_g: 1.6 }
receivers { uuid: "03bc95ca-2c8c-4a8f-a08a-dd7dfe820aec" id: "flysky-rx2a-pro-receiver-for-micro-drone-upgraded" manufacturer: "BETAFPV" name: "Flysky RX2A Pro Receiver for Micro Drone(Upgraded)" weight_g: 0.88 }
receivers { uuid: "5963378e-db01-4d3c-ab2f-2622fc54b3cb" id: "dsmx-receiver-for-micro-drone" manufacturer: "BETAFPV" name: "DSMX Receiver for Micro Drone" weight_g: 0.6 }
receivers { uuid: "64ee4342-223f-4d9c-80a2-f9782d99833c" id: "betacube-for-whoop-quads" manufacturer: "BETAFPV" name: "BetaCube for Whoop Quads" weight_g: 0.0 }
receivers { uuid: "04993f61-3ffd-4180-bab2-568b9abfa53d" id: "fpv-whoop-racing-advanced-kit" manufacturer: "BETAFPV" name: "FPV Whoop Racing Advanced Kit" weight_g: 0.0 }
receivers { uuid: "219c260a-2f70-453f-9756-44862b765111" id: "caddxfpv-alink-controller" manufacturer: "CADDX FPV" name: "CaddxFPV Alink Controller" weight_g: 180.0 }
receivers { uuid: "24a84c85-1183-45ce-9f6d-ec79835e657d" id: "darwinfpv-elrs-2-4g-nano-receiver" manufacturer: "DarwinFPV - Official Store" name: "DarwinFPV  ELRS 2.4G Nano Receiver" weight_g: 0.0 }
receivers { uuid: "36432bcf-ed71-4e75-b425-b42a292ec2db" id: "darwinfpv-hulk-iii-mini-waterproof-rtf" manufacturer: "DarwinFPV - Official Store" name: "DarwinFPV HULK III Mini Waterproof RTF" weight_g: 0.0 }
receivers { uuid: "55a59bcc-4922-4f65-a8c6-ab19b63fff67" id: "darwinfpv-tx8-elrs-radio-fpv-transmitter" manufacturer: "DarwinFPV - Official Store" name: "DarwinFPV TX8 ELRS Radio FPV Transmitter" weight_g: 0.0 }
receivers { uuid: "e44bac9d-dea6-4080-92c2-b23cde78dbc6" id: "darwinfpv-x10-large-load-and-long-range-10-fpv-drone" manufacturer: "DarwinFPV" name: "DarwinFPV X10 Large Load and Long Range 10  FPV Drone" weight_g: 0.0 }
receivers { uuid: "2bfab705-3ba5-4669-96bc-fb26813a9f54" id: "darwinfpv-foldape4-4-inch-folding-long-range-rtf-kit" manufacturer: "DarwinFPV" name: "DarwinFPV FoldApe4 4 Inch Folding Long Range  RTF Kit" weight_g: 0.0 }
receivers { uuid: "269973e9-93a1-439b-b6f7-ab01a08c9f23" id: "darwinfpv-cineape35-fpv-drone-rtf" manufacturer: "DarwinFPV" name: "DarwinFPV CineApe35 FPV Drone RTF" weight_g: 0.0 }
receivers { uuid: "10b536a5-3800-41c2-818d-7523699b725a" id: "darwinfpv-x9-9-long-range-fpv-drone" manufacturer: "DarwinFPV" name: "DarwinFPV X9 9 Long Range FPV Drone" weight_g: 0.0 }
receivers { uuid: "599a0c6f-ae15-4917-b1e2-dbe3f2611e42" id: "tx12-mark-ii-elrs-radio-controller" manufacturer: "DarwinFPV" name: "TX12 Mark II  ELRS Radio Controller" weight_g: 363.0 }
receivers { uuid: "6b7aa64c-15ed-46b8-b805-088910bbc230" id: "babyape-fpv-drone-rtf" manufacturer: "DarwinFPV" name: "BabyApe Ⅱ FPV Drone RTF" weight_g: 363.0 }
receivers { uuid: "baf358b4-9e68-40d2-8be9-68f1aef2eb50" id: "darwinfpv-cineape-25-fpv-kit-rtf" manufacturer: "DarwinFPV" name: "DarwinFPV CineApe 25 FPV Kit RTF" weight_g: 0.0 }
receivers { uuid: "437be0a9-91a9-4759-b4a5-888d855e7d6f" id: "darwinfpv-tx-lite-transmitter-rx-lite-receiver" manufacturer: "DarwinFPV" name: "DarwinFPV TX-Lite Transmitter+ RX-Lite Receiver" weight_g: 9.0 }
receivers { uuid: "2d9f870d-0090-4952-90da-44f3ac1fe771" id: "radiomaster-zorro-elrs-radio-controller" manufacturer: "DarwinFPV" name: "Radiomaster Zorro ELRS Radio Controller" weight_g: 0.0 }
receivers { uuid: "d48defd1-3337-4219-9312-714094110990" id: "bayckrc-elrs-2-4g-nano-receiver" manufacturer: "DarwinFPV" name: "BAYCKRC ELRS 2.4G Nano Receiver" weight_g: 0.4 }
receivers { uuid: "24508332-1e8f-4961-8343-988df4a1e4ba" id: "darwinfpv-baby-ape-v4-pro-fpv-rtf" manufacturer: "DarwinFPV" name: "DarwinFPV Baby Ape V4 Pro FPV RTF" weight_g: 0.0 }
receivers { uuid: "c8c6c7c6-d9da-43df-b119-b3e8e79c9a23" id: "darwinfpv-radiomaster-r81-receiver" manufacturer: "DarwinFPV" name: "DarwinFPV Radiomaster R81 Receiver" weight_g: 2.0 }
receivers { uuid: "d9d4a061-bc17-4667-9a51-737ccd55dd65" id: "darwin-vantac-elrs-2-4g-lite-tx-module" manufacturer: "DarwinFPV" name: "Darwin Vantac ELRS 2.4G Lite TX Module" weight_g: 0.0 }
receivers { uuid: "57561fe9-073a-48d6-8c19-ac9f48c80f6b" id: "darwin-240-johnny-5-quadcopters" manufacturer: "DarwinFPV" name: "Darwin 240 Johnny 5 Quadcopters" weight_g: 0.0 }
receivers { uuid: "b2b5b4ce-1edd-4be7-8c45-513616e93c3d" id: "hummingbird-v4-1-complete-fly-repair-bundle" manufacturer: "NewBeeDrone" name: "Hummingbird V4.1 Complete Fly & Repair Bundle" weight_g: 0.0 }
receivers { uuid: "8d377609-f1ce-4a68-8f93-fa1aa205277c" id: "newbeedrone-beet-antenna-60mm-75mm-90mm-for-elrs-2-4ghz-receiver-u-fl-connector" manufacturer: "NewBeeDrone" name: "NewBeeDrone BeeT-Antenna 60mm/75mm/90mm for ELRS 2.4GHz Receiver - U.FL Connector" weight_g: 0.0 }
receivers { uuid: "a4cdf676-e378-40b0-a24f-64d45e1b0b16" id: "newbeedrone-x-hummingbird-v3-1-brushless-rtf-bundle-kit" manufacturer: "NewBeeDrone" name: "NewBeeDrone x Hummingbird V3.1 Brushless RTF Bundle Kit" weight_g: 0.0 }
receivers { uuid: "31ec4b14-a76c-4cad-adfb-34d0f3910bdd" id: "newbeedrone-beet-antenna-for-expresslrs-elrs-2-4ghz-receiver-mhf3-connector" manufacturer: "NewBeeDrone" name: "NewBeeDrone BeeT-Antenna for  ExpressLRS(ELRS) 2.4GHz receiver MHF3 Connector" weight_g: 0.0 }
receivers { uuid: "2451cb66-17dd-43cc-92ad-e3367e366a74" id: "newbeedrone-acrobee75-blv5-bnf-elrs2-4g-2s-the-ultimate-outdoor-whoop" manufacturer: "NewBeeDrone" name: "NewBeeDrone AcroBee75 BLV5 BNF ELRS2.4G 2S - The Ultimate Outdoor Whoop" weight_g: 36.4 }
receivers { uuid: "4debc895-b56c-4150-b203-3d1adb3704a6" id: "newbeedrone-beeceiver-elrs-2-4ghz-diversity-with-tcxo-oscillator-micro-receiver" manufacturer: "NewBeeDrone" name: "NewBeeDrone BeeCeiver ELRS 2.4Ghz Diversity with TCXO Oscillator Micro Receiver" weight_g: 1.6 }
receivers { uuid: "10fd1f19-79b1-4f83-9188-8f09d2c8b142" id: "newbeedrone-beebrainbl-hummingbird-receiver-connector-type-mhf3-pack-of-4" manufacturer: "NewBeeDrone" name: "NewBeeDrone BeeBrainBL/Hummingbird Receiver Connector Type:MHF3 (pack of 4)" weight_g: 0.0 }
receivers { uuid: "6cdc90b8-8250-4c04-bf78-2d503af75025" id: "newbeedrone-beet-antenna-for-expresslrs-elrs-2-4ghz-receiver-mhf3-connector-blv4" manufacturer: "NewBeeDrone" name: "NewBeeDrone BeeT-Antenna for  ExpressLRS(ELRS) 2.4GHz receiver MHF3 Connector /BLV4" weight_g: 0.0 }
receivers { uuid: "43d5cead-0382-4209-9085-68d1a44e334a" id: "newbeedrone-2-4g-replacement-receiver-antennas-60mm-for-beebrain-blv3-blv4-hmb-f4-v2" manufacturer: "NewBeeDrone" name: "NewBeeDrone 2.4G Replacement Receiver Antennas 60mm for BeeBrain BLV3/BLV4/HMB F4 V2" weight_g: 0.0 }
receivers { uuid: "99dcbfc7-949f-4c42-993d-73057dfbca62" id: "newbeedrone-vim-v2-replacement-parts" manufacturer: "NewBeeDrone" name: "NewBeeDrone VIM V2 Replacement Parts" weight_g: 0.0 }
receivers { uuid: "dd71c2d6-a10b-4711-8cd3-ebfcce8303a1" id: "hdo-analog-fpv-goggles-ndaa" manufacturer: "Fat Shark" name: "HDO+ Analog FPV Goggles - NDAA" weight_g: 235.8 }
receivers { uuid: "7aa5b5d3-1e7a-42af-8337-17848b6a50a1" id: "cinemini-2-5-3d-prints-bundle-dji-o4" manufacturer: "Rotor Riot" name: "CineMini 2.5 3D Prints Bundle - DJI O4" weight_g: 0.0 }
receivers { uuid: "054a71f6-2837-4ac8-a22c-2213938973ea" id: "futaba-r7208sb-fasstest-bi-directional-communication-system-s-bus-s-bus2-port-and-8-channels-receiver" manufacturer: "Futaba" name: "Futaba R7208SB – FASSTest Bi-Directional Communication System S.Bus/S.Bus2 Port and 8 Channels Receiver" weight_g: 12.0 }
receivers { uuid: "6d10de28-6421-4908-9080-54db599b6ba4" id: "tanq-2-6s-5-pro-spec-by-let-sflyrc-built-tuned-drone-dji-o4-pro-elrs" manufacturer: "Rotor Riot Builds" name: "Tanq 2 6S 5 Pro-Spec by Let'sFlyRC Built & Tuned Drone - DJI O4 Pro / ELRS" weight_g: 0.0 }
receivers { uuid: "8daa9d8b-15fb-4ec8-bc6f-cf9e597181b9" id: "fat-shark-recon-hd-goggle-bundle" manufacturer: "Rotor Riot Store" name: "Fat Shark Recon HD Goggle Bundle" weight_g: 46.22 }
receivers { uuid: "7930c6bf-7fc9-432a-af07-45fb44e589b7" id: "pocket-radio-controller-fat-shark-edition-elrs" manufacturer: "RadioMaster" name: "Pocket Radio Controller (Fat Shark Edition) - ELRS" weight_g: 288.0 }
receivers { uuid: "d209428a-8e76-4c36-b5b8-dea0871d0e6e" id: "vision40-2s-40mm-built-tuned-drone-dji-o4-dji" manufacturer: "Rotor Riot Builds" name: "Vision40 2S 40mm Built & Tuned Drone - DJI O4 / DJI" weight_g: 0.0 }
receivers { uuid: "3738bbfc-2d5f-428b-9d00-b815818ec63b" id: "tx15-radio-controller-expresslrs" manufacturer: "RadioMaster" name: "TX15 Radio Controller ExpressLRS" weight_g: 605.0 }
receivers { uuid: "59f29e5f-e708-4098-8784-c1bf5ee6ca63" id: "tx15-max-radio-controller-expresslrs" manufacturer: "RadioMaster" name: "TX15 Max Radio Controller ExpressLRS" weight_g: 672.0 }
receivers { uuid: "6eb07a7d-feb2-4b4a-9dd6-d606dc610384" id: "tbs-tango-2-pro-radio-controller-crossfire-ndaa" manufacturer: "Team Black Sheep" name: "TBS Tango 2 Pro Radio Controller - Crossfire - NDAA" weight_g: 0.0 }
receivers { uuid: "748394d6-69a6-4f32-88c8-b31d4782548d" id: "tbs-crossfire-tx-lite-transmitter-module-ndaa" manufacturer: "Team Black Sheep" name: "TBS Crossfire TX LITE Transmitter Module - NDAA" weight_g: 76.0 }
receivers { uuid: "7ca03770-6392-4cd4-88ec-6844c9a125ed" id: "nano-diversity-915mhz-receiver-for-crossfire-protocol-ndaa" manufacturer: "Team Black Sheep" name: "Nano Diversity 915MHz Receiver For Crossfire Protocol - NDAA" weight_g: 1.8 }
receivers { uuid: "44eccfa6-25af-4aad-ba28-73752a75f75d" id: "nano-pro-915mhz-receiver-for-crossfire-protocol-ndaa" manufacturer: "Team Black Sheep" name: "Nano PRO 915MHz Receiver For Crossfire Protocol - NDAA" weight_g: 0.5 }
receivers { uuid: "a5fec8b4-17ce-4d9c-92fe-9680f922ebd4" id: "nano-se-915mhz-receiver-for-crossfire-protocol-ndaa" manufacturer: "Team Black Sheep" name: "Nano SE 915MHz Receiver For Crossfire Protocol - NDAA" weight_g: 0.5 }
receivers { uuid: "ef9737e4-2196-4ccf-a35e-5cbb1b6b5e2d" id: "cinemini-immortal-t-elrs-antenna-mount" manufacturer: "Noozle3D" name: "CineMini Immortal T / ELRS Antenna Mount" weight_g: 0.0 }
receivers { uuid: "5357171b-b056-4473-be8b-d54ca5ce7b61" id: "cl2-immortal-t-elrs-dual-antenna-mount" manufacturer: "Noozle3D" name: "CL2 Immortal T / ELRS Dual Antenna Mount" weight_g: 0.0 }
receivers { uuid: "53fa1822-3ca5-4006-b2b3-4b07973a69fd" id: "xr4-gemini-xrossband-dual-band-receiver-for-elrs-protocol" manufacturer: "RadioMaster" name: "XR4 Gemini Xrossband Dual-Band  Receiver for ELRS Protocol" weight_g: 1.7 }
receivers { uuid: "0d067b99-53dc-4ad5-8e56-46ccc4925cc3" id: "xr3-nano-multi-frequency-antenna-diversity-receiver-for-elrs-protocol" manufacturer: "RadioMaster" name: "XR3 Nano Multi-Frequency Antenna Diversity Receiver for ELRS Protocol" weight_g: 1.3 }
receivers { uuid: "56894c2c-7520-4763-890c-27bdabf56067" id: "xr2-nano-2-4ghz-receiver-for-elrs-protocol" manufacturer: "RadioMaster" name: "XR2 Nano 2.4GHz Receiver for ELRS Protocol" weight_g: 0.8 }
receivers { uuid: "e38b1e37-fc81-4dff-ae2f-6be90e007537" id: "xr1-nano-multi-frequency-receiver-for-elrs-protocol" manufacturer: "RadioMaster" name: "XR1 Nano Multi-Frequency Receiver for ELRS Protocol" weight_g: 1.0 }
receivers { uuid: "b7a85ea6-11d9-4bee-879e-d921996613ac" id: "gx12-dual-band-radio-controller-elrs" manufacturer: "RadioMaster" name: "GX12 Dual-Band Radio Controller - ELRS" weight_g: 573.0 }
receivers { uuid: "fea7e270-f977-4b37-bb73-bf6990294b92" id: "shorty-pro-spec-rx-mount" manufacturer: "Noozle3D" name: "Shorty Pro-Spec RX Mount" weight_g: 0.0 }
receivers { uuid: "4022d740-2f86-441d-8c50-5dab00e718df" id: "punch-pro-spec-rx-cap-buzzer-mount" manufacturer: "Noozle3D" name: "Punch Pro-Spec RX / Cap / Buzzer Mount" weight_g: 0.0 }
receivers { uuid: "7fb9a982-bf1d-4072-acfe-fdad58381b61" id: "dbr4-dual-band-xross-gemini-receiver-for-elrs-protocol" manufacturer: "RadioMaster" name: "DBR4 Dual Band Xross Gemini Receiver for ELRS Protocol" weight_g: 0.0 }
receivers { uuid: "3b039892-a62f-45aa-aaac-ad83f2f0cda7" id: "nomad-elrs-dual-1w-gemini-xrossband-tx-module" manufacturer: "RadioMaster" name: "Nomad ELRS Dual 1W Gemini Xrossband TX Module" weight_g: 87.2 }
receivers { uuid: "2fd6662f-bf65-4e83-85ce-f8ed0591842f" id: "skylite-skyliner-mk3-immortal-t-elrs-antenna-mount-mjf-tpu" manufacturer: "Rotor Riot" name: "Skylite / Skyliner MK3 Immortal T / ELRS Antenna Mount - MJF TPU" weight_g: 0.0 }
receivers { uuid: "ed6a6fab-8a52-4815-aab4-5d77245166f4" id: "moongoat-sma-immortal-t-elrs-antenna-mount" manufacturer: "Noozle3D" name: "Moongoat SMA & Immortal T / ELRS Antenna Mount" weight_g: 0.0 }
receivers { uuid: "3625cea5-f920-495a-bf1a-8d43e0008ee7" id: "bandit-elrs-1w-915mhz-micro-tx-module" manufacturer: "RadioMaster" name: "Bandit ELRS 1W 915MHz Micro TX Module" weight_g: 78.0 }
receivers { uuid: "d2297fb0-839b-4257-8d56-8c494aaf80ab" id: "bandit-elrs-1w-915mhz-tx-module" manufacturer: "RadioMaster" name: "Bandit ELRS 1W 915MHz TX Module" weight_g: 155.0 }
receivers { uuid: "97e33d9c-ce15-4785-b5e1-6082fd48cf2e" id: "bandit-915-868mhz-receiver-antenna-choose-version" manufacturer: "RadioMaster" name: "Bandit 915/868MHz Receiver Antenna - Choose Version" weight_g: 2.02 }
receivers { uuid: "d2aac87f-4f75-4cf7-b804-a11c597d7ac6" id: "diversity-915-868mhz-receiver-for-elrs-protocol" manufacturer: "Foxeer" name: "Diversity 915/868MHz Receiver For ELRS Protocol" weight_g: 0.0 }
receivers { uuid: "ad476e95-6719-495d-bee9-da1b90516e54" id: "rp4td-2-4ghz-true-diversity-receiver-for-elrs-protocol" manufacturer: "RadioMaster" name: "RP4TD 2.4GHz True Diversity Receiver For ELRS Protocol" weight_g: 1.4 }
receivers { uuid: "3fd83924-5351-4a82-a07c-bad5f66421c8" id: "rp3-2-4ghz-diversity-receiver-for-elrs-protocol" manufacturer: "RadioMaster" name: "RP3 2.4GHz Diversity Receiver For ELRS Protocol" weight_g: 4.6 }
receivers { uuid: "395d6c69-9cad-4dda-99cf-eaf20a257e3f" id: "bandit-br1-915mhz-receiver-for-elrs-protocol" manufacturer: "RadioMaster" name: "Bandit BR1 915MHz Receiver For ELRS Protocol" weight_g: 1.7 }
receivers { uuid: "b083b39a-8e92-4833-aea4-87df3b29fa46" id: "bandit-elrs-1w-915mhz-nano-tx-module" manufacturer: "RadioMaster" name: "Bandit ELRS 1W 915MHz Nano TX Module" weight_g: 62.5 }
receivers { uuid: "ea87c4e7-f813-4a2c-8a4d-a017980f7844" id: "tx16s-mkii-radio-controller-elrs" manufacturer: "RadioMaster" name: "TX16S MKII Radio Controller - ELRS" weight_g: 750.0 }
receivers { uuid: "422ad350-5b9d-40d0-8680-39fe2c58f4f2" id: "skylite-skyliner-mk3-gps-immortal-t-elrs-antenna-mount-choose-color" manufacturer: "Noozle3D" name: "Skylite / Skyliner MK3 GPS & Immortal T / ELRS Antenna Mount - Choose Color" weight_g: 0.0 }
receivers { uuid: "90a25142-eef1-449a-823e-6595f843c3c5" id: "tanq-2-immortal-t-elrs-antenna-mount" manufacturer: "Noozle3D" name: "TANQ 2 Immortal T / ELRS Antenna Mount" weight_g: 0.0 }
receivers { uuid: "0251c09c-e436-4384-8884-c2b875eced5d" id: "tanq-gps-immortal-t-elrs-antenna-mount" manufacturer: "Noozle3D" name: "TANQ GPS & Immortal T / ELRS Antenna Mount" weight_g: 0.0 }
receivers { uuid: "61b16423-ff10-4f70-a44b-7d483146beb4" id: "boxer-edgetx-rotor-riot-edition-radio-controller-elrs" manufacturer: "RadioMaster" name: "Boxer EdgeTX Rotor Riot Edition Radio Controller - ELRS" weight_g: 532.5 }
receivers { uuid: "5a178a81-e1cf-41b7-b9fe-436983abd273" id: "er6gv-2-4ghz-pwm-receiver-for-elrs-protocol" manufacturer: "RadioMaster" name: "ER6GV 2.4GHz PWM Receiver For ELRS Protocol" weight_g: 5.0 }
receivers { uuid: "e918a555-55d6-4653-91ff-18899b0a22e0" id: "er4-2-4ghz-pwm-receiver-for-elrs-protocol" manufacturer: "RadioMaster" name: "ER4 2.4GHz PWM Receiver For ELRS Protocol" weight_g: 0.0 }
receivers { uuid: "b5d88445-9985-458d-9248-77632954138c" id: "ranger-elrs-1w-2-4ghz-nano-tx-module" manufacturer: "RadioMaster" name: "Ranger ELRS 1W 2.4GHz Nano TX Module" weight_g: 48.0 }
receivers { uuid: "ec8973d7-2d6e-44c9-b092-f920d1159c6c" id: "nano-915mhz-receiver-for-crossfire-protocol" manufacturer: "Team Black Sheep" name: "Nano 915MHz Receiver For Crossfire Protocol" weight_g: 0.5 }
receivers { uuid: "bf243dc5-ca6c-4cdf-b3f0-884b8b1dd343" id: "ranger-elrs-1w-2-4ghz-micro-tx-module" manufacturer: "RadioMaster" name: "Ranger ELRS 1W 2.4GHz Micro TX Module" weight_g: 48.0 }
receivers { uuid: "dde85e91-cfe4-43b6-9807-40a0000bf970" id: "t-antenna-915-868mhz-receiver-for-elrs-protocol" manufacturer: "Foxeer" name: "T Antenna 915/868MHz Receiver For ELRS Protocol" weight_g: 1.0 }
receivers { uuid: "11c9d78a-2419-4a18-b1b6-e903b2b26f4f" id: "915-868mhz-elrs-t-antenna-choose-version" manufacturer: "Foxeer" name: "915/868MHz ELRS T Antenna - Choose Version" weight_g: 7.5 }
receivers { uuid: "d7c4b600-bb1e-4f60-ba97-ae68efb0b3c7" id: "2-4ghz-elrs-t-antenna-choose-version" manufacturer: "Foxeer" name: "2.4GHz ELRS T Antenna - Choose Version" weight_g: 1.5 }
receivers { uuid: "ea65339a-f3de-437a-9538-49e9ef527339" id: "t-antenna-2-4ghz-receiver-with-lna-pa-for-elrs-protocol" manufacturer: "Foxeer" name: "T Antenna 2.4GHz Receiver with LNA & PA For ELRS Protocol" weight_g: 0.7 }
receivers { uuid: "eb16f065-7880-46b4-9218-c6a5ffa6ee87" id: "lite-2-4ghz-receiver-for-elrs-protocol" manufacturer: "Foxeer" name: "Lite 2.4GHz Receiver For ELRS Protocol" weight_g: 0.5 }
receivers { uuid: "8b71cd1c-b46a-49e8-b899-9afe47a50a90" id: "d-pole-mkii-2-4ghz-receiver-antenna" manufacturer: "TrueRC" name: "D-Pole MKII 2.4GHz Receiver Antenna" weight_g: 2.0 }
receivers { uuid: "b7680398-fb32-4e74-8174-a239999fd5d5" id: "crossfire-micro-dipole-915mhz-rc-receiver-antenna" manufacturer: "Team Black Sheep" name: "Crossfire Micro Dipole 915MHz RC Receiver Antenna" weight_g: 0.0 }
receivers { uuid: "70d85ebd-eeac-43ef-8369-0e8f0f6d2c05" id: "tto-2-4ghz-receiver-for-ghost-protocol-ndaa" manufacturer: "ImmersionRC" name: "Átto 2.4Ghz Receiver For Ghost Protocol - NDAA" weight_g: 0.0 }
receivers { uuid: "e2742695-c606-4ef9-bfec-d28be9f0786b" id: "tanq-immortal-t-elrs-antenna-mount" manufacturer: "Noozle3D" name: "TANQ Immortal T / ELRS Antenna Mount" weight_g: 0.0 }
receivers { uuid: "6cf4008b-288c-43c2-a0a1-83b4f45bcd13" id: "2-4ghz-t-antenna-for-rp1-and-ep1-choose-version" manufacturer: "RadioMaster" name: "2.4GHz T Antenna for RP1 and EP1 - Choose Version" weight_g: 1.76 }
receivers { uuid: "56beb8de-c0aa-4d33-97d7-961e940b2720" id: "ranger-elrs-1w-2-4ghz-tx-module" manufacturer: "RadioMaster" name: "Ranger ELRS 1W 2.4GHz TX Module" weight_g: 138.0 }
receivers { uuid: "75e69b1c-dbf7-45b9-8ec6-d5db6c663caa" id: "rp2-2-4ghz-receiver-for-elrs-protocol" manufacturer: "RadioMaster" name: "RP2 2.4GHz Receiver For ELRS Protocol" weight_g: 0.55 }
receivers { uuid: "6ad98ca6-f42c-42f4-a62f-0a5f65d14ec1" id: "qt-2-4ghz-receiver-antenna-for-ghost-tto" manufacturer: "ImmersionRC" name: "qT 2.4GHz Receiver Antenna for Ghost Átto" weight_g: 0.0 }
receivers { uuid: "c7792c9a-e30f-42a0-89ee-94a9da1bde84" id: "hook-v2-immortal-t-elrs-antenna-mount" manufacturer: "Noozle3D" name: "Hook V2 Immortal T / ELRS Antenna Mount" weight_g: 0.0 }
receivers { uuid: "2a2f9212-6e0e-4f05-a1d1-c859b41e8eeb" id: "tanq-1-2-rx-mounting-plate" manufacturer: "Rotor Riot" name: "TANQ 1 & 2 RX Mounting Plate" weight_g: 0.0 }
receivers { uuid: "b6dd4da0-cc0c-4f88-812c-7268e217760a" id: "rp1-2-4ghz-receiver-for-elrs-protocol" manufacturer: "RadioMaster" name: "RP1 2.4GHz Receiver For ELRS Protocol" weight_g: 2.2 }
receivers { uuid: "8fd5d1ff-da23-4790-b42d-445d277fe5c3" id: "skylite-skyliner-mk3-immortal-t-elrs-antenna-mount-choose-color" manufacturer: "Noozle3D" name: "Skylite / Skyliner MK3 Immortal T / ELRS Antenna Mount - Choose Color" weight_g: 0.0 }
receivers { uuid: "40b503eb-51d7-4e5b-97ba-1debc58f02e0" id: "cl2-immortal-t-elrs-antenna-mount-choose-color" manufacturer: "Noozle3D" name: "CL2 Immortal T / ELRS Antenna Mount - Choose Color" weight_g: 0.0 }
receivers { uuid: "540bc026-17f8-448b-9a5f-8c9b1e822334" id: "moxy-immortal-t-elrs-antenna-mount" manufacturer: "Noozle3D" name: "Moxy Immortal T / ELRS Antenna Mount" weight_g: 0.0 }
receivers { uuid: "769c9fd3-6924-43cd-8fdf-8b14bcedd156" id: "tx16s-mkii-max-joshua-bardwell-edition-radio-controller-elrs" manufacturer: "RadioMaster" name: "TX16S MKII MAX Joshua Bardwell Edition Radio Controller - ELRS" weight_g: 750.0 }
receivers { uuid: "a34feda7-2a95-4717-9385-6511ecdeff31" id: "tx16s-mk2-max-rotor-riot-edition-radio-controller-elrs" manufacturer: "RadioMaster" name: "TX16S MK2 Max Rotor Riot Edition Radio Controller - ELRS" weight_g: 750.0 }
receivers { uuid: "50ae859f-2295-477a-8c3a-1a9966b79ba0" id: "minimortal-t-915mhz-rc-receiver-antenna" manufacturer: "FPV Cycle" name: "Minimortal T 915MHz RC Receiver Antenna" weight_g: 0.7 }
receivers { uuid: "07bcb3af-4283-47e6-af2a-4f957348c061" id: "tracer-100mw-2-4ghz-micro-tx-module" manufacturer: "Team Black Sheep" name: "Tracer 100mW 2.4GHz Micro TX Module" weight_g: 0.0 }
receivers { uuid: "cc104547-83c4-4f30-a072-75b11d9e82e6" id: "tracer-100mw-2-4ghz-nano-tx-module" manufacturer: "Team Black Sheep" name: "Tracer 100mW 2.4GHz Nano TX Module" weight_g: 0.0 }
receivers { uuid: "a37ca8e9-6176-4529-8c9f-db52b5c9d8cf" id: "nano-2-4ghz-receiver-for-tracer-protocol" manufacturer: "Team Black Sheep" name: "Nano 2.4GHz Receiver for Tracer Protocol" weight_g: 0.5 }
receivers { uuid: "3eb1eebb-df55-4358-9999-e19b20281c62" id: "tx12-mkii-radio-controller-elrs" manufacturer: "RadioMaster" name: "TX12 MKII Radio Controller - ELRS" weight_g: 363.0 }
receivers { uuid: "424c83a5-a37c-4b03-8659-46a89d3e1c91" id: "r81-2-4ghz-receiver-for-frsky-protocol" manufacturer: "RadioMaster" name: "R81 2.4GHz Receiver For FrSky Protocol" weight_g: 2.0 }
receivers { uuid: "85326068-7f8f-474c-93d6-e45aa4ec5f6b" id: "immersionrc-ghost-rx-mounting-board-3-pack-ndaa-choose-version" manufacturer: "ImmersionRC" name: "ImmersionRC Ghost RX Mounting Board 3-Pack - NDAA - Choose Version" weight_g: 0.0 }
receivers { uuid: "f5893f01-1530-49ff-af57-0364fc45fcff" id: "cl1-hd1-immortal-t-elrs-antenna-mount-choose-color" manufacturer: "Noozle3D" name: "CL1 & HD1 Immortal T / ELRS Antenna Mount - Choose Color" weight_g: 0.0 }
receivers { uuid: "4950cf8c-3050-4f21-be6b-7dad1bce971f" id: "literadio-4-radio-transmitter" manufacturer: "BETAFPV" name: "LiteRadio 4 Radio Transmitter" weight_g: 0.0 }
receivers { uuid: "4c87e770-36e1-4cb5-80ec-4203dcc17ce8" id: "superx-elrs-gemini-xross-receiver" manufacturer: "BETAFPV" name: "SuperX ELRS Gemini Xross Receiver" weight_g: 0.82 }
receivers { uuid: "265e5dd6-db4b-47ed-8b0d-50af6e951415" id: "micro-tx-v2-module" manufacturer: "BETAFPV" name: "Micro TX V2 Module" weight_g: 54.8 }
receivers { uuid: "8909b06d-f723-4291-9452-55ca45ca0147" id: "nano-tx-v2-module" manufacturer: "BETAFPV" name: "Nano TX V2 Module" weight_g: 28.0 }
receivers { uuid: "cc317121-6c60-43b9-a3d8-5def7d134a18" id: "superg-nano-transmitter" manufacturer: "BETAFPV" name: "SuperG Nano Transmitter" weight_g: 44.8 }
receivers { uuid: "bbfde8c1-6dae-4557-a730-58c9bae14ebe" id: "superp-14ch-diversity-receiver" manufacturer: "BETAFPV" name: "SuperP 14CH Diversity Receiver" weight_g: 15.5 }
receivers { uuid: "701c27c5-0f4b-4120-a898-66c99817b865" id: "superd-elrs-diversity-receiver" manufacturer: "BETAFPV" name: "SuperD ELRS Diversity Receiver" weight_g: 1.1 }
receivers { uuid: "dfbb416c-3035-4bc8-b4f5-305ce2173e32" id: "expresslrs-recovery-dongle" manufacturer: "BETAFPV" name: "ExpressLRS Recovery Dongle" weight_g: 0.0 }
receivers { uuid: "2afe3b61-1db7-4531-aa2e-853ceb15c1c1" id: "literadio-3-pro-radio-transmitter" manufacturer: "BETAFPV" name: "LiteRadio 3 Pro Radio Transmitter" weight_g: 0.0 }
receivers { uuid: "96879699-ee15-4e6a-b390-0e53f65a09d6" id: "elrs-micro-receiver" manufacturer: "BETAFPV" name: "ELRS Micro Receiver" weight_g: 1.1 }
receivers { uuid: "065e4ce4-e341-4ce8-93a6-5c7787557c7f" id: "elrs-micro-tx-module-case-and-cooling-fan" manufacturer: "BETAFPV" name: "ELRS Micro TX Module Case and Cooling Fan" weight_g: 20.0 }
receivers { uuid: "4f236def-c0b6-4ca2-ac85-80de16da4607" id: "micro-nano-module-adapter" manufacturer: "BETAFPV" name: "Micro-Nano Module Adapter" weight_g: 25.0 }
receivers { uuid: "ecc5e908-7865-4548-a426-b58998aa8b25" id: "elrs-nano-tx-module" manufacturer: "BETAFPV" name: "ELRS Nano TX Module" weight_g: 0.0 }
receivers { uuid: "f8a501ad-a995-4fe9-880a-19d1eeed76fd" id: "literadio-2-se-radio-transmitter" manufacturer: "BETAFPV" name: "LiteRadio 2 SE Radio Transmitter" weight_g: 0.0 }
receivers { uuid: "81cbfaa7-4da1-4841-ba16-1eb59d7dfd56" id: "x-knight-360-fpv-quadcopter" manufacturer: "BETAFPV" name: "X-Knight 360 FPV Quadcopter" weight_g: 194.4 }
receivers { uuid: "30c006ee-365f-496a-acfd-0e79d7fceafa" id: "literadio-2-radio-transmitter" manufacturer: "BETAFPV" name: "LiteRadio 2 Radio Transmitter" weight_g: 227.4 }
receivers { uuid: "558ef2eb-214e-4673-bcb0-b89b5119a485" id: "pagoda-2-5-8g-fpv-antenna-2pcs" manufacturer: "BETAFPV" name: "Pagoda 2 5.8G  FPV Antenna (2PCS)" weight_g: 9.0 }
receivers { uuid: "c6bb0ff0-8f10-45ab-afcd-304ebbd5caa6" id: "ac900-dual-mode-receiver-frsky-futaba" manufacturer: "BETAFPV" name: "AC900 Dual Mode Receiver (FrSky & FUTABA)" weight_g: 0.9 }
receivers { uuid: "2dda2c50-1b8a-42a4-91aa-498a5c4d0907" id: "frsky-xm-sbus-mini-receiver-repair-component" manufacturer: "BETAFPV" name: "FrSky XM+ SBUS Mini Receiver (Repair Component)" weight_g: 1.6 }
receivers { uuid: "fb978eef-a603-454e-842d-342fbc1e5f7b" id: "flysky-rx2a-pro-receiver-for-micro-drone-upgraded" manufacturer: "BETAFPV" name: "Flysky RX2A Pro Receiver for Micro Drone(Upgraded)" weight_g: 0.88 }
receivers { uuid: "7442bd48-6df0-42d7-b3fe-beb3074e96ad" id: "dsmx-receiver-for-micro-drone" manufacturer: "BETAFPV" name: "DSMX Receiver for Micro Drone" weight_g: 0.6 }
receivers { uuid: "41abd0bf-aac6-4566-b32f-3068d38d1cc1" id: "betacube-for-whoop-quads" manufacturer: "BETAFPV" name: "BetaCube for Whoop Quads" weight_g: 0.0 }
receivers { uuid: "65ea6333-049a-4907-b61e-1b7718a65583" id: "fpv-whoop-racing-advanced-kit" manufacturer: "BETAFPV" name: "FPV Whoop Racing Advanced Kit" weight_g: 0.0 }
receivers { uuid: "697f0894-460f-451d-83a4-f4a13593354a" id: "caddxfpv-alink-controller" manufacturer: "CADDX FPV" name: "CaddxFPV Alink Controller" weight_g: 180.0 }
receivers { uuid: "62f9ee8f-0aab-4851-aff3-3cc126c0851f" id: "darwinfpv-elrs-2-4g-nano-receiver" manufacturer: "DarwinFPV - Official Store" name: "DarwinFPV  ELRS 2.4G Nano Receiver" weight_g: 0.0 }
receivers { uuid: "f4257b5a-2d47-4010-8625-690abc3d5316" id: "darwinfpv-hulk-iii-mini-waterproof-rtf" manufacturer: "DarwinFPV - Official Store" name: "DarwinFPV HULK III Mini Waterproof RTF" weight_g: 0.0 }
receivers { uuid: "27a69020-31cf-4ca6-9ca9-c69207e34289" id: "darwinfpv-tx8-elrs-radio-fpv-transmitter" manufacturer: "DarwinFPV - Official Store" name: "DarwinFPV TX8 ELRS Radio FPV Transmitter" weight_g: 0.0 }
receivers { uuid: "b6b45e24-fc05-443e-81b6-4a884e96f9b6" id: "darwinfpv-x10-large-load-and-long-range-10-fpv-drone" manufacturer: "DarwinFPV" name: "DarwinFPV X10 Large Load and Long Range 10  FPV Drone" weight_g: 0.0 }
receivers { uuid: "781f35aa-c2af-4f4c-9516-a4988dcac2f2" id: "darwinfpv-foldape4-4-inch-folding-long-range-rtf-kit" manufacturer: "DarwinFPV" name: "DarwinFPV FoldApe4 4 Inch Folding Long Range  RTF Kit" weight_g: 0.0 }
receivers { uuid: "39d6ffe7-3802-4aa1-92c5-504c753e504d" id: "darwinfpv-cineape35-fpv-drone-rtf" manufacturer: "DarwinFPV" name: "DarwinFPV CineApe35 FPV Drone RTF" weight_g: 0.0 }
receivers { uuid: "8f99249b-d2fb-44f2-8692-a5caee55c3b3" id: "darwinfpv-x9-9-long-range-fpv-drone" manufacturer: "DarwinFPV" name: "DarwinFPV X9 9 Long Range FPV Drone" weight_g: 0.0 }
receivers { uuid: "03890c6e-a9a4-4051-9db8-dbcb1f070d97" id: "tx12-mark-ii-elrs-radio-controller" manufacturer: "DarwinFPV" name: "TX12 Mark II  ELRS Radio Controller" weight_g: 363.0 }
receivers { uuid: "21b243bc-0c7d-4d70-8020-99c1d5577df0" id: "babyape-fpv-drone-rtf" manufacturer: "DarwinFPV" name: "BabyApe Ⅱ FPV Drone RTF" weight_g: 363.0 }
receivers { uuid: "b6569fab-19c0-43f8-928b-48520ef700ee" id: "darwinfpv-cineape-25-fpv-kit-rtf" manufacturer: "DarwinFPV" name: "DarwinFPV CineApe 25 FPV Kit RTF" weight_g: 0.0 }
receivers { uuid: "705d7c19-1a80-4e1c-9d9e-72e5730ea853" id: "darwinfpv-tx-lite-transmitter-rx-lite-receiver" manufacturer: "DarwinFPV" name: "DarwinFPV TX-Lite Transmitter+ RX-Lite Receiver" weight_g: 9.0 }
receivers { uuid: "b45bdf63-e27d-4c59-8993-233cd64da1ac" id: "radiomaster-zorro-elrs-radio-controller" manufacturer: "DarwinFPV" name: "Radiomaster Zorro ELRS Radio Controller" weight_g: 0.0 }
receivers { uuid: "54b263e0-0e2c-4bc8-89e6-c8e7a49b3577" id: "bayckrc-elrs-2-4g-nano-receiver" manufacturer: "DarwinFPV" name: "BAYCKRC ELRS 2.4G Nano Receiver" weight_g: 0.4 }
receivers { uuid: "1ac88bc2-1673-4362-97c1-907203a3a377" id: "darwinfpv-baby-ape-v4-pro-fpv-rtf" manufacturer: "DarwinFPV" name: "DarwinFPV Baby Ape V4 Pro FPV RTF" weight_g: 0.0 }
receivers { uuid: "48a31f0c-aaaa-47ba-934f-dc2c52291387" id: "darwinfpv-radiomaster-r81-receiver" manufacturer: "DarwinFPV" name: "DarwinFPV Radiomaster R81 Receiver" weight_g: 2.0 }
receivers { uuid: "04ba857c-fa2d-45db-8d7f-6bf1f980ce83" id: "darwin-vantac-elrs-2-4g-lite-tx-module" manufacturer: "DarwinFPV" name: "Darwin Vantac ELRS 2.4G Lite TX Module" weight_g: 0.0 }
receivers { uuid: "96067d86-7ec2-44da-a5ca-71f2dbe4b6dc" id: "darwin-240-johnny-5-quadcopters" manufacturer: "DarwinFPV" name: "Darwin 240 Johnny 5 Quadcopters" weight_g: 0.0 }
receivers { uuid: "6e979ff4-0e40-46ba-a852-53d9bbcc8ad7" id: "hummingbird-v4-1-complete-fly-repair-bundle" manufacturer: "NewBeeDrone" name: "Hummingbird V4.1 Complete Fly & Repair Bundle" weight_g: 0.0 }
receivers { uuid: "1dc1f3d0-2f66-444d-a725-85977febe280" id: "newbeedrone-beet-antenna-60mm-75mm-90mm-for-elrs-2-4ghz-receiver-u-fl-connector" manufacturer: "NewBeeDrone" name: "NewBeeDrone BeeT-Antenna 60mm/75mm/90mm for ELRS 2.4GHz Receiver - U.FL Connector" weight_g: 0.0 }
receivers { uuid: "105894d4-52e2-4f6e-a05a-ac9fdbc24d02" id: "newbeedrone-x-hummingbird-v3-1-brushless-rtf-bundle-kit" manufacturer: "NewBeeDrone" name: "NewBeeDrone x Hummingbird V3.1 Brushless RTF Bundle Kit" weight_g: 0.0 }
receivers { uuid: "788b5054-3430-48ad-8965-f448e58e4755" id: "newbeedrone-beet-antenna-for-expresslrs-elrs-2-4ghz-receiver-mhf3-connector" manufacturer: "NewBeeDrone" name: "NewBeeDrone BeeT-Antenna for  ExpressLRS(ELRS) 2.4GHz receiver MHF3 Connector" weight_g: 0.0 }
receivers { uuid: "210622ab-7cd7-411d-bdc5-329f8f9c597e" id: "newbeedrone-acrobee75-blv5-bnf-elrs2-4g-2s-the-ultimate-outdoor-whoop" manufacturer: "NewBeeDrone" name: "NewBeeDrone AcroBee75 BLV5 BNF ELRS2.4G 2S - The Ultimate Outdoor Whoop" weight_g: 36.4 }
receivers { uuid: "9be31ce8-6ee0-4f06-978e-c3b3d8f3efa6" id: "newbeedrone-beeceiver-elrs-2-4ghz-diversity-with-tcxo-oscillator-micro-receiver" manufacturer: "NewBeeDrone" name: "NewBeeDrone BeeCeiver ELRS 2.4Ghz Diversity with TCXO Oscillator Micro Receiver" weight_g: 1.6 }
receivers { uuid: "b0fe0c4d-fab0-46c4-9063-8984eed72e81" id: "newbeedrone-beebrainbl-hummingbird-receiver-connector-type-mhf3-pack-of-4" manufacturer: "NewBeeDrone" name: "NewBeeDrone BeeBrainBL/Hummingbird Receiver Connector Type:MHF3 (pack of 4)" weight_g: 0.0 }
receivers { uuid: "aa69e628-39c8-4dff-930b-77ebec9cbb07" id: "newbeedrone-beet-antenna-for-expresslrs-elrs-2-4ghz-receiver-mhf3-connector-blv4" manufacturer: "NewBeeDrone" name: "NewBeeDrone BeeT-Antenna for  ExpressLRS(ELRS) 2.4GHz receiver MHF3 Connector /BLV4" weight_g: 0.0 }
receivers { uuid: "0b4d6ac0-a4ff-4698-bbb5-129a5bbe5b3b" id: "newbeedrone-2-4g-replacement-receiver-antennas-60mm-for-beebrain-blv3-blv4-hmb-f4-v2" manufacturer: "NewBeeDrone" name: "NewBeeDrone 2.4G Replacement Receiver Antennas 60mm for BeeBrain BLV3/BLV4/HMB F4 V2" weight_g: 0.0 }
receivers { uuid: "e1bc69ad-4778-4341-ad15-4f908b414556" id: "newbeedrone-vim-v2-replacement-parts" manufacturer: "NewBeeDrone" name: "NewBeeDrone VIM V2 Replacement Parts" weight_g: 0.0 }
receivers { uuid: "24d9c688-b7df-42ff-8d67-367ecdd01bb5" id: "hdo-analog-fpv-goggles-ndaa" manufacturer: "Fat Shark" name: "HDO+ Analog FPV Goggles - NDAA" weight_g: 235.8 }
receivers { uuid: "8fd0f6e6-a841-483b-a5b7-1f8a1cc60803" id: "cinemini-2-5-3d-prints-bundle-dji-o4" manufacturer: "Rotor Riot" name: "CineMini 2.5 3D Prints Bundle - DJI O4" weight_g: 0.0 }
receivers { uuid: "427894f2-c6bc-4ff7-8b77-21afa3e8ec1b" id: "futaba-r7208sb-fasstest-bi-directional-communication-system-s-bus-s-bus2-port-and-8-channels-receiver" manufacturer: "Futaba" name: "Futaba R7208SB – FASSTest Bi-Directional Communication System S.Bus/S.Bus2 Port and 8 Channels Receiver" weight_g: 12.0 }
receivers { uuid: "1149b5a5-1764-4e2e-ad1d-0a52f3e47e79" id: "tanq-2-6s-5-pro-spec-by-let-sflyrc-built-tuned-drone-dji-o4-pro-elrs" manufacturer: "Rotor Riot Builds" name: "Tanq 2 6S 5 Pro-Spec by Let'sFlyRC Built & Tuned Drone - DJI O4 Pro / ELRS" weight_g: 0.0 }
receivers { uuid: "2a0e6277-3e4c-4780-abbd-b18db2a8a788" id: "fat-shark-recon-hd-goggle-bundle" manufacturer: "Rotor Riot Store" name: "Fat Shark Recon HD Goggle Bundle" weight_g: 46.22 }
receivers { uuid: "027f09f1-df4e-47ba-84d1-29204444fc0f" id: "pocket-radio-controller-fat-shark-edition-elrs" manufacturer: "RadioMaster" name: "Pocket Radio Controller (Fat Shark Edition) - ELRS" weight_g: 288.0 }
receivers { uuid: "0f3e2090-ea51-4e98-a0ea-91b556be39f2" id: "vision40-2s-40mm-built-tuned-drone-dji-o4-dji" manufacturer: "Rotor Riot Builds" name: "Vision40 2S 40mm Built & Tuned Drone - DJI O4 / DJI" weight_g: 0.0 }
receivers { uuid: "e0ffb411-0e93-4791-a324-dcda4a64e1f9" id: "tx15-radio-controller-expresslrs" manufacturer: "RadioMaster" name: "TX15 Radio Controller ExpressLRS" weight_g: 605.0 }
receivers { uuid: "803789a9-46cb-435a-9ab6-e8561b397d63" id: "tx15-max-radio-controller-expresslrs" manufacturer: "RadioMaster" name: "TX15 Max Radio Controller ExpressLRS" weight_g: 672.0 }
receivers { uuid: "393cdb1b-4605-4be2-abf7-fe3c601bb4dd" id: "tbs-tango-2-pro-radio-controller-crossfire-ndaa" manufacturer: "Team Black Sheep" name: "TBS Tango 2 Pro Radio Controller - Crossfire - NDAA" weight_g: 0.0 }
receivers { uuid: "0072a71a-061b-4036-83ef-2ccd48bfb168" id: "tbs-crossfire-tx-lite-transmitter-module-ndaa" manufacturer: "Team Black Sheep" name: "TBS Crossfire TX LITE Transmitter Module - NDAA" weight_g: 76.0 }
receivers { uuid: "544be4f8-015d-441a-8351-c9322516aa9d" id: "nano-diversity-915mhz-receiver-for-crossfire-protocol-ndaa" manufacturer: "Team Black Sheep" name: "Nano Diversity 915MHz Receiver For Crossfire Protocol - NDAA" weight_g: 1.8 }
receivers { uuid: "5f4fd902-3e48-4cc9-bb99-ad71a46a7b9e" id: "nano-pro-915mhz-receiver-for-crossfire-protocol-ndaa" manufacturer: "Team Black Sheep" name: "Nano PRO 915MHz Receiver For Crossfire Protocol - NDAA" weight_g: 0.5 }
receivers { uuid: "9e14072c-0a3e-4a71-a149-456c932be904" id: "nano-se-915mhz-receiver-for-crossfire-protocol-ndaa" manufacturer: "Team Black Sheep" name: "Nano SE 915MHz Receiver For Crossfire Protocol - NDAA" weight_g: 0.5 }
receivers { uuid: "62eddd66-3460-4020-a0c6-2694d3fd83cb" id: "cinemini-immortal-t-elrs-antenna-mount" manufacturer: "Noozle3D" name: "CineMini Immortal T / ELRS Antenna Mount" weight_g: 0.0 }
receivers { uuid: "c3527ef2-1183-463e-b6ee-80b1273862b3" id: "cl2-immortal-t-elrs-dual-antenna-mount" manufacturer: "Noozle3D" name: "CL2 Immortal T / ELRS Dual Antenna Mount" weight_g: 0.0 }
receivers { uuid: "d3ffce33-5680-4d50-b279-34714853a6ef" id: "xr4-gemini-xrossband-dual-band-receiver-for-elrs-protocol" manufacturer: "RadioMaster" name: "XR4 Gemini Xrossband Dual-Band  Receiver for ELRS Protocol" weight_g: 1.7 }
receivers { uuid: "32f92e53-4017-4bbd-bb1f-e5ebb697f035" id: "xr3-nano-multi-frequency-antenna-diversity-receiver-for-elrs-protocol" manufacturer: "RadioMaster" name: "XR3 Nano Multi-Frequency Antenna Diversity Receiver for ELRS Protocol" weight_g: 1.3 }
receivers { uuid: "dad82be6-8255-4881-93d0-e360c1b94935" id: "xr2-nano-2-4ghz-receiver-for-elrs-protocol" manufacturer: "RadioMaster" name: "XR2 Nano 2.4GHz Receiver for ELRS Protocol" weight_g: 0.8 }
receivers { uuid: "2cca9943-ad0f-43db-8afc-cca89f371a24" id: "xr1-nano-multi-frequency-receiver-for-elrs-protocol" manufacturer: "RadioMaster" name: "XR1 Nano Multi-Frequency Receiver for ELRS Protocol" weight_g: 1.0 }
receivers { uuid: "8c3f5371-facc-47bc-ad9d-5f3832a94311" id: "gx12-dual-band-radio-controller-elrs" manufacturer: "RadioMaster" name: "GX12 Dual-Band Radio Controller - ELRS" weight_g: 573.0 }
receivers { uuid: "860fe888-d494-4cb9-a3b9-5cb86bb312cb" id: "shorty-pro-spec-rx-mount" manufacturer: "Noozle3D" name: "Shorty Pro-Spec RX Mount" weight_g: 0.0 }
receivers { uuid: "e4844e02-d6f2-4b38-8456-4950e416794a" id: "punch-pro-spec-rx-cap-buzzer-mount" manufacturer: "Noozle3D" name: "Punch Pro-Spec RX / Cap / Buzzer Mount" weight_g: 0.0 }
receivers { uuid: "1c97de2f-c4f0-4001-a833-acb0a0e2d0e7" id: "dbr4-dual-band-xross-gemini-receiver-for-elrs-protocol" manufacturer: "RadioMaster" name: "DBR4 Dual Band Xross Gemini Receiver for ELRS Protocol" weight_g: 0.0 }
receivers { uuid: "08355cfd-b137-44dc-bb0d-104040680f74" id: "nomad-elrs-dual-1w-gemini-xrossband-tx-module" manufacturer: "RadioMaster" name: "Nomad ELRS Dual 1W Gemini Xrossband TX Module" weight_g: 87.2 }
receivers { uuid: "29236093-ee0a-46ca-8a29-57ac592f53fa" id: "skylite-skyliner-mk3-immortal-t-elrs-antenna-mount-mjf-tpu" manufacturer: "Rotor Riot" name: "Skylite / Skyliner MK3 Immortal T / ELRS Antenna Mount - MJF TPU" weight_g: 0.0 }
receivers { uuid: "6898fdb9-afde-4836-a51c-2b300934b895" id: "moongoat-sma-immortal-t-elrs-antenna-mount" manufacturer: "Noozle3D" name: "Moongoat SMA & Immortal T / ELRS Antenna Mount" weight_g: 0.0 }
receivers { uuid: "833d6c97-2d1b-4ff8-a9ab-8f58a84e6b8d" id: "bandit-elrs-1w-915mhz-micro-tx-module" manufacturer: "RadioMaster" name: "Bandit ELRS 1W 915MHz Micro TX Module" weight_g: 78.0 }
receivers { uuid: "630cb8f2-fef0-4bb2-b0e8-405352eee8e8" id: "bandit-elrs-1w-915mhz-tx-module" manufacturer: "RadioMaster" name: "Bandit ELRS 1W 915MHz TX Module" weight_g: 155.0 }
receivers { uuid: "f781866c-0c56-4b0d-84b9-17f76e0401cb" id: "bandit-915-868mhz-receiver-antenna-choose-version" manufacturer: "RadioMaster" name: "Bandit 915/868MHz Receiver Antenna - Choose Version" weight_g: 2.02 }
receivers { uuid: "721f5690-df05-4ece-a6c3-d9e95b2be020" id: "diversity-915-868mhz-receiver-for-elrs-protocol" manufacturer: "Foxeer" name: "Diversity 915/868MHz Receiver For ELRS Protocol" weight_g: 0.0 }
receivers { uuid: "0e7c02f9-b92a-461b-abcb-df0ac2690755" id: "rp4td-2-4ghz-true-diversity-receiver-for-elrs-protocol" manufacturer: "RadioMaster" name: "RP4TD 2.4GHz True Diversity Receiver For ELRS Protocol" weight_g: 1.4 }
receivers { uuid: "738fbad6-95e5-4a37-b939-6ce58b136542" id: "rp3-2-4ghz-diversity-receiver-for-elrs-protocol" manufacturer: "RadioMaster" name: "RP3 2.4GHz Diversity Receiver For ELRS Protocol" weight_g: 4.6 }
receivers { uuid: "8710abbf-cc07-4630-81f8-4744c82d5ded" id: "bandit-br1-915mhz-receiver-for-elrs-protocol" manufacturer: "RadioMaster" name: "Bandit BR1 915MHz Receiver For ELRS Protocol" weight_g: 1.7 }
receivers { uuid: "98c4299c-1e04-434f-8a17-457f3ef4bd9d" id: "bandit-elrs-1w-915mhz-nano-tx-module" manufacturer: "RadioMaster" name: "Bandit ELRS 1W 915MHz Nano TX Module" weight_g: 62.5 }
receivers { uuid: "610fe3d9-9ac5-490e-8190-b5c9e6ecbb10" id: "tx16s-mkii-radio-controller-elrs" manufacturer: "RadioMaster" name: "TX16S MKII Radio Controller - ELRS" weight_g: 750.0 }
receivers { uuid: "ed77c51b-fa62-40c7-bcbc-214b1ab19c60" id: "skylite-skyliner-mk3-gps-immortal-t-elrs-antenna-mount-choose-color" manufacturer: "Noozle3D" name: "Skylite / Skyliner MK3 GPS & Immortal T / ELRS Antenna Mount - Choose Color" weight_g: 0.0 }
receivers { uuid: "73294f7c-c254-4630-ab2c-a248622c8b1e" id: "tanq-2-immortal-t-elrs-antenna-mount" manufacturer: "Noozle3D" name: "TANQ 2 Immortal T / ELRS Antenna Mount" weight_g: 0.0 }
receivers { uuid: "1e9e5085-ee71-459b-9d2a-6749a3b1b9fb" id: "tanq-gps-immortal-t-elrs-antenna-mount" manufacturer: "Noozle3D" name: "TANQ GPS & Immortal T / ELRS Antenna Mount" weight_g: 0.0 }
receivers { uuid: "c4959391-3fca-43d4-9e2b-0126b0d4be7a" id: "boxer-edgetx-rotor-riot-edition-radio-controller-elrs" manufacturer: "RadioMaster" name: "Boxer EdgeTX Rotor Riot Edition Radio Controller - ELRS" weight_g: 532.5 }
receivers { uuid: "1ea7a127-8780-485e-9905-14d37028a91f" id: "er6gv-2-4ghz-pwm-receiver-for-elrs-protocol" manufacturer: "RadioMaster" name: "ER6GV 2.4GHz PWM Receiver For ELRS Protocol" weight_g: 5.0 }
receivers { uuid: "71cdf671-53b6-4856-999f-5451e079fdd7" id: "er4-2-4ghz-pwm-receiver-for-elrs-protocol" manufacturer: "RadioMaster" name: "ER4 2.4GHz PWM Receiver For ELRS Protocol" weight_g: 0.0 }
receivers { uuid: "acfe4d01-0599-4aa9-ac43-e771d18d5b13" id: "ranger-elrs-1w-2-4ghz-nano-tx-module" manufacturer: "RadioMaster" name: "Ranger ELRS 1W 2.4GHz Nano TX Module" weight_g: 48.0 }
receivers { uuid: "f7dc8bb1-1ea0-4e0c-97ef-4e6da74ae3f5" id: "nano-915mhz-receiver-for-crossfire-protocol" manufacturer: "Team Black Sheep" name: "Nano 915MHz Receiver For Crossfire Protocol" weight_g: 0.5 }
receivers { uuid: "02b95567-13ef-466e-944b-5085674e8174" id: "ranger-elrs-1w-2-4ghz-micro-tx-module" manufacturer: "RadioMaster" name: "Ranger ELRS 1W 2.4GHz Micro TX Module" weight_g: 48.0 }
receivers { uuid: "c905d2d7-0da1-4448-a60c-1cb6b36be9bf" id: "t-antenna-915-868mhz-receiver-for-elrs-protocol" manufacturer: "Foxeer" name: "T Antenna 915/868MHz Receiver For ELRS Protocol" weight_g: 1.0 }
receivers { uuid: "1cf51f1f-7913-4d24-807f-601afc3a82fc" id: "915-868mhz-elrs-t-antenna-choose-version" manufacturer: "Foxeer" name: "915/868MHz ELRS T Antenna - Choose Version" weight_g: 7.5 }
receivers { uuid: "0f553309-828a-49fe-8df9-007cea39e24e" id: "2-4ghz-elrs-t-antenna-choose-version" manufacturer: "Foxeer" name: "2.4GHz ELRS T Antenna - Choose Version" weight_g: 1.5 }
receivers { uuid: "6e69eb4b-a4d5-4224-ab4a-1270ba3fd6d2" id: "t-antenna-2-4ghz-receiver-with-lna-pa-for-elrs-protocol" manufacturer: "Foxeer" name: "T Antenna 2.4GHz Receiver with LNA & PA For ELRS Protocol" weight_g: 0.7 }
receivers { uuid: "b4c1eda4-6e2e-445e-869d-abde77ef0960" id: "lite-2-4ghz-receiver-for-elrs-protocol" manufacturer: "Foxeer" name: "Lite 2.4GHz Receiver For ELRS Protocol" weight_g: 0.5 }
receivers { uuid: "9461e64e-3bec-4721-bbec-d473865fdbb4" id: "d-pole-mkii-2-4ghz-receiver-antenna" manufacturer: "TrueRC" name: "D-Pole MKII 2.4GHz Receiver Antenna" weight_g: 2.0 }
receivers { uuid: "df9cf884-ef4f-470d-b87f-2c82c1c3d9e1" id: "crossfire-micro-dipole-915mhz-rc-receiver-antenna" manufacturer: "Team Black Sheep" name: "Crossfire Micro Dipole 915MHz RC Receiver Antenna" weight_g: 0.0 }
receivers { uuid: "e2c3cc2a-b5c9-4240-8212-55b7532fb2fd" id: "tto-2-4ghz-receiver-for-ghost-protocol-ndaa" manufacturer: "ImmersionRC" name: "Átto 2.4Ghz Receiver For Ghost Protocol - NDAA" weight_g: 0.0 }
receivers { uuid: "ef15d1c2-52d2-4e7a-afb2-e08901f11730" id: "tanq-immortal-t-elrs-antenna-mount" manufacturer: "Noozle3D" name: "TANQ Immortal T / ELRS Antenna Mount" weight_g: 0.0 }
receivers { uuid: "3ef18279-06c3-475b-9804-807e6c5b0557" id: "2-4ghz-t-antenna-for-rp1-and-ep1-choose-version" manufacturer: "RadioMaster" name: "2.4GHz T Antenna for RP1 and EP1 - Choose Version" weight_g: 1.76 }
receivers { uuid: "27b92dd2-5a79-4e6d-ac7f-1bf30304d530" id: "ranger-elrs-1w-2-4ghz-tx-module" manufacturer: "RadioMaster" name: "Ranger ELRS 1W 2.4GHz TX Module" weight_g: 138.0 }
receivers { uuid: "310b6f3b-e747-43dc-8940-297101d37590" id: "rp2-2-4ghz-receiver-for-elrs-protocol" manufacturer: "RadioMaster" name: "RP2 2.4GHz Receiver For ELRS Protocol" weight_g: 0.55 }
receivers { uuid: "cb177416-cabb-43cc-a7c7-18a3edc7da5c" id: "qt-2-4ghz-receiver-antenna-for-ghost-tto" manufacturer: "ImmersionRC" name: "qT 2.4GHz Receiver Antenna for Ghost Átto" weight_g: 0.0 }
receivers { uuid: "91ada90f-330e-41e6-933c-bdec9b3da40b" id: "hook-v2-immortal-t-elrs-antenna-mount" manufacturer: "Noozle3D" name: "Hook V2 Immortal T / ELRS Antenna Mount" weight_g: 0.0 }
receivers { uuid: "ec18bab7-b47a-47a9-bc50-b26de2978069" id: "tanq-1-2-rx-mounting-plate" manufacturer: "Rotor Riot" name: "TANQ 1 & 2 RX Mounting Plate" weight_g: 0.0 }
receivers { uuid: "c3c2ec70-5632-4af0-a810-eeaeb193e3f2" id: "rp1-2-4ghz-receiver-for-elrs-protocol" manufacturer: "RadioMaster" name: "RP1 2.4GHz Receiver For ELRS Protocol" weight_g: 2.2 }
receivers { uuid: "4f038484-44f2-4f75-b05a-fd186594ce75" id: "skylite-skyliner-mk3-immortal-t-elrs-antenna-mount-choose-color" manufacturer: "Noozle3D" name: "Skylite / Skyliner MK3 Immortal T / ELRS Antenna Mount - Choose Color" weight_g: 0.0 }
receivers { uuid: "403dfaae-7bc8-4720-9221-31017ee67de7" id: "cl2-immortal-t-elrs-antenna-mount-choose-color" manufacturer: "Noozle3D" name: "CL2 Immortal T / ELRS Antenna Mount - Choose Color" weight_g: 0.0 }
receivers { uuid: "eb48bc25-04fd-4f1c-84a5-3aa717004713" id: "moxy-immortal-t-elrs-antenna-mount" manufacturer: "Noozle3D" name: "Moxy Immortal T / ELRS Antenna Mount" weight_g: 0.0 }
receivers { uuid: "2832a757-2eda-4dd9-8e24-6d1d2c77b77c" id: "tx16s-mkii-max-joshua-bardwell-edition-radio-controller-elrs" manufacturer: "RadioMaster" name: "TX16S MKII MAX Joshua Bardwell Edition Radio Controller - ELRS" weight_g: 750.0 }
receivers { uuid: "86373f31-c58d-4762-a245-c62542049df6" id: "tx16s-mk2-max-rotor-riot-edition-radio-controller-elrs" manufacturer: "RadioMaster" name: "TX16S MK2 Max Rotor Riot Edition Radio Controller - ELRS" weight_g: 750.0 }
receivers { uuid: "4d661bed-a3b7-48d6-8ca8-c7d087a268c0" id: "minimortal-t-915mhz-rc-receiver-antenna" manufacturer: "FPV Cycle" name: "Minimortal T 915MHz RC Receiver Antenna" weight_g: 0.7 }
receivers { uuid: "84466594-f863-4f69-a909-e7fee288070e" id: "tracer-100mw-2-4ghz-micro-tx-module" manufacturer: "Team Black Sheep" name: "Tracer 100mW 2.4GHz Micro TX Module" weight_g: 0.0 }
receivers { uuid: "6689e3e3-4a7f-42d1-b06f-d5fa15d8190a" id: "tracer-100mw-2-4ghz-nano-tx-module" manufacturer: "Team Black Sheep" name: "Tracer 100mW 2.4GHz Nano TX Module" weight_g: 0.0 }
receivers { uuid: "0e77dae7-98bf-4674-bd17-e37d0408e102" id: "nano-2-4ghz-receiver-for-tracer-protocol" manufacturer: "Team Black Sheep" name: "Nano 2.4GHz Receiver for Tracer Protocol" weight_g: 0.5 }
receivers { uuid: "99efa28c-4afa-4e6f-a396-c089524ae1e2" id: "tx12-mkii-radio-controller-elrs" manufacturer: "RadioMaster" name: "TX12 MKII Radio Controller - ELRS" weight_g: 363.0 }
receivers { uuid: "75d260b1-f8ef-42b8-aef3-85d57a15cd8a" id: "r81-2-4ghz-receiver-for-frsky-protocol" manufacturer: "RadioMaster" name: "R81 2.4GHz Receiver For FrSky Protocol" weight_g: 2.0 }
receivers { uuid: "8bcfbe88-64c8-4b0c-bba2-efb61858f521" id: "immersionrc-ghost-rx-mounting-board-3-pack-ndaa-choose-version" manufacturer: "ImmersionRC" name: "ImmersionRC Ghost RX Mounting Board 3-Pack - NDAA - Choose Version" weight_g: 0.0 }
receivers { uuid: "8539740f-ea46-4953-9dcc-d278de3b17ef" id: "cl1-hd1-immortal-t-elrs-antenna-mount-choose-color" manufacturer: "Noozle3D" name: "CL1 & HD1 Immortal T / ELRS Antenna Mount - Choose Color" weight_g: 0.0 }
receivers { uuid: "fcdfc6f4-766f-4e60-82e1-eddea0f771c7" id: "literadio-4-radio-transmitter" manufacturer: "BETAFPV" name: "LiteRadio 4 Radio Transmitter" weight_g: 0.0 }
receivers { uuid: "c5f9dc37-f7ee-4602-b3df-05f36b050af4" id: "superx-elrs-gemini-xross-receiver" manufacturer: "BETAFPV" name: "SuperX ELRS Gemini Xross Receiver" weight_g: 0.82 }
receivers { uuid: "81982d26-e525-49ca-8125-75c8b808f51f" id: "micro-tx-v2-module" manufacturer: "BETAFPV" name: "Micro TX V2 Module" weight_g: 54.8 }
receivers { uuid: "b54973db-71ac-4561-838f-11e7c915e961" id: "nano-tx-v2-module" manufacturer: "BETAFPV" name: "Nano TX V2 Module" weight_g: 28.0 }
receivers { uuid: "a0123b8a-853a-4a33-9c66-3725541d48b6" id: "superg-nano-transmitter" manufacturer: "BETAFPV" name: "SuperG Nano Transmitter" weight_g: 44.8 }
receivers { uuid: "caf1f1e2-7e99-4759-b9b2-3dfa58b728ff" id: "superp-14ch-diversity-receiver" manufacturer: "BETAFPV" name: "SuperP 14CH Diversity Receiver" weight_g: 15.5 }
receivers { uuid: "6b83d817-7030-47e3-98b2-1d01034019da" id: "superd-elrs-diversity-receiver" manufacturer: "BETAFPV" name: "SuperD ELRS Diversity Receiver" weight_g: 1.1 }
receivers { uuid: "9fa4fa38-29c5-4b69-8b18-21f5f48b168f" id: "expresslrs-recovery-dongle" manufacturer: "BETAFPV" name: "ExpressLRS Recovery Dongle" weight_g: 0.0 }
receivers { uuid: "82ada0a1-0e7a-4273-bc28-0880f01f359d" id: "literadio-3-pro-radio-transmitter" manufacturer: "BETAFPV" name: "LiteRadio 3 Pro Radio Transmitter" weight_g: 0.0 }
receivers { uuid: "18739f1f-5163-4561-b0e0-ab6b10f7bfb2" id: "elrs-micro-receiver" manufacturer: "BETAFPV" name: "ELRS Micro Receiver" weight_g: 1.1 }
receivers { uuid: "f77150b4-64c2-4d95-9628-601a4241d44d" id: "elrs-micro-tx-module-case-and-cooling-fan" manufacturer: "BETAFPV" name: "ELRS Micro TX Module Case and Cooling Fan" weight_g: 20.0 }
receivers { uuid: "bb22d95f-f513-4eb7-9321-b66651713156" id: "micro-nano-module-adapter" manufacturer: "BETAFPV" name: "Micro-Nano Module Adapter" weight_g: 25.0 }
receivers { uuid: "08e97118-8d27-47ba-95a4-f043c96251ba" id: "elrs-nano-tx-module" manufacturer: "BETAFPV" name: "ELRS Nano TX Module" weight_g: 0.0 }
receivers { uuid: "b2b86f40-a7c8-4a4c-9a76-a19d2de97a8a" id: "literadio-2-se-radio-transmitter" manufacturer: "BETAFPV" name: "LiteRadio 2 SE Radio Transmitter" weight_g: 0.0 }
receivers { uuid: "a8245772-6513-4dba-a4ac-c05a53f7da39" id: "x-knight-360-fpv-quadcopter" manufacturer: "BETAFPV" name: "X-Knight 360 FPV Quadcopter" weight_g: 194.4 }
receivers { uuid: "97259cbe-13d5-4f12-8e18-40f27df168ca" id: "literadio-2-radio-transmitter" manufacturer: "BETAFPV" name: "LiteRadio 2 Radio Transmitter" weight_g: 227.4 }
receivers { uuid: "87b63e60-8623-4b65-ac8e-2c3c4549a766" id: "pagoda-2-5-8g-fpv-antenna-2pcs" manufacturer: "BETAFPV" name: "Pagoda 2 5.8G  FPV Antenna (2PCS)" weight_g: 9.0 }
receivers { uuid: "001400af-937a-437b-9c28-18f764ab1b84" id: "ac900-dual-mode-receiver-frsky-futaba" manufacturer: "BETAFPV" name: "AC900 Dual Mode Receiver (FrSky & FUTABA)" weight_g: 0.9 }
receivers { uuid: "021f6aea-0312-4880-af19-63cd1fc56989" id: "frsky-xm-sbus-mini-receiver-repair-component" manufacturer: "BETAFPV" name: "FrSky XM+ SBUS Mini Receiver (Repair Component)" weight_g: 1.6 }
receivers { uuid: "b722b267-b0f9-459a-ac30-96b690f9a47f" id: "flysky-rx2a-pro-receiver-for-micro-drone-upgraded" manufacturer: "BETAFPV" name: "Flysky RX2A Pro Receiver for Micro Drone(Upgraded)" weight_g: 0.88 }
receivers { uuid: "e7c0dc74-73dd-4c6a-9d47-39e0fa2d20a0" id: "dsmx-receiver-for-micro-drone" manufacturer: "BETAFPV" name: "DSMX Receiver for Micro Drone" weight_g: 0.6 }
receivers { uuid: "4036a7c7-3eae-4bb7-b3c9-9ed6b903e023" id: "betacube-for-whoop-quads" manufacturer: "BETAFPV" name: "BetaCube for Whoop Quads" weight_g: 0.0 }
receivers { uuid: "617323f8-f21f-48ee-8800-4fda231b2307" id: "fpv-whoop-racing-advanced-kit" manufacturer: "BETAFPV" name: "FPV Whoop Racing Advanced Kit" weight_g: 0.0 }
receivers { uuid: "dc3ad88a-1ce3-4145-a0f0-95e97e574731" id: "caddxfpv-alink-controller" manufacturer: "CADDX FPV" name: "CaddxFPV Alink Controller" weight_g: 180.0 }
receivers { uuid: "113f70e2-c821-4e60-8ee6-d9881c0fa8fe" id: "darwinfpv-elrs-2-4g-nano-receiver" manufacturer: "DarwinFPV - Official Store" name: "DarwinFPV  ELRS 2.4G Nano Receiver" weight_g: 0.0 }
receivers { uuid: "584a31cd-2e06-4fd3-be99-c0152cbb533d" id: "darwinfpv-hulk-iii-mini-waterproof-rtf" manufacturer: "DarwinFPV - Official Store" name: "DarwinFPV HULK III Mini Waterproof RTF" weight_g: 0.0 }
receivers { uuid: "e1703780-39b2-4f1c-949e-3bfe74feb5d6" id: "darwinfpv-tx8-elrs-radio-fpv-transmitter" manufacturer: "DarwinFPV - Official Store" name: "DarwinFPV TX8 ELRS Radio FPV Transmitter" weight_g: 0.0 }
receivers { uuid: "a7774378-5864-4dea-8601-82e45cd0ad6e" id: "darwinfpv-x10-large-load-and-long-range-10-fpv-drone" manufacturer: "DarwinFPV" name: "DarwinFPV X10 Large Load and Long Range 10  FPV Drone" weight_g: 0.0 }
receivers { uuid: "afb178a7-bd5a-4fee-b897-401aebb4bd64" id: "darwinfpv-foldape4-4-inch-folding-long-range-rtf-kit" manufacturer: "DarwinFPV" name: "DarwinFPV FoldApe4 4 Inch Folding Long Range  RTF Kit" weight_g: 0.0 }
receivers { uuid: "72189e6a-4619-4c91-ba91-15e373ab770d" id: "darwinfpv-cineape35-fpv-drone-rtf" manufacturer: "DarwinFPV" name: "DarwinFPV CineApe35 FPV Drone RTF" weight_g: 0.0 }
receivers { uuid: "06340112-52f1-4e61-a6b9-9b445046672a" id: "darwinfpv-x9-9-long-range-fpv-drone" manufacturer: "DarwinFPV" name: "DarwinFPV X9 9 Long Range FPV Drone" weight_g: 0.0 }
receivers { uuid: "eb956cf3-3526-44d3-aece-2fba2769d932" id: "tx12-mark-ii-elrs-radio-controller" manufacturer: "DarwinFPV" name: "TX12 Mark II  ELRS Radio Controller" weight_g: 363.0 }
receivers { uuid: "0365944c-648b-4698-8247-3e49cb2c263a" id: "babyape-fpv-drone-rtf" manufacturer: "DarwinFPV" name: "BabyApe Ⅱ FPV Drone RTF" weight_g: 363.0 }
receivers { uuid: "9e9b6dc1-6cec-4b53-8404-71f385d966cc" id: "darwinfpv-cineape-25-fpv-kit-rtf" manufacturer: "DarwinFPV" name: "DarwinFPV CineApe 25 FPV Kit RTF" weight_g: 0.0 }
receivers { uuid: "13bc6ae6-64ed-47a2-bf96-7948d1dd8a07" id: "darwinfpv-tx-lite-transmitter-rx-lite-receiver" manufacturer: "DarwinFPV" name: "DarwinFPV TX-Lite Transmitter+ RX-Lite Receiver" weight_g: 9.0 }
receivers { uuid: "c806dce8-c0d3-4eed-baa3-d3637dff56ff" id: "radiomaster-zorro-elrs-radio-controller" manufacturer: "DarwinFPV" name: "Radiomaster Zorro ELRS Radio Controller" weight_g: 0.0 }
receivers { uuid: "b29c4a31-9589-4310-9032-f30add45dc1c" id: "bayckrc-elrs-2-4g-nano-receiver" manufacturer: "DarwinFPV" name: "BAYCKRC ELRS 2.4G Nano Receiver" weight_g: 0.4 }
receivers { uuid: "cfe3f029-4436-4d4f-8c39-45b64ab2480b" id: "darwinfpv-baby-ape-v4-pro-fpv-rtf" manufacturer: "DarwinFPV" name: "DarwinFPV Baby Ape V4 Pro FPV RTF" weight_g: 0.0 }
receivers { uuid: "1f80f913-6d35-46d5-b8f3-a6fac688c1e8" id: "darwinfpv-radiomaster-r81-receiver" manufacturer: "DarwinFPV" name: "DarwinFPV Radiomaster R81 Receiver" weight_g: 2.0 }
receivers { uuid: "f933d265-7b34-4fc7-8653-d554f0ec3377" id: "darwin-vantac-elrs-2-4g-lite-tx-module" manufacturer: "DarwinFPV" name: "Darwin Vantac ELRS 2.4G Lite TX Module" weight_g: 0.0 }
receivers { uuid: "cc5e07ca-8023-4e89-838a-9159519f5d37" id: "darwin-240-johnny-5-quadcopters" manufacturer: "DarwinFPV" name: "Darwin 240 Johnny 5 Quadcopters" weight_g: 0.0 }
receivers { uuid: "09ba67c2-0e9b-4de5-9077-52fe76f019e6" id: "hummingbird-v4-1-complete-fly-repair-bundle" manufacturer: "NewBeeDrone" name: "Hummingbird V4.1 Complete Fly & Repair Bundle" weight_g: 0.0 }
receivers { uuid: "69e4d6cf-d2eb-4fdf-82fb-402110d7dc72" id: "newbeedrone-beet-antenna-60mm-75mm-90mm-for-elrs-2-4ghz-receiver-u-fl-connector" manufacturer: "NewBeeDrone" name: "NewBeeDrone BeeT-Antenna 60mm/75mm/90mm for ELRS 2.4GHz Receiver - U.FL Connector" weight_g: 0.0 }
receivers { uuid: "050d0f5a-f7ae-4dec-b6d1-a41558feb767" id: "newbeedrone-x-hummingbird-v3-1-brushless-rtf-bundle-kit" manufacturer: "NewBeeDrone" name: "NewBeeDrone x Hummingbird V3.1 Brushless RTF Bundle Kit" weight_g: 0.0 }
receivers { uuid: "bca03052-55c8-4316-93ce-2c5f982c43d2" id: "newbeedrone-beet-antenna-for-expresslrs-elrs-2-4ghz-receiver-mhf3-connector" manufacturer: "NewBeeDrone" name: "NewBeeDrone BeeT-Antenna for  ExpressLRS(ELRS) 2.4GHz receiver MHF3 Connector" weight_g: 0.0 }
receivers { uuid: "24d82dfe-b2da-4a1d-8806-ce08177ee974" id: "newbeedrone-acrobee75-blv5-bnf-elrs2-4g-2s-the-ultimate-outdoor-whoop" manufacturer: "NewBeeDrone" name: "NewBeeDrone AcroBee75 BLV5 BNF ELRS2.4G 2S - The Ultimate Outdoor Whoop" weight_g: 36.4 }
receivers { uuid: "2ba447bb-15d2-4896-8cf1-4b486bc3e4d2" id: "newbeedrone-beeceiver-elrs-2-4ghz-diversity-with-tcxo-oscillator-micro-receiver" manufacturer: "NewBeeDrone" name: "NewBeeDrone BeeCeiver ELRS 2.4Ghz Diversity with TCXO Oscillator Micro Receiver" weight_g: 1.6 }
receivers { uuid: "b547e4d8-b817-4fc0-bb0f-db60138f08b0" id: "newbeedrone-beebrainbl-hummingbird-receiver-connector-type-mhf3-pack-of-4" manufacturer: "NewBeeDrone" name: "NewBeeDrone BeeBrainBL/Hummingbird Receiver Connector Type:MHF3 (pack of 4)" weight_g: 0.0 }
receivers { uuid: "530e5efd-d1bb-424e-b0f1-1064de30f739" id: "newbeedrone-beet-antenna-for-expresslrs-elrs-2-4ghz-receiver-mhf3-connector-blv4" manufacturer: "NewBeeDrone" name: "NewBeeDrone BeeT-Antenna for  ExpressLRS(ELRS) 2.4GHz receiver MHF3 Connector /BLV4" weight_g: 0.0 }
receivers { uuid: "aaa79858-fea1-4549-8bae-a09ee919fb0c" id: "newbeedrone-2-4g-replacement-receiver-antennas-60mm-for-beebrain-blv3-blv4-hmb-f4-v2" manufacturer: "NewBeeDrone" name: "NewBeeDrone 2.4G Replacement Receiver Antennas 60mm for BeeBrain BLV3/BLV4/HMB F4 V2" weight_g: 0.0 }
receivers { uuid: "4d391994-744e-4976-9b20-40769fcb84e3" id: "newbeedrone-vim-v2-replacement-parts" manufacturer: "NewBeeDrone" name: "NewBeeDrone VIM V2 Replacement Parts" weight_g: 0.0 }
receivers { uuid: "e51765f9-11b4-4ad8-b7fb-799d0cf03853" id: "hdo-analog-fpv-goggles-ndaa" manufacturer: "Fat Shark" name: "HDO+ Analog FPV Goggles - NDAA" weight_g: 235.8 }
receivers { uuid: "74fbbdf0-df6f-4c8b-818c-7bdd9e0a3f50" id: "cinemini-2-5-3d-prints-bundle-dji-o4" manufacturer: "Rotor Riot" name: "CineMini 2.5 3D Prints Bundle - DJI O4" weight_g: 0.0 }
receivers { uuid: "9e56e02f-05e9-4c40-b828-e695085ed6ff" id: "futaba-r7208sb-fasstest-bi-directional-communication-system-s-bus-s-bus2-port-and-8-channels-receiver" manufacturer: "Futaba" name: "Futaba R7208SB – FASSTest Bi-Directional Communication System S.Bus/S.Bus2 Port and 8 Channels Receiver" weight_g: 12.0 }
receivers { uuid: "5ba541e7-32f8-4dab-bd3e-577a688eaed2" id: "tanq-2-6s-5-pro-spec-by-let-sflyrc-built-tuned-drone-dji-o4-pro-elrs" manufacturer: "Rotor Riot Builds" name: "Tanq 2 6S 5 Pro-Spec by Let'sFlyRC Built & Tuned Drone - DJI O4 Pro / ELRS" weight_g: 0.0 }
receivers { uuid: "1d42b4e5-7718-437c-a628-1492e309ee9a" id: "fat-shark-recon-hd-goggle-bundle" manufacturer: "Rotor Riot Store" name: "Fat Shark Recon HD Goggle Bundle" weight_g: 46.22 }
receivers { uuid: "05b57d96-0e1f-40a5-85ab-6c526b2b3dfd" id: "pocket-radio-controller-fat-shark-edition-elrs" manufacturer: "RadioMaster" name: "Pocket Radio Controller (Fat Shark Edition) - ELRS" weight_g: 288.0 }
receivers { uuid: "7f62485f-0acc-42aa-a8a2-ae83754f762e" id: "vision40-2s-40mm-built-tuned-drone-dji-o4-dji" manufacturer: "Rotor Riot Builds" name: "Vision40 2S 40mm Built & Tuned Drone - DJI O4 / DJI" weight_g: 0.0 }
receivers { uuid: "38fb0403-8016-4121-aae6-3cd708029677" id: "tx15-radio-controller-expresslrs" manufacturer: "RadioMaster" name: "TX15 Radio Controller ExpressLRS" weight_g: 605.0 }
receivers { uuid: "408b4e05-d84a-422d-ae3c-77e57cd397a0" id: "tx15-max-radio-controller-expresslrs" manufacturer: "RadioMaster" name: "TX15 Max Radio Controller ExpressLRS" weight_g: 672.0 }
receivers { uuid: "64c9aa8d-ae4c-4b3b-a0ad-935cc333d9b3" id: "tbs-tango-2-pro-radio-controller-crossfire-ndaa" manufacturer: "Team Black Sheep" name: "TBS Tango 2 Pro Radio Controller - Crossfire - NDAA" weight_g: 0.0 }
receivers { uuid: "4ef89b0e-331d-45fd-b423-ca4da78abf4b" id: "tbs-crossfire-tx-lite-transmitter-module-ndaa" manufacturer: "Team Black Sheep" name: "TBS Crossfire TX LITE Transmitter Module - NDAA" weight_g: 76.0 }
receivers { uuid: "b311c8d5-fa9a-4784-befc-b39959d5405e" id: "nano-diversity-915mhz-receiver-for-crossfire-protocol-ndaa" manufacturer: "Team Black Sheep" name: "Nano Diversity 915MHz Receiver For Crossfire Protocol - NDAA" weight_g: 1.8 }
receivers { uuid: "c3cf5a50-49e7-4abb-85dc-d4838cd79dc8" id: "nano-pro-915mhz-receiver-for-crossfire-protocol-ndaa" manufacturer: "Team Black Sheep" name: "Nano PRO 915MHz Receiver For Crossfire Protocol - NDAA" weight_g: 0.5 }
receivers { uuid: "42fe0671-fbda-4db0-a83e-b823901f3ae9" id: "nano-se-915mhz-receiver-for-crossfire-protocol-ndaa" manufacturer: "Team Black Sheep" name: "Nano SE 915MHz Receiver For Crossfire Protocol - NDAA" weight_g: 0.5 }
receivers { uuid: "e850edff-2101-44c9-937c-5b38a1763347" id: "cinemini-immortal-t-elrs-antenna-mount" manufacturer: "Noozle3D" name: "CineMini Immortal T / ELRS Antenna Mount" weight_g: 0.0 }
receivers { uuid: "73821dad-229c-45fd-b51b-3922f30f81e3" id: "cl2-immortal-t-elrs-dual-antenna-mount" manufacturer: "Noozle3D" name: "CL2 Immortal T / ELRS Dual Antenna Mount" weight_g: 0.0 }
receivers { uuid: "05e3ddf4-08ac-4780-859e-ac6870549df1" id: "xr4-gemini-xrossband-dual-band-receiver-for-elrs-protocol" manufacturer: "RadioMaster" name: "XR4 Gemini Xrossband Dual-Band  Receiver for ELRS Protocol" weight_g: 1.7 }
receivers { uuid: "28977cec-969d-4d92-9b16-6e9c516268a7" id: "xr3-nano-multi-frequency-antenna-diversity-receiver-for-elrs-protocol" manufacturer: "RadioMaster" name: "XR3 Nano Multi-Frequency Antenna Diversity Receiver for ELRS Protocol" weight_g: 1.3 }
receivers { uuid: "bf4e2885-7181-4a6c-9118-5cca4499d2d5" id: "xr2-nano-2-4ghz-receiver-for-elrs-protocol" manufacturer: "RadioMaster" name: "XR2 Nano 2.4GHz Receiver for ELRS Protocol" weight_g: 0.8 }
receivers { uuid: "9879bb38-ca1c-4ffe-9cf3-72eaebc9e247" id: "xr1-nano-multi-frequency-receiver-for-elrs-protocol" manufacturer: "RadioMaster" name: "XR1 Nano Multi-Frequency Receiver for ELRS Protocol" weight_g: 1.0 }
receivers { uuid: "f09e0ee1-81f6-47ae-b897-6f43121c1999" id: "gx12-dual-band-radio-controller-elrs" manufacturer: "RadioMaster" name: "GX12 Dual-Band Radio Controller - ELRS" weight_g: 573.0 }
receivers { uuid: "520f7a81-96ef-4871-8e96-fbe1ea4cef17" id: "shorty-pro-spec-rx-mount" manufacturer: "Noozle3D" name: "Shorty Pro-Spec RX Mount" weight_g: 0.0 }
receivers { uuid: "d8fbb5ef-5906-4c51-86d4-93dc02d808db" id: "punch-pro-spec-rx-cap-buzzer-mount" manufacturer: "Noozle3D" name: "Punch Pro-Spec RX / Cap / Buzzer Mount" weight_g: 0.0 }
receivers { uuid: "f097bd52-fd62-449c-8ce2-ab575f3486b5" id: "dbr4-dual-band-xross-gemini-receiver-for-elrs-protocol" manufacturer: "RadioMaster" name: "DBR4 Dual Band Xross Gemini Receiver for ELRS Protocol" weight_g: 0.0 }
receivers { uuid: "ca4576e9-6377-492e-8c8a-076b3ad532cd" id: "nomad-elrs-dual-1w-gemini-xrossband-tx-module" manufacturer: "RadioMaster" name: "Nomad ELRS Dual 1W Gemini Xrossband TX Module" weight_g: 87.2 }
receivers { uuid: "559f5ec3-c0c9-4195-a8b4-d82f91bf5d5a" id: "skylite-skyliner-mk3-immortal-t-elrs-antenna-mount-mjf-tpu" manufacturer: "Rotor Riot" name: "Skylite / Skyliner MK3 Immortal T / ELRS Antenna Mount - MJF TPU" weight_g: 0.0 }
receivers { uuid: "060b187c-ac58-4b71-bd51-ec460e997f2f" id: "moongoat-sma-immortal-t-elrs-antenna-mount" manufacturer: "Noozle3D" name: "Moongoat SMA & Immortal T / ELRS Antenna Mount" weight_g: 0.0 }
receivers { uuid: "c3267858-3d07-46f3-b7a6-fcfe1ece2eae" id: "bandit-elrs-1w-915mhz-micro-tx-module" manufacturer: "RadioMaster" name: "Bandit ELRS 1W 915MHz Micro TX Module" weight_g: 78.0 }
receivers { uuid: "44a4b619-5c83-456c-bf85-03981ebcbe39" id: "bandit-elrs-1w-915mhz-tx-module" manufacturer: "RadioMaster" name: "Bandit ELRS 1W 915MHz TX Module" weight_g: 155.0 }
receivers { uuid: "15a78b08-6b9d-4cd4-b8da-eab722a5c0b6" id: "bandit-915-868mhz-receiver-antenna-choose-version" manufacturer: "RadioMaster" name: "Bandit 915/868MHz Receiver Antenna - Choose Version" weight_g: 2.02 }
receivers { uuid: "672113ce-49f5-4332-9e18-be04a69d294f" id: "diversity-915-868mhz-receiver-for-elrs-protocol" manufacturer: "Foxeer" name: "Diversity 915/868MHz Receiver For ELRS Protocol" weight_g: 0.0 }
receivers { uuid: "a7403159-829e-4116-bb92-66915c5efd03" id: "rp4td-2-4ghz-true-diversity-receiver-for-elrs-protocol" manufacturer: "RadioMaster" name: "RP4TD 2.4GHz True Diversity Receiver For ELRS Protocol" weight_g: 1.4 }
receivers { uuid: "ecc6e86b-998f-4375-b24f-40aed7da6b62" id: "rp3-2-4ghz-diversity-receiver-for-elrs-protocol" manufacturer: "RadioMaster" name: "RP3 2.4GHz Diversity Receiver For ELRS Protocol" weight_g: 4.6 }
receivers { uuid: "91dc84ee-f938-46d9-ba6f-0c07b1bb9780" id: "bandit-br1-915mhz-receiver-for-elrs-protocol" manufacturer: "RadioMaster" name: "Bandit BR1 915MHz Receiver For ELRS Protocol" weight_g: 1.7 }
receivers { uuid: "ab29292b-32b7-4c96-b8e2-01d7b6f9e872" id: "bandit-elrs-1w-915mhz-nano-tx-module" manufacturer: "RadioMaster" name: "Bandit ELRS 1W 915MHz Nano TX Module" weight_g: 62.5 }
receivers { uuid: "33c6f658-dc70-432e-b91e-28627fd3daf4" id: "tx16s-mkii-radio-controller-elrs" manufacturer: "RadioMaster" name: "TX16S MKII Radio Controller - ELRS" weight_g: 750.0 }
receivers { uuid: "7669de2d-b70f-49af-b88f-d259e734ece8" id: "skylite-skyliner-mk3-gps-immortal-t-elrs-antenna-mount-choose-color" manufacturer: "Noozle3D" name: "Skylite / Skyliner MK3 GPS & Immortal T / ELRS Antenna Mount - Choose Color" weight_g: 0.0 }
receivers { uuid: "dbb28b80-e0f5-47e3-a43d-c3a6844d458e" id: "tanq-2-immortal-t-elrs-antenna-mount" manufacturer: "Noozle3D" name: "TANQ 2 Immortal T / ELRS Antenna Mount" weight_g: 0.0 }
receivers { uuid: "2cb2b59f-dae7-4cfc-857a-01d27acdffda" id: "tanq-gps-immortal-t-elrs-antenna-mount" manufacturer: "Noozle3D" name: "TANQ GPS & Immortal T / ELRS Antenna Mount" weight_g: 0.0 }
receivers { uuid: "3ed20c2c-30c3-4f97-9b12-e67783358338" id: "boxer-edgetx-rotor-riot-edition-radio-controller-elrs" manufacturer: "RadioMaster" name: "Boxer EdgeTX Rotor Riot Edition Radio Controller - ELRS" weight_g: 532.5 }
receivers { uuid: "b0bd9beb-7bb9-4d1e-8cf1-18b77c6e0db6" id: "er6gv-2-4ghz-pwm-receiver-for-elrs-protocol" manufacturer: "RadioMaster" name: "ER6GV 2.4GHz PWM Receiver For ELRS Protocol" weight_g: 5.0 }
receivers { uuid: "5b7c0520-cb97-4e22-b5f3-a4edbf73b52e" id: "er4-2-4ghz-pwm-receiver-for-elrs-protocol" manufacturer: "RadioMaster" name: "ER4 2.4GHz PWM Receiver For ELRS Protocol" weight_g: 0.0 }
receivers { uuid: "951dde96-0f7b-4e4a-816c-3f15510ff181" id: "ranger-elrs-1w-2-4ghz-nano-tx-module" manufacturer: "RadioMaster" name: "Ranger ELRS 1W 2.4GHz Nano TX Module" weight_g: 48.0 }
receivers { uuid: "e071ec94-14e6-49c9-bec2-97c96985c82c" id: "nano-915mhz-receiver-for-crossfire-protocol" manufacturer: "Team Black Sheep" name: "Nano 915MHz Receiver For Crossfire Protocol" weight_g: 0.5 }
receivers { uuid: "0f982523-6bd6-4945-aa83-915fdc6fb31c" id: "ranger-elrs-1w-2-4ghz-micro-tx-module" manufacturer: "RadioMaster" name: "Ranger ELRS 1W 2.4GHz Micro TX Module" weight_g: 48.0 }
receivers { uuid: "efa81e48-010d-41f5-b97d-c5cd610f8537" id: "t-antenna-915-868mhz-receiver-for-elrs-protocol" manufacturer: "Foxeer" name: "T Antenna 915/868MHz Receiver For ELRS Protocol" weight_g: 1.0 }
receivers { uuid: "a27cc5c3-2618-42fe-9293-36117886ad81" id: "915-868mhz-elrs-t-antenna-choose-version" manufacturer: "Foxeer" name: "915/868MHz ELRS T Antenna - Choose Version" weight_g: 7.5 }
receivers { uuid: "20c49d34-3ad9-4524-b97a-92d9d11afd66" id: "2-4ghz-elrs-t-antenna-choose-version" manufacturer: "Foxeer" name: "2.4GHz ELRS T Antenna - Choose Version" weight_g: 1.5 }
receivers { uuid: "7627d6f9-546e-4d5f-8bed-18690922ed72" id: "t-antenna-2-4ghz-receiver-with-lna-pa-for-elrs-protocol" manufacturer: "Foxeer" name: "T Antenna 2.4GHz Receiver with LNA & PA For ELRS Protocol" weight_g: 0.7 }
receivers { uuid: "2a91ec4e-f9c9-4621-baba-54d9a4a95df0" id: "lite-2-4ghz-receiver-for-elrs-protocol" manufacturer: "Foxeer" name: "Lite 2.4GHz Receiver For ELRS Protocol" weight_g: 0.5 }
receivers { uuid: "2564e023-f481-4f07-b425-c422db8635bc" id: "d-pole-mkii-2-4ghz-receiver-antenna" manufacturer: "TrueRC" name: "D-Pole MKII 2.4GHz Receiver Antenna" weight_g: 2.0 }
receivers { uuid: "b97646b5-36b1-4f47-8b2b-02fd52c36ffc" id: "crossfire-micro-dipole-915mhz-rc-receiver-antenna" manufacturer: "Team Black Sheep" name: "Crossfire Micro Dipole 915MHz RC Receiver Antenna" weight_g: 0.0 }
receivers { uuid: "c732909f-fe63-465b-9254-8f1473a887ae" id: "tto-2-4ghz-receiver-for-ghost-protocol-ndaa" manufacturer: "ImmersionRC" name: "Átto 2.4Ghz Receiver For Ghost Protocol - NDAA" weight_g: 0.0 }
receivers { uuid: "0d05650c-67d1-4f05-8eb3-a98f99e7afab" id: "tanq-immortal-t-elrs-antenna-mount" manufacturer: "Noozle3D" name: "TANQ Immortal T / ELRS Antenna Mount" weight_g: 0.0 }
receivers { uuid: "2d765e03-27ec-44b5-80de-fc4b34f3cb8a" id: "2-4ghz-t-antenna-for-rp1-and-ep1-choose-version" manufacturer: "RadioMaster" name: "2.4GHz T Antenna for RP1 and EP1 - Choose Version" weight_g: 1.76 }
receivers { uuid: "2fa34f32-3a3f-4b29-ab4c-770382bdb17f" id: "ranger-elrs-1w-2-4ghz-tx-module" manufacturer: "RadioMaster" name: "Ranger ELRS 1W 2.4GHz TX Module" weight_g: 138.0 }
receivers { uuid: "92e2fe1e-d923-429f-bd3d-baa7524e8540" id: "rp2-2-4ghz-receiver-for-elrs-protocol" manufacturer: "RadioMaster" name: "RP2 2.4GHz Receiver For ELRS Protocol" weight_g: 0.55 }
receivers { uuid: "0458032f-ee20-42d2-bebb-374e96ac6d1c" id: "qt-2-4ghz-receiver-antenna-for-ghost-tto" manufacturer: "ImmersionRC" name: "qT 2.4GHz Receiver Antenna for Ghost Átto" weight_g: 0.0 }
receivers { uuid: "5370b5a2-6ab4-4bae-b075-5fdd980638c1" id: "hook-v2-immortal-t-elrs-antenna-mount" manufacturer: "Noozle3D" name: "Hook V2 Immortal T / ELRS Antenna Mount" weight_g: 0.0 }
receivers { uuid: "12b82422-0edc-4322-b133-d1910cab14a7" id: "tanq-1-2-rx-mounting-plate" manufacturer: "Rotor Riot" name: "TANQ 1 & 2 RX Mounting Plate" weight_g: 0.0 }
receivers { uuid: "bfd41ccc-5c80-402e-a0eb-83113bea64eb" id: "rp1-2-4ghz-receiver-for-elrs-protocol" manufacturer: "RadioMaster" name: "RP1 2.4GHz Receiver For ELRS Protocol" weight_g: 2.2 }
receivers { uuid: "04236b1e-6324-4189-82e1-52d03bb302f2" id: "skylite-skyliner-mk3-immortal-t-elrs-antenna-mount-choose-color" manufacturer: "Noozle3D" name: "Skylite / Skyliner MK3 Immortal T / ELRS Antenna Mount - Choose Color" weight_g: 0.0 }
receivers { uuid: "71675fc1-287d-479d-b2d9-31c1475a8025" id: "cl2-immortal-t-elrs-antenna-mount-choose-color" manufacturer: "Noozle3D" name: "CL2 Immortal T / ELRS Antenna Mount - Choose Color" weight_g: 0.0 }
receivers { uuid: "af6dae50-fd6b-4ffe-b085-1c26ac9291e2" id: "moxy-immortal-t-elrs-antenna-mount" manufacturer: "Noozle3D" name: "Moxy Immortal T / ELRS Antenna Mount" weight_g: 0.0 }
receivers { uuid: "ea69f9ad-eb3e-45ca-8253-6e8f27dc924c" id: "tx16s-mkii-max-joshua-bardwell-edition-radio-controller-elrs" manufacturer: "RadioMaster" name: "TX16S MKII MAX Joshua Bardwell Edition Radio Controller - ELRS" weight_g: 750.0 }
receivers { uuid: "946d1044-bd3d-4df9-afcc-2dce894e14ef" id: "tx16s-mk2-max-rotor-riot-edition-radio-controller-elrs" manufacturer: "RadioMaster" name: "TX16S MK2 Max Rotor Riot Edition Radio Controller - ELRS" weight_g: 750.0 }
receivers { uuid: "fe626740-df3d-4908-9df5-ffc17472e5d2" id: "minimortal-t-915mhz-rc-receiver-antenna" manufacturer: "FPV Cycle" name: "Minimortal T 915MHz RC Receiver Antenna" weight_g: 0.7 }
receivers { uuid: "753345d9-331a-493b-acfc-9e0ef35d50e5" id: "tracer-100mw-2-4ghz-micro-tx-module" manufacturer: "Team Black Sheep" name: "Tracer 100mW 2.4GHz Micro TX Module" weight_g: 0.0 }
receivers { uuid: "0d7625cc-5b89-49ad-bf3e-71237c6956a0" id: "tracer-100mw-2-4ghz-nano-tx-module" manufacturer: "Team Black Sheep" name: "Tracer 100mW 2.4GHz Nano TX Module" weight_g: 0.0 }
receivers { uuid: "07c7b9e4-7f2a-48b4-8700-746d47c2978c" id: "nano-2-4ghz-receiver-for-tracer-protocol" manufacturer: "Team Black Sheep" name: "Nano 2.4GHz Receiver for Tracer Protocol" weight_g: 0.5 }
receivers { uuid: "c88191b1-ffba-4f6c-8503-2a59d0dc3695" id: "tx12-mkii-radio-controller-elrs" manufacturer: "RadioMaster" name: "TX12 MKII Radio Controller - ELRS" weight_g: 363.0 }
receivers { uuid: "b9ca0b68-e7f3-41f8-9ee4-ebbcbaaa144e" id: "r81-2-4ghz-receiver-for-frsky-protocol" manufacturer: "RadioMaster" name: "R81 2.4GHz Receiver For FrSky Protocol" weight_g: 2.0 }
receivers { uuid: "fe533574-3969-41c1-ab4d-cf17d734fe14" id: "immersionrc-ghost-rx-mounting-board-3-pack-ndaa-choose-version" manufacturer: "ImmersionRC" name: "ImmersionRC Ghost RX Mounting Board 3-Pack - NDAA - Choose Version" weight_g: 0.0 }
receivers { uuid: "263237f5-d824-430d-ba2f-992f3660d27b" id: "cl1-hd1-immortal-t-elrs-antenna-mount-choose-color" manufacturer: "Noozle3D" name: "CL1 & HD1 Immortal T / ELRS Antenna Mount - Choose Color" weight_g: 0.0 }
receivers { uuid: "515dd422-2230-4a19-8447-c530b270653b" id: "rekon-5-inch-rocket-8s-2-5w-elrs-2-4-915-dual-band" manufacturer: "HGLRC" name: "Rekon 5-inch Rocket 8S 2.5W Elrs 2.4/915 dual-band" weight_g: 0.0 }
receivers { uuid: "6d081d63-fb8a-4517-b2ff-6585fc62bac6" id: "hglrc-gemini-elrs-915mhz-2-4ghz-dual-band-single-dual-antenna-receiver" manufacturer: "HGLRC" name: "HGLRC Gemini ELRS 915MHz & 2.4GHz Dual-Band Single/Dual Antenna Receiver" weight_g: 0.0 }
receivers { uuid: "77eb2616-829b-4220-8165-44acd991621b" id: "hglrc-d200-soccer-drone-rtf-kit-crash-resistant-training-quadcopter" manufacturer: "HGLRC" name: "HGLRC D200 Soccer Drone RTF Kit - Crash-Resistant Training Quadcopter" weight_g: 0.0 }
receivers { uuid: "bf625697-9254-48b3-baba-6b3fbf6c2a03" id: "hglrc-talon-2-inch-entry-level-rtf-set" manufacturer: "HGLRC" name: "HGLRC Talon 2-inch entry-level RTF Set" weight_g: 0.0 }
receivers { uuid: "677f3561-5f8d-46f6-a298-2bbf2477de1a" id: "hglrc-petrel-75whoop-1s-entry-level-rtf-set" manufacturer: "HGLRC" name: "HGLRC Petrel 75Whoop 1S Entry-level RTF Set" weight_g: 0.0 }
receivers { uuid: "9e867034-9e97-428f-9293-346a7314cc5a" id: "hglrc-elrs-t-one-tx-module" manufacturer: "HGLRC" name: "HGLRC ELRS T ONE TX Module" weight_g: 76.0 }
receivers { uuid: "8e10399e-49b7-497d-a585-f79dc1eabf61" id: "hglrc-elrs-gemini-rx-dual-receiver-2-4g-915mhz" manufacturer: "HGLRC" name: "HGLRC ELRS GEMINI RX dual receiver 2.4G/915Mhz" weight_g: 0.0 }
receivers { uuid: "6c32ff51-2c05-47da-8627-c2a76f918f47" id: "hglrc-elrs-2-4g-receiver" manufacturer: "HGLRC" name: "HGLRC ELRS 2.4G Receiver" weight_g: 0.0 }
receivers { uuid: "090e27cd-9d42-490d-b8ac-af524f833435" id: "diatone-roma-f7-6s-pnp-bnf-drone-msr-tbs-receiver" manufacturer: "DIATONE OFFICIAL" name: "DIATONE Roma F7 6S PNP/BNF Drone MSR/TBS Receiver" weight_g: 0.0 }
receivers { uuid: "b8305249-a23c-4258-a718-cb9378ecf0ca" id: "diatone-roma-f4-dji-4-6s-drone-msr-tbs-receiver" manufacturer: "DIATONE INNOVATIONS" name: "DIATONE Roma F4 DJI 4/6S Drone MSR/TBS Receiver" weight_g: 0.0 }
receivers { uuid: "08e1a7d7-58c6-48aa-87d6-e177fc9dc395" id: "fifty5-flash-2306-hq-5-5x3-5x3-bundle-kit" manufacturer: "FlyFishRC" name: "FIFTY5 Flash 2306 HQ 5.5x3.5x3 Bundle Kit" weight_g: 127.7 }
receivers { uuid: "9d847c71-31d8-4697-baa2-70174d806dbf" id: "fifty5-sword-2207-bundle-kit" manufacturer: "FlyFish RC" name: "FIFTY5 Sword 2207 Bundle Kit" weight_g: 127.7 }
receivers { uuid: "4b4f95b2-da12-4c22-b54f-2563ec4dc7ca" id: "clearance-sale-sub250-microradio-elrs-2-4g-transmitter" manufacturer: "Sub250" name: "(Clearance Sale) Sub250 MicroRadio Elrs 2.4g Transmitter" weight_g: 0.0 }
receivers { uuid: "d8497c69-c03d-4430-ab4d-b35c0a068b71" id: "sub250-nimble65-rtf-combo" manufacturer: "sub250" name: "Sub250 Nimble65 RTF Combo" weight_g: 21.0 }
receivers { uuid: "12ff7e0d-0e05-4065-aa44-4b0b88c19733" id: "sub250-elrs-lite-2-4g-receiver" manufacturer: "Sub250" name: "Sub250 ELRS Lite 2.4G Receiver" weight_g: 0.7 }
receivers { uuid: "d676a9f6-b295-4212-9758-ce819ebbfcc6" id: "sub250-elrs-nano-pro-2-4g-receiver" manufacturer: "Sub250" name: "Sub250 ELRS Nano Pro 2.4G Receiver" weight_g: 0.7 }
receivers { uuid: "3f1f6603-164a-476e-a05f-d90c701f42d8" id: "sub250-elrs-nano-2-4g-receiver" manufacturer: "Sub250" name: "Sub250 ELRS Nano 2.4G Receiver" weight_g: 0.6 }
receivers { uuid: "2c79cc2d-a773-4305-b0a9-ae06f15b8fff" id: "sub250-1s-nanofly16-1-6-inch-freestyle-quadcopter" manufacturer: "Sub250" name: "Sub250 1s Nanofly16  1.6 inch Freestyle Quadcopter" weight_g: 0.0 }
receivers { uuid: "57277db0-6c37-4b84-80e4-825997ba1299" id: "heat-shrink-20mm-x-1m" manufacturer: "FPVCycle" name: "Heat Shrink - 20mm x 1M" weight_g: 0.0 }
