-- Code generated by protoc-gen-sql. DO NOT EDIT.

CREATE TABLE IF NOT EXISTS antennas (
    uuid UUID,
    PRIMARY KEY (uuid),
    id TEXT UNIQUE,
    manufacturer TEXT,
    model TEXT,
    weight_g DECIMAL,
    connector TEXT,
    polarization TEXT,
    frequency_band_ghz DECIMAL,
    length_mm DECIMAL,
    gain_dbi DECIMAL
);

CREATE INDEX IF NOT EXISTS idx_antennas_manufacturer ON antennas (manufacturer);

CREATE TABLE IF NOT EXISTS batteries (
    uuid UUID,
    PRIMARY KEY (uuid),
    id TEXT UNIQUE,
    manufacturer TEXT,
    model TEXT,
    weight_g DECIMAL,
    capacity_mah INTEGER,
    cell_count_s INTEGER,
    chemistry TEXT,
    connector TEXT
);

CREATE INDEX IF NOT EXISTS idx_batteries_manufacturer ON batteries (manufacturer);
CREATE INDEX IF NOT EXISTS idx_batteries_cell_count_s ON batteries (cell_count_s);

CREATE TABLE IF NOT EXISTS builds (
    uuid UUID,
    PRIMARY KEY (uuid),
    id TEXT UNIQUE,
    name TEXT,
    description TEXT,
    frame_uuid UUID,
    FOREIGN KEY (frame_uuid) REFERENCES frames(uuid),
    motor_uuid UUID,
    FOREIGN KEY (motor_uuid) REFERENCES motors(uuid),
    battery_uuid UUID,
    FOREIGN KEY (battery_uuid) REFERENCES batteries(uuid),
    flight_controller_uuid UUID,
    FOREIGN KEY (flight_controller_uuid) REFERENCES flight_controllers(uuid),
    esc_uuids UUID[],
    receiver_uuids UUID[],
    antenna_uuids UUID[],
    propeller_uuid UUID,
    FOREIGN KEY (propeller_uuid) REFERENCES propellers(uuid),
    camera_uuids UUID[]
);


CREATE TABLE IF NOT EXISTS cameras (
    uuid UUID,
    PRIMARY KEY (uuid),
    id TEXT UNIQUE,
    manufacturer TEXT,
    model TEXT,
    weight_g DECIMAL,
    protocol TEXT,
    sensor_size TEXT,
    width_mm INTEGER,
    lens_size_mm DECIMAL
);

CREATE INDEX IF NOT EXISTS idx_cameras_manufacturer ON cameras (manufacturer);

CREATE TABLE IF NOT EXISTS escs (
    uuid UUID,
    PRIMARY KEY (uuid),
    id TEXT UNIQUE,
    manufacturer TEXT,
    model TEXT,
    weight_g DECIMAL,
    max_motors INTEGER,
    continuous_amps INTEGER,
    burst_amps INTEGER,
    firmware TEXT
);

CREATE INDEX IF NOT EXISTS idx_escs_manufacturer ON escs (manufacturer);

CREATE TABLE IF NOT EXISTS flight_controllers (
    uuid UUID,
    PRIMARY KEY (uuid),
    id TEXT UNIQUE,
    manufacturer TEXT,
    model TEXT,
    weight_g DECIMAL,
    processor TEXT,
    gyro TEXT,
    internal_esc_uuid UUID,
    FOREIGN KEY (internal_esc_uuid) REFERENCES escs(uuid),
    internal_receiver_uuid UUID,
    FOREIGN KEY (internal_receiver_uuid) REFERENCES receivers(uuid),
    internal_vtx_uuid UUID,
    FOREIGN KEY (internal_vtx_uuid) REFERENCES video_transmitters(uuid)
);

CREATE INDEX IF NOT EXISTS idx_flight_controllers_manufacturer ON flight_controllers (manufacturer);

CREATE TABLE IF NOT EXISTS frames (
    uuid UUID,
    PRIMARY KEY (uuid),
    id TEXT UNIQUE,
    manufacturer TEXT,
    model TEXT,
    weight_g DECIMAL,
    wheelbase_mm DECIMAL,
    max_prop_size_inches DECIMAL,
    geometry TEXT
);

CREATE INDEX IF NOT EXISTS idx_frames_manufacturer ON frames (manufacturer);

CREATE TABLE IF NOT EXISTS motors (
    uuid UUID,
    PRIMARY KEY (uuid),
    id TEXT UNIQUE,
    manufacturer TEXT,
    model TEXT,
    weight_g DECIMAL,
    stator_diameter_mm DECIMAL,
    stator_height_mm DECIMAL,
    kv INTEGER
);

CREATE INDEX IF NOT EXISTS idx_motors_manufacturer ON motors (manufacturer);
CREATE INDEX IF NOT EXISTS idx_motors_kv ON motors (kv);

CREATE TABLE IF NOT EXISTS propellers (
    uuid UUID,
    PRIMARY KEY (uuid),
    id TEXT UNIQUE,
    manufacturer TEXT,
    model TEXT,
    weight_g DECIMAL,
    diameter_inches DECIMAL,
    pitch_inches DECIMAL,
    blades INTEGER,
    material TEXT
);

CREATE INDEX IF NOT EXISTS idx_propellers_manufacturer ON propellers (manufacturer);

CREATE TABLE IF NOT EXISTS receivers (
    uuid UUID,
    PRIMARY KEY (uuid),
    id TEXT UNIQUE,
    manufacturer TEXT,
    model TEXT,
    weight_g DECIMAL,
    protocol TEXT,
    frequency_band_ghz DECIMAL,
    has_telemetry BOOLEAN,
    antenna_uuids UUID[]
);

CREATE INDEX IF NOT EXISTS idx_receivers_manufacturer ON receivers (manufacturer);
CREATE INDEX IF NOT EXISTS idx_receivers_protocol ON receivers (protocol);

CREATE TABLE IF NOT EXISTS video_transmitters (
    uuid UUID,
    PRIMARY KEY (uuid),
    id TEXT UNIQUE,
    manufacturer TEXT,
    model TEXT,
    weight_g DECIMAL,
    protocol TEXT,
    max_power_mw INTEGER,
    input_voltage_min_v DECIMAL,
    input_voltage_max_v DECIMAL,
    antenna_uuids UUID[]
);

CREATE INDEX IF NOT EXISTS idx_video_transmitters_manufacturer ON video_transmitters (manufacturer);
CREATE INDEX IF NOT EXISTS idx_video_transmitters_protocol ON video_transmitters (protocol);

