-- Code generated by protoc-gen-sql. DO NOT EDIT.
CREATE TABLE IF NOT EXISTS antennas (
  uuid UUID,
  PRIMARY KEY (uuid),
  id TEXT UNIQUE,
  manufacturer TEXT,
  name TEXT,
  is_internal_only BOOLEAN,
  weight_g DECIMAL,
  connector TEXT,
  polarization TEXT,
  frequency_band_mhz INTEGER,
  length_mm DECIMAL,
  gain_dbi DECIMAL
);

CREATE INDEX IF NOT EXISTS idx_antennas_manufacturer ON antennas (manufacturer);

CREATE TABLE IF NOT EXISTS batteries (
  uuid UUID,
  PRIMARY KEY (uuid),
  id TEXT UNIQUE,
  manufacturer TEXT,
  name TEXT,
  weight_g DECIMAL,
  capacity_mah INTEGER,
  cell_count_s INTEGER,
  chemistry TEXT,
  connector TEXT
);

CREATE INDEX IF NOT EXISTS idx_batteries_manufacturer ON batteries (manufacturer);

CREATE INDEX IF NOT EXISTS idx_batteries_cell_count_s ON batteries (cell_count_s);

CREATE TABLE IF NOT EXISTS builds (
  uuid UUID,
  PRIMARY KEY (uuid),
  id TEXT UNIQUE,
  name TEXT,
  description TEXT,
  frame_uuid UUID,
  motor_uuid UUID,
  battery_uuid UUID,
  flight_controller_uuid UUID,
  esc_uuids UUID[],
  receiver_uuids UUID[],
  antenna_uuids UUID[],
  propeller_uuid UUID,
  camera_uuids UUID[]
);

CREATE TABLE IF NOT EXISTS cameras (
  uuid UUID,
  PRIMARY KEY (uuid),
  id TEXT UNIQUE,
  manufacturer TEXT,
  name TEXT,
  is_internal_only BOOLEAN,
  weight_g DECIMAL,
  protocol TEXT,
  sensor_size TEXT,
  width_mm INTEGER,
  lens_size_mm DECIMAL
);

CREATE INDEX IF NOT EXISTS idx_cameras_manufacturer ON cameras (manufacturer);

CREATE TABLE IF NOT EXISTS escs (
  uuid UUID,
  PRIMARY KEY (uuid),
  id TEXT UNIQUE,
  manufacturer TEXT,
  name TEXT,
  is_internal_only BOOLEAN,
  weight_g DECIMAL,
  max_motors INTEGER,
  motor_current_max_a DECIMAL,
  motor_current_burst_a DECIMAL,
  firmware TEXT
);

CREATE INDEX IF NOT EXISTS idx_escs_manufacturer ON escs (manufacturer);

CREATE TABLE IF NOT EXISTS flight_controllers (
  uuid UUID,
  PRIMARY KEY (uuid),
  id TEXT UNIQUE,
  manufacturer TEXT,
  name TEXT,
  is_internal_only BOOLEAN,
  weight_g DECIMAL,
  processor TEXT,
  gyro TEXT,
  internal_esc_uuid UUID,
  internal_receiver_uuid UUID,
  internal_vtx_uuid UUID
);

CREATE INDEX IF NOT EXISTS idx_flight_controllers_manufacturer ON flight_controllers (manufacturer);

CREATE TABLE IF NOT EXISTS frames (
  uuid UUID,
  PRIMARY KEY (uuid),
  id TEXT UNIQUE,
  manufacturer TEXT,
  name TEXT,
  weight_g DECIMAL,
  wheelbase_mm DECIMAL,
  max_prop_size_mm DECIMAL,
  geometry TEXT
);

CREATE INDEX IF NOT EXISTS idx_frames_manufacturer ON frames (manufacturer);

CREATE TABLE IF NOT EXISTS motors (
  uuid UUID,
  PRIMARY KEY (uuid),
  id TEXT UNIQUE,
  manufacturer TEXT,
  name TEXT,
  weight_g DECIMAL,
  stator_diameter_mm DECIMAL,
  stator_height_mm DECIMAL,
  kv INTEGER
);

CREATE INDEX IF NOT EXISTS idx_motors_manufacturer ON motors (manufacturer);

CREATE INDEX IF NOT EXISTS idx_motors_kv ON motors (kv);

CREATE TABLE IF NOT EXISTS propellers (
  uuid UUID,
  PRIMARY KEY (uuid),
  id TEXT UNIQUE,
  manufacturer TEXT,
  name TEXT,
  weight_g DECIMAL,
  diameter_mm DECIMAL,
  pitch_mm DECIMAL,
  blades INTEGER,
  material TEXT
);

CREATE INDEX IF NOT EXISTS idx_propellers_manufacturer ON propellers (manufacturer);

CREATE TABLE IF NOT EXISTS receivers (
  uuid UUID,
  PRIMARY KEY (uuid),
  id TEXT UNIQUE,
  manufacturer TEXT,
  name TEXT,
  is_internal_only BOOLEAN,
  weight_g DECIMAL,
  protocol TEXT,
  frequency_band_mhz INTEGER,
  has_telemetry BOOLEAN,
  antenna_uuids UUID[]
);

CREATE INDEX IF NOT EXISTS idx_receivers_manufacturer ON receivers (manufacturer);

CREATE INDEX IF NOT EXISTS idx_receivers_protocol ON receivers (protocol);

CREATE TABLE IF NOT EXISTS video_transmitters (
  uuid UUID,
  PRIMARY KEY (uuid),
  id TEXT UNIQUE,
  manufacturer TEXT,
  name TEXT,
  is_internal_only BOOLEAN,
  weight_g DECIMAL,
  protocol TEXT,
  max_power_mw INTEGER,
  input_voltage_min_v DECIMAL,
  input_voltage_max_v DECIMAL,
  antenna_uuids UUID[]
);

CREATE INDEX IF NOT EXISTS idx_video_transmitters_manufacturer ON video_transmitters (manufacturer);

CREATE INDEX IF NOT EXISTS idx_video_transmitters_protocol ON video_transmitters (protocol);

-- Foreign Keys
ALTER TABLE builds
ADD CONSTRAINT fk_builds_frame_uuid FOREIGN KEY (frame_uuid) REFERENCES frames (uuid);

ALTER TABLE builds
ADD CONSTRAINT fk_builds_motor_uuid FOREIGN KEY (motor_uuid) REFERENCES motors (uuid);

ALTER TABLE builds
ADD CONSTRAINT fk_builds_battery_uuid FOREIGN KEY (battery_uuid) REFERENCES batteries (uuid);

ALTER TABLE builds
ADD CONSTRAINT fk_builds_flight_controller_uuid FOREIGN KEY (flight_controller_uuid) REFERENCES flight_controllers (uuid);

ALTER TABLE builds
ADD CONSTRAINT fk_builds_propeller_uuid FOREIGN KEY (propeller_uuid) REFERENCES propellers (uuid);

ALTER TABLE flight_controllers
ADD CONSTRAINT fk_flight_controllers_internal_esc_uuid FOREIGN KEY (internal_esc_uuid) REFERENCES escs (uuid);

ALTER TABLE flight_controllers
ADD CONSTRAINT fk_flight_controllers_internal_receiver_uuid FOREIGN KEY (internal_receiver_uuid) REFERENCES receivers (uuid);

ALTER TABLE flight_controllers
ADD CONSTRAINT fk_flight_controllers_internal_vtx_uuid FOREIGN KEY (internal_vtx_uuid) REFERENCES video_transmitters (uuid);
