syntax = "proto3";

package quadsmith;

import "google/protobuf/descriptor.proto";

option go_package = "quadsmith/api/gen/quadsmith";

// ---------------------------------------------------------
// Entity Naming Options
// ---------------------------------------------------------

message NameOptions {
  // Title case with spaces (e.g., "Video Transmitter")
  string singular = 1;

  // Title case with spaces (e.g., "Video Transmitters")
  string plural = 2;
}

extend google.protobuf.MessageOptions {
  NameOptions name = 50002;
}
