syntax = "proto3";

package quadsmith;

import "google/protobuf/descriptor.proto";

option go_package = "quadsmith/api/gen/quadsmith";

// ---------------------------------------------------------
// Entity Naming Options
// ---------------------------------------------------------

message NameOptions {
  // Title case with spaces (e.g., "Video Transmitter")
  string singular = 1;

  // Title case with spaces (e.g., "Video Transmitters")
  string plural = 2;

  // Kebab case (e.g., "video-transmitters")
  string cli = 3;

  // Kebab case (e.g., "video-transmitters")
  string api = 4;

  // Camel case (e.g., "videoTransmitter")
  string go = 5;

  // Pascal case (e.g., "VideoTransmitter")
  string typescript = 6;

  // Snake case (e.g., "video_transmitters")
  string sql = 7;
}

extend google.protobuf.MessageOptions {
  NameOptions name = 50002;
}
