edition = "2023";

import "google/protobuf/go_features.proto";
option features.(pb.go).api_level = API_OPAQUE;


package quadsmith;
option go_package = "quadsmith/api/gen/quadsmith;quadsmith";

import "google/protobuf/field_mask.proto";
import "quadsmith/common.proto";
import "quadsmith/component.proto";

message ChangeRequest {
  enum Action {
    UNKNOWN_ACTION = 0;
    CREATE = 1;
    UPDATE = 2;
    DELETE = 3;
  }
  
  enum Status {
    UNKNOWN_STATUS = 0;
    PENDING = 1;
    APPROVED = 2;
    REJECTED = 3;
    MERGED = 4;
  }

  string id = 1;
  string user_id = 2;
  string component_id = 3; // Null if proposing a brand new component
  string target_type = 4;
  Action action = 5;
  Component proposed_component = 6;
  google.protobuf.FieldMask update_mask = 7; // Precise fields changed for updates
  string rationale = 8;
  Status status = 9;
  string merged_into_id = 10;
  int64 created_at_unix_ms = 11;
  int64 updated_at_unix_ms = 12;
}

message ChangeRequestVote {
  string id = 1;
  string request_id = 2;
  string user_id = 3;
  bool is_upvote = 4;
  int64 created_at_unix_ms = 5;
}
