edition = "2023";

import "google/protobuf/go_features.proto";
option features.(pb.go).api_level = API_OPAQUE;

package quadsmith;
option go_package = "quadsmith/api/gen/quadsmith;quadsmith";

import "google/protobuf/descriptor.proto";

extend google.protobuf.MessageOptions {
  string plural_name = 50000;
  repeated string default_columns = 50001;
}

message ReferenceLink {
  enum Type {
    UNSPECIFIED = 0;
    PURCHASE = 1;
    MANUAL = 2;
    FIRMWARE = 3;
    DATASHEET = 4;
  }
  string id = 1;
  string url = 2;
  Type link_type = 3;
  string title = 4;
  string description = 5;
  string company_id = 6;
}

message ReleaseDate {
  int32 year = 1;
  int32 month = 2 [features.field_presence = EXPLICIT];
  int32 day = 3 [features.field_presence = EXPLICIT];
}

message Ecosystem {
  enum Value {
    UNSPECIFIED = 0;
    ANALOG = 1;
    DJI = 2;
    HDZERO = 3;
    WALKSNAIL = 4;
    AVATAR = 5;
  }
}

message AntennaConnector {
  enum Value {
    UNSPECIFIED = 0;
    SMA = 1;
    RP_SMA = 2;
    UFL = 3;
    MMCX = 4;
  }
}

message AntennaPolarization {
  enum Value {
    UNSPECIFIED = 0;
    RHCP = 1;
    LHCP = 2;
    LINEAR = 3;
  }
}

message ScrewSize {
  enum Value {
    UNSPECIFIED = 0;
    M2 = 1;
    M2_5 = 2;
    M3 = 3;
  }
}

message PropellerMount {
  enum Value {
    UNSPECIFIED = 0;
    M5_SHAFT = 1;
    T_MOUNT_1_5MM = 2;
    T_MOUNT_2MM = 3;
  }
}

message VideoStandard {
  enum Value {
    UNSPECIFIED = 0;
    NTSC = 1;
    PAL = 2;
    MIPI = 3;
  }
}

message AntennaStyle {
  enum Value {
    UNSPECIFIED = 0;
    OMNI = 1;
    DIRECTIONAL = 2;
    PATCH = 3;
  }
}

message ResourceMetadata {
  option (quadsmith.default_columns) = "id";
  option (quadsmith.default_columns) = "name";

  string id = 1;
  string name = 2;
}
