edition = "2023";

import "google/protobuf/go_features.proto";
option features.(pb.go).api_level = API_OPAQUE;


package quadsmith;
option go_package = "quadsmith/api/gen/quadsmith;quadsmith";

message CompatibilityMessage {
  enum Severity {
    UNSPECIFIED = 0;
    DEFINITE_INCOMPATIBILITY = 1;
    HEURISTIC_INCOMPATIBILITY = 2;
    PARTIAL_COMPATIBILITY = 3;
    INFORMATIONAL = 4;
  }
  Severity severity = 1;
  string message = 2;
  string resolution = 3;
}

message CompatibilityMetric {
  oneof metric_data {
    CurrentDrawMetric current_draw = 1;
    MountMatchMetric mount_match = 2;
    VoltageMetric voltage = 3;
    UartMetric uart = 4;
  }
}

message CurrentDrawMetric {
  double value = 1;
  double max = 2;
  string unit = 3; 
}

message MountMatchMetric {
  repeated string expected = 1;
  repeated string actual = 2;
}

message VoltageMetric {
  double value = 1;
  double min = 2;
  double max = 3;
  string unit = 4; 
}

message UartMetric {
  int32 required = 1;
  int32 available = 2;
}

message CompatibilityResult {
  repeated string component_ids = 1;
  string checker_name = 2;
  CompatibilityMetric metrics = 3;
  repeated CompatibilityMessage messages = 4;
}

message CheckCompatibilityRequest {
  repeated string component_ids = 1; 
}

message CheckCompatibilityResponse {
  repeated CompatibilityResult results = 1;
}
