syntax = "proto3";

package quadsmith;

import "quadsmith/sql.proto";

option go_package = "quadsmith/api/gen/quadsmith";

// ---------------------------------------------------------
// Domain Model
// ---------------------------------------------------------
message Esc {
  option (quadsmith.sql.table_name) = "escs";

  string uuid = 1 [(quadsmith.sql.is_primary_key) = true];

  string id = 2 [(quadsmith.sql.is_unique) = true];

  string manufacturer = 3 [(quadsmith.sql.create_index) = true];
  string name = 4;
  bool is_internal_only = 20;

  float weight_g = 5;

  // E.g., 1 for individual arm ESCs, 4 for 4-in-1 boards, 8 for X8 boards
  uint32 max_motors = 6;

  // Continuous and Burst amperage ratings
  float motor_current_max_a = 7;
  float motor_current_burst_a = 8;

  // E.g., "BLHeli_S", "BLHeli_32", "AM32", "Bluejay"
  string firmware = 9;
  string description = 21;
}

// ---------------------------------------------------------
// RPC Requests & Responses
// ---------------------------------------------------------
message GetEscRequest {
  string id = 1;
  repeated string columns = 2;
}

message ListEscsRequest {
  string filter = 1;
  int32 page_size = 2;
  string page_token = 3;
  repeated string columns = 4;
  repeated string sort = 5;
}

message ListEscsResponse {
  repeated Esc escs = 1;
  string next_page_token = 2;
}

// ---------------------------------------------------------
// gRPC Service
// ---------------------------------------------------------
service EscService {
  rpc GetEsc(GetEscRequest) returns (Esc);
  rpc ListEscs(ListEscsRequest) returns (ListEscsResponse);
}
