edition = "2023";

import "google/protobuf/go_features.proto";
option features.(pb.go).api_level = API_OPAQUE;


package quadsmith;
option go_package = "quadsmith/api/gen/quadsmith;quadsmith";

message EvaluateBuildRequest {
  repeated string component_ids = 1;
   
  double payload_weight_g = 3;
}

message EvaluatorResult {
  double total_mass_g = 1;
  double thrust_to_weight_ratio = 2;
  double max_pitch_speed_kph = 3;
  double max_speed_kph = 4;
  
  // Flight Times (seconds)
  double hover_flight_time_s = 5;
  double cinematic_flight_time_s = 6;
  double freestyle_flight_time_s = 7;
  double racing_flight_time_s = 8;
  
  // Range (meters)
  double aerodynamic_range_m = 9;
  double estimated_rf_range_m = 10;
  
  // Handling metrics
  double disk_loading_g_cm2 = 11;
  double torque_to_inertia_ratio = 12;
  double handling_score = 13; // Dimensionless, 1-10
  
  // Payload curve data
  repeated PayloadCurvePoint payload_curve = 14;
}

message PayloadCurvePoint {
  double payload_weight_g = 1;
  double resulting_twr = 2;
}

message EvaluateBuildResponse {
  EvaluatorResult result = 1;
}
