syntax = "proto3";

package quadsmith;

import "_common.proto";
import "_sql.proto";
import "media.proto";
import "reference_link.proto";

option go_package = "quadsmith/api/gen/quadsmith";

// ---------------------------------------------------------
// Domain Model
// ---------------------------------------------------------
message Frame {
  option (quadsmith.sql.table) = {name: "frames"};
  option (quadsmith.collection_path) = "components/hardware/frames";
  option (quadsmith.frontend) = {
    color_code: "#64748b"
    default_columns: [
      "manufacturer",
      "name",
      "wheelbase_mm",
      "geometry"
    ]
  };

  string uuid = 1 [(quadsmith.sql.column) = {is_primary_key: true}];

  string id = 2 [(quadsmith.sql.column) = {is_unique: true}];

  string manufacturer = 3 [(quadsmith.sql.column) = {create_index: true}];
  string name = 4;

  float weight_g = 5;

  // The diagonal distance between motors in millimeters
  float wheelbase_mm = 6;

  // Maximum propeller size supported
  float max_prop_size_mm = 7;

  // E.g., "True X", "Squashed X", "Deadcat"
  string geometry = 8;
  string description = 9;
  repeated ReferenceLink reference_links = 10;
  optional string primary_display_image = 11;
  repeated Media media = 12;
}

// ---------------------------------------------------------
// RPC Requests & Responses
// ---------------------------------------------------------
message GetFrameRequest {
  string id = 1;
  repeated string columns = 2;
}

message ListFramesRequest {
  string filter = 1;
  int32 page_size = 2;
  string page_token = 3;
  repeated string columns = 4;
  repeated string sort = 5;
}

message ListFramesResponse {
  repeated Frame frames = 1;
  string next_page_token = 2;
}

// ---------------------------------------------------------
// gRPC Service
// ---------------------------------------------------------
service FrameService {
  rpc GetFrame(GetFrameRequest) returns (Frame);
  rpc ListFrames(ListFramesRequest) returns (ListFramesResponse);
}
