edition = "2023";

import "google/protobuf/go_features.proto";
option features.(pb.go).api_level = API_OPAQUE;


package quadsmith;
option go_package = "quadsmith/api/gen/quadsmith;quadsmith";

import "quadsmith/common.proto";

message Radio {
  option (quadsmith.plural_name) = "radios";


  option (quadsmith.default_columns) = "external_bay_type";
  enum ExternalBayType {
    UNSPECIFIED = 0;
    NONE = 1;
    MICRO_JR = 2;
    NANO_LITE = 3;
  }
  repeated string supported_frequency_ids = 1;
  repeated string rf_protocol_ids = 2;
  ExternalBayType external_bay_type = 3;
  int32 antenna_count = 4;
  AntennaConnector.Value antenna_connector = 5;
  AntennaPolarization.Value included_antenna_polarization = 6;
  repeated string supported_os_ids = 7;
  string internal_transmitter_id = 8;
}

message Goggles {
  option (quadsmith.plural_name) = "goggles";


  option (quadsmith.default_columns) = "supported_ecosystems";
  repeated string supported_frequency_ids = 1;
  Ecosystem.Value ecosystem = 2;
  int32 antenna_count = 3;
  AntennaConnector.Value antenna_connector = 4;
  AntennaPolarization.Value included_antenna_polarization = 5;
}

message RadioModule {
  option (quadsmith.plural_name) = "radio-modules";


  option (quadsmith.default_columns) = "compatible_bay_type";
  Radio.ExternalBayType compatible_bay_type = 1;
  string internal_transmitter_id = 2;
}
