syntax = "proto3";

package quadsmith;

import "quadsmith/sql.proto";

option go_package = "quadsmith/api/gen/quadsmith";

// ---------------------------------------------------------
// Domain Model
// ---------------------------------------------------------
message Receiver {
  option (quadsmith.sql.table_name) = "receivers";

  string uuid = 1 [(quadsmith.sql.is_primary_key) = true];
  
  string id = 2 [(quadsmith.sql.is_unique) = true];

  string manufacturer = 3 [(quadsmith.sql.create_index) = true];
  string name = 4;
  
  float weight_g = 5;
  
  // E.g., "ExpressLRS", "Crossfire", "FrSky"
  string protocol = 6 [(quadsmith.sql.create_index) = true];
  
  // E.g., 2.4, 0.9 (for 900MHz)
  float frequency_band_ghz = 7;
  
  bool has_telemetry = 8;
  
  // Array of antenna UUIDs included with or required by this receiver
  repeated string antenna_uuids = 9;
}

// ---------------------------------------------------------
// RPC Requests & Responses
// ---------------------------------------------------------
message GetReceiverRequest {
  string id = 1;
  repeated string columns = 2;
}

message ListReceiversRequest {
  string filter = 1;
  int32 page_size = 2;
  string page_token = 3;
  repeated string columns = 4;
  repeated string sort = 5;
}

message ListReceiversResponse {
  repeated Receiver receivers = 1;
  string next_page_token = 2;
}

// ---------------------------------------------------------
// gRPC Service
// ---------------------------------------------------------
service ReceiverService {
  rpc GetReceiver(GetReceiverRequest) returns (Receiver);
  rpc ListReceivers(ListReceiversRequest) returns (ListReceiversResponse);
}
