package main

import (
	"fmt"
	"strings"

	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/reflect/protoreflect"
	"google.golang.org/protobuf/types/pluginpb"

	quadsmith_sql "quadsmith/api/gen/quadsmith"
)

func main() {
	protogen.Options{}.Run(func(gen *protogen.Plugin) error {
		gen.SupportedFeatures = uint64(pluginpb.CodeGeneratorResponse_FEATURE_PROTO3_OPTIONAL)
		g := gen.NewGeneratedFile("schema.sql", "")
		g.P("-- Code generated by protoc-gen-sql. DO NOT EDIT.")
		g.P()

		var alterStatements []string

		for _, f := range gen.Files {
			if !f.Generate {
				continue
			}

			for _, msg := range f.Messages {
				alters := generateTable(g, msg)
				alterStatements = append(alterStatements, alters...)
			}
		}

		g.P("-- Foreign Keys")
		for _, stmt := range alterStatements {
			g.P(stmt)
		}

		return nil
	})
}

func toSnakeCase(s string) string {
	words := strings.Fields(s)
	for i, w := range words {
		words[i] = strings.ToLower(w)
	}
	return strings.Join(words, "_")
}

func getTableName(msg *protogen.Message) string {
	opts := msg.Desc.Options()
	if proto.HasExtension(opts, quadsmith_sql.E_Table) {
		if tblOpts, ok := proto.GetExtension(opts, quadsmith_sql.E_Table).(*quadsmith_sql.TableOptions); ok && tblOpts != nil && tblOpts.Name != "" {
			return tblOpts.Name
		}
	}
	if proto.HasExtension(opts, quadsmith_sql.E_Name) {
		if nameOpts, ok := proto.GetExtension(opts, quadsmith_sql.E_Name).(*quadsmith_sql.NameOptions); ok && nameOpts != nil && nameOpts.Plural != "" {
			return toSnakeCase(nameOpts.Plural)
		}
	}
	return ""
}

func generateTable(g *protogen.GeneratedFile, msg *protogen.Message) []string {
	tableName := getTableName(msg)
	if tableName == "" {
		return nil
	}

	g.P("CREATE TABLE IF NOT EXISTS ", tableName, " (")

	var defs []string
	var alters []string

	for _, field := range msg.Fields {
		fOpts := field.Desc.Options()

		var colOpt *quadsmith_sql.ColumnOptions
		if proto.HasExtension(fOpts, quadsmith_sql.E_Column) {
			if co, ok := proto.GetExtension(fOpts, quadsmith_sql.E_Column).(*quadsmith_sql.ColumnOptions); ok && co != nil {
				colOpt = co
			}
		}

		colName := string(field.Desc.Name())
		if colOpt != nil && colOpt.Name != "" {
			colName = colOpt.Name
		}
		colType := sqlDataType(field.Desc)

		if colOpt != nil && colOpt.IsUnique {
			colType += " UNIQUE"
		}

		if !field.Desc.IsList() && !field.Desc.HasPresence() {
			colType += " NOT NULL"
		}

		defs = append(defs, fmt.Sprintf("%s %s", colName, colType))

		// Check primary key
		if colOpt != nil && colOpt.IsPrimaryKey {
			defs = append(defs, fmt.Sprintf("PRIMARY KEY (%s)", colName))
		}

		// Check foreign key
		if colOpt != nil && colOpt.References != "" {
			alters = append(alters, fmt.Sprintf("ALTER TABLE %s ADD CONSTRAINT fk_%s_%s FOREIGN KEY (%s) REFERENCES %s;", tableName, tableName, colName, colName, colOpt.References))
		}
	}

	g.P("    ", strings.Join(defs, ",\n    "))
	g.P(");")
	g.P()

	// Generate indexes
	for _, field := range msg.Fields {
		fOpts := field.Desc.Options()
		if proto.HasExtension(fOpts, quadsmith_sql.E_Column) {
			if co, ok := proto.GetExtension(fOpts, quadsmith_sql.E_Column).(*quadsmith_sql.ColumnOptions); ok && co != nil && co.CreateIndex {
				colName := string(field.Desc.Name())
				if co.Name != "" {
					colName = co.Name
				}
				g.P("CREATE INDEX IF NOT EXISTS idx_", tableName, "_", colName, " ON ", tableName, " (", colName, ");")
			}
		}
	}
	g.P()
	return alters
}

func sqlDataType(desc protoreflect.FieldDescriptor) string {
	name := string(desc.Name())
	kind := desc.Kind()

	if desc.IsList() {
		if kind == protoreflect.StringKind {
			if strings.HasSuffix(name, "uuids") {
				return "UUID[]"
			}
			return "TEXT[]"
		}
		if kind == protoreflect.MessageKind {
			return "JSONB"
		}
	}

	if strings.HasSuffix(name, "uuid") && kind == protoreflect.StringKind {
		return "UUID"
	}
	switch kind {
	case protoreflect.MessageKind:
		return "JSONB"
	case protoreflect.StringKind:
		return "TEXT"
	case protoreflect.Int32Kind, protoreflect.Uint32Kind, protoreflect.EnumKind:
		return "INTEGER"
	case protoreflect.Int64Kind, protoreflect.Uint64Kind:
		return "BIGINT"
	case protoreflect.FloatKind, protoreflect.DoubleKind:
		return "DECIMAL"
	case protoreflect.BoolKind:
		return "BOOLEAN"
	default:
		return "TEXT"
	}
}
