package main

import (
	"fmt"
	"strings"

	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/reflect/protoreflect"

	quadsmith_sql "quadsmith/api/gen/quadsmith"
)

func main() {
	protogen.Options{}.Run(func(gen *protogen.Plugin) error {
		for _, f := range gen.Files {
			if !f.Generate {
				continue
			}
			generateFile(gen, f)
		}
		return nil
	})
}

func generateFile(gen *protogen.Plugin, file *protogen.File) {
	hasTables := false
	for _, msg := range file.Messages {
		if proto.HasExtension(msg.Desc.Options(), quadsmith_sql.E_TableName) {
			hasTables = true
			break
		}
	}
	if !hasTables {
		return
	}

	filename := file.GeneratedFilenamePrefix + "_store.pb.go"
	g := gen.NewGeneratedFile(filename, file.GoImportPath)

	g.P("// Code generated by protoc-gen-store. DO NOT EDIT.")
	g.P("package ", file.GoPackageName)
	g.P()
	g.P(`import (`)
	g.P(`	"context"
	"strings"`)
	g.P(`	"github.com/jackc/pgx/v5"`)
	g.P(`	"github.com/jackc/pgx/v5/pgxpool"`)
	g.P(`)`)
	g.P()

	for _, msg := range file.Messages {
		generateStoreForMessage(g, msg)
	}
}

func generateStoreForMessage(g *protogen.GeneratedFile, msg *protogen.Message) {
	opts := msg.Desc.Options()
	if !proto.HasExtension(opts, quadsmith_sql.E_TableName) {
		return
	}

	tableName := proto.GetExtension(opts, quadsmith_sql.E_TableName).(string)
	msgName := msg.GoIdent.GoName

	var colNames []string
	var placeHolders []string
	var mFields []string
	var scanVars []string
	var scanAddrs []string
	var assignments []string

	for i, field := range msg.Fields {
		colName := string(field.Desc.Name())
		colNames = append(colNames, colName)
		placeHolders = append(placeHolders, fmt.Sprintf("$%d", i+1))
		
		goName := field.GoName
		if strings.HasSuffix(colName, "uuid") {
				mFields = append(mFields, "func(s string) interface{} { if s == \"\" { return nil }; return s }(m."+goName+")")
			} else if strings.HasSuffix(colName, "uuids") {
				mFields = append(mFields, "func(s []string) interface{} { if len(s) == 0 { return nil }; return s }(m."+goName+")")
			} else {
				mFields = append(mFields, "m."+goName)
			}

		varType := goDataType(field.Desc)
		scanVarName := "v_" + colName
		
		if field.Desc.IsList() {
			scanVars = append(scanVars, fmt.Sprintf("var %s %s", scanVarName, varType))
			scanAddrs = append(scanAddrs, "&"+scanVarName)
			assignments = append(assignments, fmt.Sprintf("m.%s = %s", goName, scanVarName))
		} else {
			scanVars = append(scanVars, fmt.Sprintf("var %s *%s", scanVarName, varType))
			scanAddrs = append(scanAddrs, "&"+scanVarName)
			assignments = append(assignments, fmt.Sprintf("if %s != nil { m.%s = *%s }", scanVarName, goName, scanVarName))
		}
	}

	colsStr := strings.Join(colNames, ", ")
	valsStr := strings.Join(placeHolders, ", ")
	mFieldsStr := strings.Join(mFields, ", ")

	// --- CREATE ---
	g.P("func Create", msgName, "(ctx context.Context, tx pgx.Tx, m *", msgName, ") error {")
	g.P("	query := `INSERT INTO ", tableName, " (", colsStr, ") VALUES (", valsStr, ")`")
	g.P("	_, err := tx.Exec(ctx, query, ", mFieldsStr, ")")
	g.P("	return err")
	g.P("}")
	g.P()

	
	// --- GET ---
	g.P("func Get", msgName, "(ctx context.Context, db *pgxpool.Pool, idOrUuid string, cols []string) (*", msgName, ", error) {")
	g.P("	colsStr := \"", colsStr, "\"")
	g.P("	if len(cols) > 0 {")
	g.P("		colsStr = strings.Join(cols, \", \")")
	g.P("	} else {")
	g.P("       cols = []string{\"" + strings.ReplaceAll(colsStr, ", ", "\", \"") + "\"}")
	g.P("   }")
	g.P("	query := `SELECT ` + colsStr + ` FROM ", tableName, " WHERE id = $1 OR uuid::text = $1 LIMIT 1`")
	
	g.P("	scanArgs := make([]interface{}, len(cols))")
	g.P("	m := &", msgName, "{}")
	g.P("	for i, col := range cols {")
	g.P("		switch col {")
	for j, colName := range colNames {
		g.P("		case \"", colName, "\":")
		g.P("			scanArgs[i] = &m.", msg.Fields[j].GoName)
	}
	g.P("		default:")
	g.P("			var dummy interface{}")
	g.P("			scanArgs[i] = &dummy")
	g.P("		}")
	g.P("	}")

	g.P("	err := db.QueryRow(ctx, query, idOrUuid).Scan(scanArgs...)")
	g.P("	if err != nil {")
	g.P("		return nil, err")
	g.P("	}")
	g.P("	return m, nil")
	g.P("}")
	g.P()

	// --- UPDATE ---
	var updateSets []string
	var updateArgs []string
	updateArgs = append(updateArgs, "m.Uuid")
	
	argIdx := 2
	for i, colName := range colNames {
		if colName == "uuid" || colName == "id" {
			continue
		}
		updateSets = append(updateSets, fmt.Sprintf("%s = $%d", colName, argIdx))
		updateArgs = append(updateArgs, mFields[i])
		argIdx++
	}
	
	updateSetsStr := strings.Join(updateSets, ", ")
	updateArgsStr := strings.Join(updateArgs, ", ")

	g.P("func Update", msgName, "(ctx context.Context, tx pgx.Tx, m *", msgName, ") error {")
	g.P("	query := `UPDATE ", tableName, " SET ", updateSetsStr, " WHERE uuid = $1`")
	g.P("	_, err := tx.Exec(ctx, query, ", updateArgsStr, ")")
	g.P("	return err")
	g.P("}")
	g.P()

	// --- DELETE ---
	g.P("func Delete", msgName, "(ctx context.Context, tx pgx.Tx, idOrUuid string) error {")
	g.P("	query := `DELETE FROM ", tableName, " WHERE id = $1 OR uuid::text = $1`")
	g.P("	_, err := tx.Exec(ctx, query, idOrUuid)")
	g.P("	return err")
	g.P("}")
	g.P()

	// --- LIST ---
	pluralName := msgName + "s"
	if strings.HasSuffix(msgName, "y") {
		pluralName = strings.TrimSuffix(msgName, "y") + "ies"
	}
	
	g.P("func List", pluralName, "(ctx context.Context, db *pgxpool.Pool, cols []string, whereClause string, args ...any) ([]*", msgName, ", error) {")
	g.P("	colsStr := \"", colsStr, "\"")
	g.P("	if len(cols) > 0 {")
	g.P("		colsStr = strings.Join(cols, \", \")")
	g.P("	} else {")
	g.P("       cols = []string{\"" + strings.ReplaceAll(colsStr, ", ", "\", \"") + "\"}")
	g.P("   }")
	g.P("	query := `SELECT ` + colsStr + ` FROM ", tableName, "`")
	g.P("	if whereClause != \"\" {")
	g.P("		query += \" WHERE \" + whereClause")
	g.P("	}")
	g.P("	rows, err := db.Query(ctx, query, args...)")
	g.P("	if err != nil {")
	g.P("		return nil, err")
	g.P("	}")
	g.P("	defer rows.Close()")
	g.P("	results := make([]*", msgName, ", 0)")
	g.P("	for rows.Next() {")
	
	g.P("		scanArgs := make([]interface{}, len(cols))")
	g.P("		m := &", msgName, "{}")
	g.P("		for i, col := range cols {")
	g.P("			switch col {")
	for j, colName := range colNames {
		g.P("			case \"", colName, "\":")
		g.P("				scanArgs[i] = &m.", msg.Fields[j].GoName)
	}
	g.P("			default:")
	g.P("				var dummy interface{}")
	g.P("				scanArgs[i] = &dummy")
	g.P("			}")
	g.P("		}")
	g.P("		err := rows.Scan(scanArgs...)")
	g.P("		if err != nil {")
	g.P("			return nil, err")
	g.P("		}")
	g.P("		results = append(results, m)")
	g.P("	}")
	g.P("	return results, nil")
	g.P("}")
	g.P()

}

func goDataType(desc protoreflect.FieldDescriptor) string {
	if desc.IsList() {
		switch desc.Kind() {
		case protoreflect.StringKind:
			return "[]string"
		}
		return "[]interface{}"
	}
	switch desc.Kind() {
	case protoreflect.StringKind:
		return "string"
	case protoreflect.Int32Kind:
		return "int32"
	case protoreflect.Int64Kind:
		return "int64"
	case protoreflect.Uint32Kind:
		return "uint32"
	case protoreflect.Uint64Kind:
		return "uint64"
	case protoreflect.FloatKind:
		return "float32"
	case protoreflect.DoubleKind:
		return "float64"
	case protoreflect.BoolKind:
		return "bool"
	default:
		return "string"
	}
}
