package main

import (
	"fmt"
	"strings"

	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/reflect/protoreflect"

	quadsmith_sql "quadsmith/api/gen/quadsmith"
)

func main() {
	protogen.Options{}.Run(func(gen *protogen.Plugin) error {
		for _, f := range gen.Files {
			if !f.Generate {
				continue
			}
			generateFile(gen, f)
		}
		return nil
	})
}

func generateFile(gen *protogen.Plugin, file *protogen.File) {
	hasTables := false
	for _, msg := range file.Messages {
		if proto.HasExtension(msg.Desc.Options(), quadsmith_sql.E_TableName) {
			hasTables = true
			break
		}
	}
	if !hasTables {
		return
	}

	filename := file.GeneratedFilenamePrefix + "_store.pb.go"
	g := gen.NewGeneratedFile(filename, file.GoImportPath)

	g.P("// Code generated by protoc-gen-store. DO NOT EDIT.")
	g.P("package ", file.GoPackageName)
	g.P()
	g.P(`import (`)
	g.P(`	"context"`)
	g.P(`	"github.com/jackc/pgx/v5"`)
	g.P(`	"github.com/jackc/pgx/v5/pgxpool"`)
	g.P(`)`)
	g.P()

	for _, msg := range file.Messages {
		generateStoreForMessage(g, msg)
	}
}

func generateStoreForMessage(g *protogen.GeneratedFile, msg *protogen.Message) {
	opts := msg.Desc.Options()
	if !proto.HasExtension(opts, quadsmith_sql.E_TableName) {
		return
	}

	tableName := proto.GetExtension(opts, quadsmith_sql.E_TableName).(string)
	msgName := msg.GoIdent.GoName

	var colNames []string
	var placeHolders []string
	var mFields []string
	var scanVars []string
	var scanAddrs []string
	var assignments []string

	for i, field := range msg.Fields {
		colName := string(field.Desc.Name())
		colNames = append(colNames, colName)
		placeHolders = append(placeHolders, fmt.Sprintf("$%d", i+1))
		
		goName := field.GoName
		mFields = append(mFields, "m."+goName)

		varType := goDataType(field.Desc)
		scanVarName := "v_" + colName
		
		if field.Desc.IsList() {
			scanVars = append(scanVars, fmt.Sprintf("var %s %s", scanVarName, varType))
			scanAddrs = append(scanAddrs, "&"+scanVarName)
			assignments = append(assignments, fmt.Sprintf("m.%s = %s", goName, scanVarName))
		} else {
			scanVars = append(scanVars, fmt.Sprintf("var %s *%s", scanVarName, varType))
			scanAddrs = append(scanAddrs, "&"+scanVarName)
			assignments = append(assignments, fmt.Sprintf("if %s != nil { m.%s = *%s }", scanVarName, goName, scanVarName))
		}
	}

	colsStr := strings.Join(colNames, ", ")
	valsStr := strings.Join(placeHolders, ", ")
	mFieldsStr := strings.Join(mFields, ", ")
	scanAddrsStr := strings.Join(scanAddrs, ", ")

	// --- CREATE ---
	g.P("func Create", msgName, "(ctx context.Context, tx pgx.Tx, m *", msgName, ") error {")
	g.P("	query := `INSERT INTO ", tableName, " (", colsStr, ") VALUES (", valsStr, ")`")
	g.P("	_, err := tx.Exec(ctx, query, ", mFieldsStr, ")")
	g.P("	return err")
	g.P("}")
	g.P()

	// --- GET ---
	g.P("func Get", msgName, "(ctx context.Context, db *pgxpool.Pool, idOrUuid string) (*", msgName, ", error) {")
	g.P("	query := `SELECT ", colsStr, " FROM ", tableName, " WHERE id = $1 OR uuid::text = $1 LIMIT 1`")
	for _, v := range scanVars {
		g.P("	", v)
	}
	g.P("	err := db.QueryRow(ctx, query, idOrUuid).Scan(", scanAddrsStr, ")")
	g.P("	if err != nil {")
	g.P("		return nil, err")
	g.P("	}")
	g.P("	m := &", msgName, "{}")
	for _, a := range assignments {
		g.P("	", a)
	}
	g.P("	return m, nil")
	g.P("}")
	g.P()

	// --- DELETE ---
	g.P("func Delete", msgName, "(ctx context.Context, tx pgx.Tx, idOrUuid string) error {")
	g.P("	query := `DELETE FROM ", tableName, " WHERE id = $1 OR uuid::text = $1`")
	g.P("	_, err := tx.Exec(ctx, query, idOrUuid)")
	g.P("	return err")
	g.P("}")
	g.P()
}

func goDataType(desc protoreflect.FieldDescriptor) string {
	if desc.IsList() {
		switch desc.Kind() {
		case protoreflect.StringKind:
			return "[]string"
		}
		return "[]interface{}"
	}
	switch desc.Kind() {
	case protoreflect.StringKind:
		return "string"
	case protoreflect.Int32Kind:
		return "int32"
	case protoreflect.Int64Kind:
		return "int64"
	case protoreflect.Uint32Kind:
		return "uint32"
	case protoreflect.Uint64Kind:
		return "uint64"
	case protoreflect.FloatKind:
		return "float32"
	case protoreflect.DoubleKind:
		return "float64"
	case protoreflect.BoolKind:
		return "bool"
	default:
		return "string"
	}
}
