package main

import (
	"fmt"
	"sort"
	"strings"

	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/types/pluginpb"
	quadsmith_sql "quadsmith/api/gen/quadsmith"
)

func main() {
	protogen.Options{}.Run(func(gen *protogen.Plugin) error {
		gen.SupportedFeatures = uint64(pluginpb.CodeGeneratorResponse_FEATURE_PROTO3_OPTIONAL)
		for _, f := range gen.Files {
			if !f.Generate {
				continue
			}
			generateFile(gen, f)
		}
		generateSearchRegistry(gen)
		return nil
	})
}

func getTableName(msg *protogen.Message) string {
	opts := msg.Desc.Options()
	if proto.HasExtension(opts, quadsmith_sql.E_Table) {
		if tblOpts, ok := proto.GetExtension(opts, quadsmith_sql.E_Table).(*quadsmith_sql.TableOptions); ok && tblOpts != nil && tblOpts.Name != "" {
			return tblOpts.Name
		}
	}
	return ""
}

func generateFile(gen *protogen.Plugin, file *protogen.File) {
	hasTables := false
	for _, msg := range file.Messages {
		if getTableName(msg) != "" {
			hasTables = true
			break
		}
	}
	if !hasTables {
		return
	}

	filename := file.GeneratedFilenamePrefix + "_server.pb.go"
	g := gen.NewGeneratedFile(filename, file.GoImportPath)

	g.P("// Code generated by protoc-gen-server. DO NOT EDIT.")
	g.P("package ", file.GoPackageName)
	g.P()
	g.P(`import (`)
	g.P(`	"context"`)
	g.P(`	"connectrpc.com/connect"`)
	g.P(`	"github.com/jackc/pgx/v5/pgxpool"`)
	g.P(`	"quadsmith/api/internal/cel2sql"`)
	g.P(`	"quadsmith/api/internal/pagination"`)
	g.P(`)`)
	g.P()

	for _, msg := range file.Messages {
		if getTableName(msg) == "" {
			continue
		}

		msgName := msg.GoIdent.GoName

		// Find the service name
		serviceName := msgName + "Service"

		// We assume pluralization rules based on the name
		pluralName := msgName + "s"
		if strings.HasSuffix(msgName, "y") {
			pluralName = strings.TrimSuffix(msgName, "y") + "ies"
		}

		g.P("type ", serviceName, "Handler struct {")
		g.P("	db *pgxpool.Pool")
		g.P("}")
		g.P()
		g.P("func New", serviceName, "Handler(db *pgxpool.Pool) *", serviceName, "Handler {")
		g.P("	return &", serviceName, "Handler{db: db}")
		g.P("}")
		g.P()

		// Get
		g.P("func (s *", serviceName, "Handler) Get", msgName, "(ctx context.Context, req *connect.Request[Get", msgName, "Request]) (*connect.Response[", msgName, "], error) {")
		g.P("	m, err := Get", msgName, "(ctx, s.db, req.Msg.GetId(), req.Msg.GetColumns())")
		g.P("	if err != nil {")
		g.P("		return nil, connect.NewError(connect.CodeInternal, err)")
		g.P("	}")
		g.P("	return connect.NewResponse(m), nil")
		g.P("}")
		g.P()

		// List
		g.P("func (s *", serviceName, "Handler) List", pluralName, "(ctx context.Context, req *connect.Request[List", pluralName, "Request]) (*connect.Response[List", pluralName, "Response], error) {")
		g.P("	pageSize, err := pagination.ParsePageSize(req.Msg.GetPageSize())")
		g.P("	if err != nil {")
		g.P("		return nil, connect.NewError(connect.CodeInvalidArgument, err)")
		g.P("	}")
		g.P()
		g.P("	filter, sort, offset, err := pagination.ResolveParams(req.Msg.GetFilter(), req.Msg.GetSort(), req.Msg.GetPageToken())")
		g.P("	if err != nil {")
		g.P("		return nil, connect.NewError(connect.CodeInvalidArgument, err)")
		g.P("	}")
		g.P()
		g.P("	where, args, err := cel2sql.Compile(filter)")
		g.P("	if err != nil {")
		g.P("		return nil, connect.NewError(connect.CodeInvalidArgument, err)")
		g.P("	}")
		g.P()
		g.P("	items, err := List", pluralName, "(ctx, s.db, req.Msg.GetColumns(), sort, where, pageSize+1, offset, args...)")
		g.P("	if err != nil {")
		g.P("		if pagination.IsInvalidArgument(err) {")
		g.P("			return nil, connect.NewError(connect.CodeInvalidArgument, err)")
		g.P("		}")
		g.P("		return nil, connect.NewError(connect.CodeInternal, err)")
		g.P("	}")
		g.P()
		g.P("	nextPageToken := \"\"")
		g.P("	if int32(len(items)) > pageSize {")
		g.P("		items = items[:pageSize]")
		g.P("		nextPageToken, err = pagination.EncodePageToken(offset+pageSize, filter, sort)")
		g.P("		if err != nil {")
		g.P("			return nil, connect.NewError(connect.CodeInternal, err)")
		g.P("		}")
		g.P("	}")
		g.P()
		g.P("	res := &List", pluralName, "Response{")
		g.P("		", pluralName, ": items,")
		g.P("		NextPageToken: nextPageToken,")
		g.P("	}")
		g.P("	return connect.NewResponse(res), nil")
		g.P("}")

	}
}

func getCollectionPath(msg *protogen.Message) string {
	opts := msg.Desc.Options()
	if proto.HasExtension(opts, quadsmith_sql.E_CollectionPath) {
		if p, ok := proto.GetExtension(opts, quadsmith_sql.E_CollectionPath).(string); ok && p != "" {
			return strings.Trim(p, "/")
		}
	}
	return ""
}

func getDefaultColumns(msg *protogen.Message) []string {
	opts := msg.Desc.Options()
	if proto.HasExtension(opts, quadsmith_sql.E_Frontend) {
		if fe, ok := proto.GetExtension(opts, quadsmith_sql.E_Frontend).(*quadsmith_sql.FrontendOptions); ok && fe != nil {
			return fe.DefaultColumns
		}
	}
	return nil
}

func generateSearchRegistry(gen *protogen.Plugin) {
	type colInfo struct {
		canonicalPath   string
		tableName       string
		displayName     string
		messageName     string
		hasManufacturer bool
		defaultColumns  []string
		columns         []string
		aliases         []string
	}

	var collections []colInfo

	for _, f := range gen.Files {
		if !f.Generate {
			continue
		}
		for _, msg := range f.Messages {
			tbl := getTableName(msg)
			if tbl == "" {
				continue
			}
			path := getCollectionPath(msg)
			if path == "" {
				continue
			}

			msgName := msg.GoIdent.GoName
			plural := msgName + "s"
			if strings.HasSuffix(msgName, "y") {
				plural = strings.TrimSuffix(msgName, "y") + "ies"
			}

			hasMfr := false
			var cols []string
			for _, field := range msg.Fields {
				fName := string(field.Desc.Name())
				cols = append(cols, fName)
				if fName == "manufacturer" {
					hasMfr = true
				}
			}

			// Generate aliases
			aliasMap := make(map[string]bool)
			aliasMap[path] = true
			parts := strings.Split(path, "/")
			lastPart := parts[len(parts)-1]
			aliasMap[lastPart] = true
			aliasMap[strings.ReplaceAll(lastPart, "-", "_")] = true
			aliasMap[strings.ToLower(msgName)] = true
			aliasMap[strings.ToLower(plural)] = true

			// Well-known shorthand abbreviations
			switch lastPart {
			case "electronic-speed-controllers":
				aliasMap["escs"] = true
				aliasMap["esc"] = true
			case "flight-controllers":
				aliasMap["fcs"] = true
				aliasMap["fc"] = true
			case "video-transmitters":
				aliasMap["vtxs"] = true
				aliasMap["vtx"] = true
			case "gps-receivers":
				aliasMap["gps"] = true
			case "receivers":
				aliasMap["rxs"] = true
				aliasMap["rx"] = true
			}

			var aliases []string
			for a := range aliasMap {
				aliases = append(aliases, a)
			}
			sort.Strings(aliases)

			collections = append(collections, colInfo{
				canonicalPath:   path,
				tableName:       tbl,
				displayName:     plural,
				messageName:     msgName,
				hasManufacturer: hasMfr,
				defaultColumns:  getDefaultColumns(msg),
				columns:         cols,
				aliases:         aliases,
			})
		}
	}

	if len(collections) == 0 {
		return
	}

	sort.Slice(collections, func(i, j int) bool {
		return collections[i].canonicalPath < collections[j].canonicalPath
	})

	g := gen.NewGeneratedFile("search_registry.pb.go", "quadsmith/api/gen/quadsmith")
	g.P("// Code generated by protoc-gen-server. DO NOT EDIT.")
	g.P("package quadsmith")
	g.P()
	g.P(`import "strings"`)
	g.P()
	g.P("type SearchCollectionDef struct {")
	g.P("	CanonicalPath   string")
	g.P("	Aliases         []string")
	g.P("	TableName       string")
	g.P("	DisplayName     string")
	g.P("	MessageName     string")
	g.P("	HasManufacturer bool")
	g.P("	DefaultColumns  []string")
	g.P("	Columns         []string")
	g.P("}")
	g.P()
	g.P("var AllSearchCollections = []*SearchCollectionDef{")
	for _, c := range collections {
		g.P("	{")
		g.P("		CanonicalPath: ", fmt.Sprintf("%q", c.canonicalPath), ",")
		g.P("		Aliases: []string{")
		for _, a := range c.aliases {
			g.P("			", fmt.Sprintf("%q", a), ",")
		}
		g.P("		},")
		g.P("		TableName: ", fmt.Sprintf("%q", c.tableName), ",")
		g.P("		DisplayName: ", fmt.Sprintf("%q", c.displayName), ",")
		g.P("		MessageName: ", fmt.Sprintf("%q", c.messageName), ",")
		g.P("		HasManufacturer: ", c.hasManufacturer, ",")
		g.P("		DefaultColumns: []string{")
		for _, col := range c.defaultColumns {
			g.P("			", fmt.Sprintf("%q", col), ",")
		}
		g.P("		},")
		g.P("		Columns: []string{")
		for _, col := range c.columns {
			g.P("			", fmt.Sprintf("%q", col), ",")
		}
		g.P("		},")
		g.P("	},")
	}
	g.P("}")
	g.P()
	g.P("func NormalizeSearchPath(p string) string {")
	g.P(`	p = strings.Trim(strings.ToLower(strings.TrimSpace(p)), "/")`)
	g.P(`	return strings.ReplaceAll(p, "_", "-")`)
	g.P("}")
	g.P()
	g.P("func LookupSearchCollection(path string) (*SearchCollectionDef, bool) {")
	g.P("	norm := NormalizeSearchPath(path)")
	g.P("	for _, c := range AllSearchCollections {")
	g.P("		if NormalizeSearchPath(c.CanonicalPath) == norm {")
	g.P("			return c, true")
	g.P("		}")
	g.P("		for _, a := range c.Aliases {")
	g.P("			if NormalizeSearchPath(a) == norm {")
	g.P("				return c, true")
	g.P("			}")
	g.P("		}")
	g.P("	}")
	g.P("	return nil, false")
	g.P("}")
}
