package main

import (
	"strings"

	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/types/pluginpb"
	quadsmith_sql "quadsmith/api/gen/quadsmith"
)

func main() {
	protogen.Options{}.Run(func(gen *protogen.Plugin) error {
		gen.SupportedFeatures = uint64(pluginpb.CodeGeneratorResponse_FEATURE_PROTO3_OPTIONAL)
		for _, f := range gen.Files {
			if !f.Generate {
				continue
			}
			generateFile(gen, f)
		}
		return nil
	})
}

func toSnakeCase(s string) string {
	words := strings.Fields(s)
	for i, w := range words {
		words[i] = strings.ToLower(w)
	}
	return strings.Join(words, "_")
}

func getTableName(msg *protogen.Message) string {
	opts := msg.Desc.Options()
	if proto.HasExtension(opts, quadsmith_sql.E_Table) {
		if tblOpts, ok := proto.GetExtension(opts, quadsmith_sql.E_Table).(*quadsmith_sql.TableOptions); ok && tblOpts != nil && tblOpts.Name != "" {
			return tblOpts.Name
		}
	}
	if proto.HasExtension(opts, quadsmith_sql.E_Name) {
		if nameOpts, ok := proto.GetExtension(opts, quadsmith_sql.E_Name).(*quadsmith_sql.NameOptions); ok && nameOpts != nil && nameOpts.Plural != "" {
			return toSnakeCase(nameOpts.Plural)
		}
	}
	return ""
}

func generateFile(gen *protogen.Plugin, file *protogen.File) {
	hasTables := false
	for _, msg := range file.Messages {
		if getTableName(msg) != "" {
			hasTables = true
			break
		}
	}
	if !hasTables {
		return
	}

	filename := file.GeneratedFilenamePrefix + "_server.pb.go"
	g := gen.NewGeneratedFile(filename, file.GoImportPath)

	g.P("// Code generated by protoc-gen-server. DO NOT EDIT.")
	g.P("package ", file.GoPackageName)
	g.P()
	g.P(`import (`)
	g.P(`	"context"`)
	g.P(`	"connectrpc.com/connect"`)
	g.P(`	"github.com/jackc/pgx/v5/pgxpool"`)
	g.P(`	"quadsmith/api/internal/cel2sql"`)
	g.P(`	"quadsmith/api/internal/pagination"`)
	g.P(`)`)
	g.P()

	for _, msg := range file.Messages {
		if getTableName(msg) == "" {
			continue
		}

		msgName := msg.GoIdent.GoName

		// Find the service name
		serviceName := msgName + "Service"

		// We assume pluralization rules based on the name
		pluralName := msgName + "s"
		if strings.HasSuffix(msgName, "y") {
			pluralName = strings.TrimSuffix(msgName, "y") + "ies"
		}

		g.P("type ", serviceName, "Handler struct {")
		g.P("	db *pgxpool.Pool")
		g.P("}")
		g.P()
		g.P("func New", serviceName, "Handler(db *pgxpool.Pool) *", serviceName, "Handler {")
		g.P("	return &", serviceName, "Handler{db: db}")
		g.P("}")
		g.P()

		// Get
		g.P("func (s *", serviceName, "Handler) Get", msgName, "(ctx context.Context, req *connect.Request[Get", msgName, "Request]) (*connect.Response[", msgName, "], error) {")
		g.P("	m, err := Get", msgName, "(ctx, s.db, req.Msg.GetId(), req.Msg.GetColumns())")
		g.P("	if err != nil {")
		g.P("		return nil, connect.NewError(connect.CodeInternal, err)")
		g.P("	}")
		g.P("	return connect.NewResponse(m), nil")
		g.P("}")
		g.P()

		// List
		g.P("func (s *", serviceName, "Handler) List", pluralName, "(ctx context.Context, req *connect.Request[List", pluralName, "Request]) (*connect.Response[List", pluralName, "Response], error) {")
		g.P("	pageSize, err := pagination.ParsePageSize(req.Msg.GetPageSize())")
		g.P("	if err != nil {")
		g.P("		return nil, connect.NewError(connect.CodeInvalidArgument, err)")
		g.P("	}")
		g.P()
		g.P("	filter, sort, offset, err := pagination.ResolveParams(req.Msg.GetFilter(), req.Msg.GetSort(), req.Msg.GetPageToken())")
		g.P("	if err != nil {")
		g.P("		return nil, connect.NewError(connect.CodeInvalidArgument, err)")
		g.P("	}")
		g.P()
		g.P("	where, args, err := cel2sql.Compile(filter)")
		g.P("	if err != nil {")
		g.P("		return nil, connect.NewError(connect.CodeInvalidArgument, err)")
		g.P("	}")
		g.P()
		g.P("	items, err := List", pluralName, "(ctx, s.db, req.Msg.GetColumns(), sort, where, pageSize+1, offset, args...)")
		g.P("	if err != nil {")
		g.P("		if pagination.IsInvalidArgument(err) {")
		g.P("			return nil, connect.NewError(connect.CodeInvalidArgument, err)")
		g.P("		}")
		g.P("		return nil, connect.NewError(connect.CodeInternal, err)")
		g.P("	}")
		g.P()
		g.P("	nextPageToken := \"\"")
		g.P("	if int32(len(items)) > pageSize {")
		g.P("		items = items[:pageSize]")
		g.P("		nextPageToken, err = pagination.EncodePageToken(offset+pageSize, filter, sort)")
		g.P("		if err != nil {")
		g.P("			return nil, connect.NewError(connect.CodeInternal, err)")
		g.P("		}")
		g.P("	}")
		g.P()
		g.P("	res := &List", pluralName, "Response{")
		g.P("		", pluralName, ": items,")
		g.P("		NextPageToken: nextPageToken,")
		g.P("	}")
		g.P("	return connect.NewResponse(res), nil")
		g.P("}")

	}
}
