package main

import (
	"fmt"
	"strings"

	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/reflect/protoreflect"

	quadsmith_sql "quadsmith/api/gen/quadsmith"
)

func main() {
	protogen.Options{}.Run(func(gen *protogen.Plugin) error {
		for _, f := range gen.Files {
			if !f.Generate {
				continue
			}
			generateFile(gen, f)
		}
		return nil
	})
}

func toSnakeCase(s string) string {
	words := strings.Fields(s)
	for i, w := range words {
		words[i] = strings.ToLower(w)
	}
	return strings.Join(words, "_")
}

func getTableName(msg *protogen.Message) string {
	opts := msg.Desc.Options()
	if proto.HasExtension(opts, quadsmith_sql.E_Name) {
		if nameOpts, ok := proto.GetExtension(opts, quadsmith_sql.E_Name).(*quadsmith_sql.NameOptions); ok && nameOpts != nil && nameOpts.Plural != "" {
			return toSnakeCase(nameOpts.Plural)
		}
	}
	if proto.HasExtension(opts, quadsmith_sql.E_TableName) {
		if tn, ok := proto.GetExtension(opts, quadsmith_sql.E_TableName).(string); ok && tn != "" {
			return tn
		}
	}
	return ""
}

func generateFile(gen *protogen.Plugin, file *protogen.File) {
	hasTables := false
	for _, msg := range file.Messages {
		if getTableName(msg) != "" {
			hasTables = true
			break
		}
	}
	if !hasTables {
		return
	}

	filename := file.GeneratedFilenamePrefix + "_store.pb.go"
	g := gen.NewGeneratedFile(filename, file.GoImportPath)

	g.P("// Code generated by protoc-gen-store. DO NOT EDIT.")
	g.P("package ", file.GoPackageName)
	g.P()
	g.P(`import (`)
	g.P(`	"context"`)
	g.P(`	"fmt"`)
	g.P(`	"strings"`)
	g.P(`	"github.com/jackc/pgx/v5"`)
	g.P(`	"github.com/jackc/pgx/v5/pgxpool"`)
	g.P(`	"quadsmith/api/internal/pagination"`)
	g.P(`)`)
	g.P()

	for _, msg := range file.Messages {
		generateStoreForMessage(g, msg)
	}
}

func generateStoreForMessage(g *protogen.GeneratedFile, msg *protogen.Message) {
	tableName := getTableName(msg)
	if tableName == "" {
		return
	}

	msgName := msg.GoIdent.GoName

	var colNames []string
	var placeHolders []string
	var mFields []string
	var scanVars []string
	var scanAddrs []string
	var assignments []string

	for i, field := range msg.Fields {
		colName := string(field.Desc.Name())
		colNames = append(colNames, colName)

		colType := ""
		if proto.HasExtension(field.Desc.Options(), quadsmith_sql.E_ColumnType) {
			if ct, ok := proto.GetExtension(field.Desc.Options(), quadsmith_sql.E_ColumnType).(string); ok && ct != "" {
				colType = ct
			}
		}

		if colType != "" {
			placeHolders = append(placeHolders, fmt.Sprintf("$%d::%s", i+1, colType))
		} else {
			placeHolders = append(placeHolders, fmt.Sprintf("$%d", i+1))
		}

		goName := field.GoName
		if strings.HasSuffix(colName, "uuid") {
			mFields = append(mFields, "func(s string) interface{} { if s == \"\" { return nil }; return s }(m."+goName+")")
		} else if strings.HasSuffix(colName, "uuids") {
			mFields = append(mFields, "func(s []string) interface{} { if len(s) == 0 { return nil }; return s }(m."+goName+")")
		} else {
			mFields = append(mFields, "m."+goName)
		}

		varType := goDataType(field.Desc)
		scanVarName := "v_" + colName

		if field.Desc.IsList() {
			scanVars = append(scanVars, fmt.Sprintf("var %s %s", scanVarName, varType))
			scanAddrs = append(scanAddrs, "&"+scanVarName)
			assignments = append(assignments, fmt.Sprintf("m.%s = %s", goName, scanVarName))
		} else {
			scanVars = append(scanVars, fmt.Sprintf("var %s *%s", scanVarName, varType))
			scanAddrs = append(scanAddrs, "&"+scanVarName)
			assignments = append(assignments, fmt.Sprintf("if %s != nil { m.%s = *%s }", scanVarName, goName, scanVarName))
		}
	}

	colsStr := strings.Join(colNames, ", ")
	valsStr := strings.Join(placeHolders, ", ")
	mFieldsStr := strings.Join(mFields, ", ")

	// --- CREATE ---
	g.P("func Create", msgName, "(ctx context.Context, tx pgx.Tx, m *", msgName, ") error {")
	g.P("	query := `INSERT INTO ", tableName, " (", colsStr, ") VALUES (", valsStr, ")`")
	g.P("	_, err := tx.Exec(ctx, query, ", mFieldsStr, ")")
	g.P("	return err")
	g.P("}")
	g.P()

	// --- GET ---
	g.P("func Get", msgName, "(ctx context.Context, db *pgxpool.Pool, idOrUuid string, cols []string) (*", msgName, ", error) {")
	g.P("	colsStr := \"", colsStr, "\"")
	g.P("	if len(cols) > 0 {")
	g.P("		colsStr = strings.Join(cols, \", \")")
	g.P("	} else {")
	g.P("       cols = []string{\"" + strings.ReplaceAll(colsStr, ", ", "\", \"") + "\"}")
	g.P("   }")
	g.P("	query := `SELECT ` + colsStr + ` FROM ", tableName, " WHERE id = $1 OR uuid::text = $1 LIMIT 1`")

	g.P("	scanArgs := make([]interface{}, len(cols))")
	g.P("	scanAssigns := make([]func(), 0, len(cols))")
	g.P("	m := &", msgName, "{}")
	g.P("	for i, col := range cols {")
	g.P("		switch col {")
	for j, colName := range colNames {
		field := msg.Fields[j]
		goName := field.GoName
		g.P("		case \"", colName, "\":")
		if strings.HasSuffix(colName, "uuid") && colName != "uuid" && !field.Desc.IsList() {
			g.P("			var v *string")
			g.P("			scanArgs[i] = &v")
			g.P("			scanAssigns = append(scanAssigns, func() {")
			g.P("				if v != nil {")
			g.P("					m.", goName, " = *v")
			g.P("				}")
			g.P("			})")
		} else {
			g.P("			scanArgs[i] = &m.", goName)
		}
	}
	g.P("		default:")
	g.P("			var dummy interface{}")
	g.P("			scanArgs[i] = &dummy")
	g.P("		}")
	g.P("	}")
	g.P()
	g.P("	err := db.QueryRow(ctx, query, idOrUuid).Scan(scanArgs...)")
	g.P("	if err != nil {")
	g.P("		return nil, err")
	g.P("	}")
	g.P("	for _, assign := range scanAssigns {")
	g.P("		assign()")
	g.P("	}")
	g.P("	return m, nil")
	g.P("}")
	g.P()

	// --- UPDATE ---
	var updateSets []string
	var updateArgs []string
	updateArgs = append(updateArgs, "m.Uuid")

	argIdx := 2
	for i, field := range msg.Fields {
		colName := string(field.Desc.Name())
		if colName == "uuid" || colName == "id" {
			continue
		}

		colType := ""
		if proto.HasExtension(field.Desc.Options(), quadsmith_sql.E_ColumnType) {
			if ct, ok := proto.GetExtension(field.Desc.Options(), quadsmith_sql.E_ColumnType).(string); ok && ct != "" {
				colType = ct
			}
		}

		if colType != "" {
			updateSets = append(updateSets, fmt.Sprintf("%s = $%d::%s", colName, argIdx, colType))
		} else {
			updateSets = append(updateSets, fmt.Sprintf("%s = $%d", colName, argIdx))
		}

		updateArgs = append(updateArgs, mFields[i])
		argIdx++
	}

	updateSetsStr := strings.Join(updateSets, ", ")
	updateArgsStr := strings.Join(updateArgs, ", ")

	g.P("func Update", msgName, "(ctx context.Context, tx pgx.Tx, m *", msgName, ") error {")
	g.P("	query := `UPDATE ", tableName, " SET ", updateSetsStr, " WHERE uuid = $1`")
	g.P("	_, err := tx.Exec(ctx, query, ", updateArgsStr, ")")
	g.P("	return err")
	g.P("}")
	g.P()

	// --- DELETE ---
	g.P("func Delete", msgName, "(ctx context.Context, tx pgx.Tx, idOrUuid string) error {")
	g.P("	query := `DELETE FROM ", tableName, " WHERE id = $1 OR uuid::text = $1`")
	g.P("	_, err := tx.Exec(ctx, query, idOrUuid)")
	g.P("	return err")
	g.P("}")
	g.P()

	// --- LIST ---
	pluralName := msgName + "s"
	if strings.HasSuffix(msgName, "y") {
		pluralName = strings.TrimSuffix(msgName, "y") + "ies"
	}

	validColsStr := "map[string]bool{\"" + strings.Join(colNames, "\": true, \"") + "\": true}"

	g.P("func List", pluralName, "(ctx context.Context, db *pgxpool.Pool, cols []string, sorts []string, whereClause string, limit int32, offset int32, args ...any) ([]*", msgName, ", error) {")
	g.P("	colsStr := \"", colsStr, "\"")
	g.P("	if len(cols) > 0 {")
	g.P("		colsStr = strings.Join(cols, \", \")")
	g.P("	} else {")
	g.P("       cols = []string{\"" + strings.ReplaceAll(colsStr, ", ", "\", \"") + "\"}")
	g.P("   }")
	g.P("	query := `SELECT ` + colsStr + ` FROM ", tableName, "`")
	g.P("	if whereClause != \"\" {")
	g.P("		query += \" WHERE \" + whereClause")
	g.P("	}")
	g.P("	validCols := " + validColsStr)
	g.P("	var orderClauses []string")
	g.P("	hasIdSort := false")
	g.P("	if len(sorts) > 0 {")
	g.P("		for _, s := range sorts {")
	g.P("			col := s")
	g.P("			dir := \"ASC NULLS LAST\"")
	g.P("			if strings.HasPrefix(s, \"^\") {")
	g.P("				col = s[1:]")
	g.P("				dir = \"DESC NULLS LAST\"")
	g.P("			}")
	g.P("			if !validCols[col] {")
	g.P("				return nil, pagination.ErrInvalidSortColumn(col)")
	g.P("			}")
	g.P("			if col == \"id\" || col == \"uuid\" {")
	g.P("				hasIdSort = true")
	g.P("			}")
	g.P("			orderClauses = append(orderClauses, col + \" \" + dir)")
	g.P("		}")
	g.P("	}")
	g.P("	if !hasIdSort {")
	g.P("		orderClauses = append(orderClauses, \"id ASC\")")
	g.P("	}")
	g.P("	query += \" ORDER BY \" + strings.Join(orderClauses, \", \")")
	g.P("	if limit > 0 {")
	g.P("		query += fmt.Sprintf(\" LIMIT $%d\", len(args)+1)")
	g.P("		args = append(args, limit)")
	g.P("	}")
	g.P("	if offset > 0 {")
	g.P("		query += fmt.Sprintf(\" OFFSET $%d\", len(args)+1)")
	g.P("		args = append(args, offset)")
	g.P("	}")
	g.P("	rows, err := db.Query(ctx, query, args...)")
	g.P("	if err != nil {")
	g.P("		return nil, err")
	g.P("	}")
	g.P("	defer rows.Close()")
	g.P("	results := make([]*", msgName, ", 0)")
	g.P("	for rows.Next() {")

	g.P("		scanArgs := make([]interface{}, len(cols))")
	g.P("		scanAssigns := make([]func(), 0, len(cols))")
	g.P("		m := &", msgName, "{}")
	g.P("		for i, col := range cols {")
	g.P("			switch col {")
	for j, colName := range colNames {
		field := msg.Fields[j]
		goName := field.GoName
		g.P("			case \"", colName, "\":")
		if strings.HasSuffix(colName, "uuid") && colName != "uuid" && !field.Desc.IsList() {
			g.P("				var v *string")
			g.P("				scanArgs[i] = &v")
			g.P("				scanAssigns = append(scanAssigns, func() {")
			g.P("					if v != nil {")
			g.P("						m.", goName, " = *v")
			g.P("					}")
			g.P("				})")
		} else {
			g.P("				scanArgs[i] = &m.", goName)
		}
	}
	g.P("			default:")
	g.P("				var dummy interface{}")
	g.P("				scanArgs[i] = &dummy")
	g.P("			}")
	g.P("		}")
	g.P("		err := rows.Scan(scanArgs...)")
	g.P("		if err != nil {")
	g.P("			return nil, err")
	g.P("		}")
	g.P("		for _, assign := range scanAssigns {")
	g.P("			assign()")
	g.P("		}")
	g.P("		results = append(results, m)")
	g.P("	}")
	g.P("	return results, nil")
	g.P("}")
	g.P()

}

func goDataType(desc protoreflect.FieldDescriptor) string {
	if desc.IsList() {
		switch desc.Kind() {
		case protoreflect.StringKind:
			return "[]string"
		}
		return "[]interface{}"
	}
	switch desc.Kind() {
	case protoreflect.StringKind:
		return "string"
	case protoreflect.Int32Kind:
		return "int32"
	case protoreflect.Int64Kind:
		return "int64"
	case protoreflect.Uint32Kind:
		return "uint32"
	case protoreflect.Uint64Kind:
		return "uint64"
	case protoreflect.FloatKind:
		return "float32"
	case protoreflect.DoubleKind:
		return "float64"
	case protoreflect.BoolKind:
		return "bool"
	default:
		return "string"
	}
}
